(()=>{
'use strict';
const VERSION='8.1.4';
const FAMILY='default-family';
const LS='ofa-8-data';
const ADMIN_EMAIL='mlehr1211@gmail.com';
let deferredInstall=null,fb=false,uid=localStorage.getItem('ofa-uid')||'admin-local',role=localStorage.getItem('ofa-role')||'Admin',route='home',selectedTrip=null,unsub=null;
const $=s=>document.querySelector(s);
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const COLS=['people','trips','memories','media','scrapbooks','meals','grocery','packing','links','invites','notifications','activity','chats','votes','profiles','settings','locks'];
const blank=()=>({version:VERSION,people:[],trips:[],memories:[],media:[],scrapbooks:[],meals:[],grocery:[],packing:[],links:[],invites:[],notifications:[],activity:[],chats:[],votes:[],profiles:[],settings:{theme:'light',notifications:{chat:true,votes:true,trips:true,lists:true,memories:true,admin:true}},locks:{},migrated:false});
let data=load();
function arr(k){ if(!Array.isArray(data[k])) data[k]=[]; return data[k]; }
function st(){data.settings=data.settings||blank().settings;data.settings.notifications=data.settings.notifications||blank().settings.notifications;return data.settings}
function locks(){data.locks=data.locks||{};return data.locks}
function isLocked(area){return !!locks()[area]&&!canAdmin()}
function currentPersonName(){let p=arr('people').find(p=>p.owner===uid||p.email===localStorage.getItem('ofa-email'));return (p&&p.name)|| (canAdmin()?'Melissa':'Family Member')}
function notifyEnabled(kind){return st().notifications[kind]!==false}
function load(){try{return Object.assign(blank(),JSON.parse(localStorage.getItem(LS)||'{}'))}catch{return blank()}}
function save(){migrate(false);data.version=VERSION;localStorage.setItem(LS,JSON.stringify(data));const hasApp=window.firebase&&firebase.apps&&firebase.apps.length;const u=hasApp&&firebase.auth?firebase.auth().currentUser:null;if(fb&&u)firebase.database().ref(`families/${FAMILY}/appData`).set(data).catch(e=>{console.error(e);sync('Saved on this device only');});}
function toast(t){let x=$('#toast'); if(!x) return; x.textContent=t;x.style.display='block';clearTimeout(x._t);x._t=setTimeout(()=>x.style.display='none',3500)}
function sync(t){let x=$('#sync'); if(x)x.textContent=t}
function escape(s=''){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function canAdmin(){return role==='Admin'}
function setIdentity(u){const who=$('#who'); if(u){uid=u.uid;localStorage.setItem('ofa-uid',uid);localStorage.setItem('ofa-email',u.email||'');let profile=arr('people').find(p=>p.email===(u.email||''));role=(u.email===ADMIN_EMAIL||profile?.role==='Admin')?'Admin':(profile?.role||'Family');localStorage.setItem('ofa-role',role);if(who)who.textContent=(u.email||'Signed in')+' · '+role;}else{uid=localStorage.getItem('ofa-uid')||'admin-local';role=localStorage.getItem('ofa-role')||'Admin';if(who)who.textContent=(role==='Admin'?'Melissa · Admin (this device)':'Family Member');}}
function canEdit(item={}){return canAdmin()||!item.private||item.owner===uid||item.createdBy===uid}
function migrate(doSave=true){COLS.forEach(k=>{if(['settings','locks'].includes(k)){data[k]=data[k]||blank()[k]}else if(!Array.isArray(data[k]))data[k]=[]});st();locks();arr('trips').forEach(t=>{t.id=t.id||id();t.visibility=t.visibility||'family';t.invitees=t.invitees||[]});['memories','media','scrapbooks','meals','grocery','packing','links','chats','votes'].forEach(k=>arr(k).forEach(x=>{x.id=x.id||id();x.createdAt=x.createdAt||Date.now();x.owner=x.owner||uid}));data.migrated=true;if(doSave)save()}
function activity(text){arr('activity').unshift({id:id(),text,at:Date.now(),user:uid});data.activity=data.activity.slice(0,120);notify(text,false)}
function notify(text,push=true){arr('notifications').unshift({id:id(),text,at:Date.now(),read:false,user:uid});data.notifications=data.notifications.slice(0,120);if(push&&'Notification'in window&&Notification.permission==='granted'){try{if(navigator.serviceWorker){navigator.serviceWorker.ready.then(reg=>reg.showNotification('Our Family Adventures',{body:text,icon:'./icons/icon-192.png'})).catch(()=>{});} }catch(e){console.warn('Push display skipped',e)}}save()}
function tripsVisible(){return arr('trips').filter(t=>canAdmin()||t.visibility!=='private'||(t.invitees||[]).includes(uid)||t.owner===uid)}
function byTrip(k){return arr(k).filter(x=>x&&(!selectedTrip||x.tripId===selectedTrip))}
function trip(){return arr('trips').find(t=>t.id===selectedTrip)||tripsVisible()[0]}
function peopleOptions(){let p=arr('people');return p.length?p.map(x=>x.name||x.email||'Family member'):['Melissa','Everyone']}
function setRoute(r,arg){route=r;if(arg)selectedTrip=arg;location.hash=arg?`${r}/${arg}`:r;render()}
function parseHash(){let h=(location.hash||'#home').slice(1).split('/');route=h[0]||'home';if(h[1])selectedTrip=h[1]}
function enter(){localStorage.setItem('ofa-entered','yes');$('#splash')?.classList.add('hidden');$('#shell')?.classList.remove('hidden');render()}
function initFirebase(){try{setIdentity(null);if(!window.firebase||!window.firebaseConfig||!firebaseConfig.apiKey){sync('Local admin saving ready');return}if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);sync('Firebase ready · sign in for family sync');firebase.auth().onAuthStateChanged(u=>{if(!u){fb=false;setIdentity(null);sync('Admin on this device · sign in for family sync');render();return}uid=u.uid;fb=true;setIdentity(u);sync('Connected and saving');const ref=firebase.database().ref(`families/${FAMILY}/appData`);if(unsub)ref.off('value',unsub);unsub=ref.on('value',snap=>{if(snap.exists()){data=Object.assign(blank(),snap.val());localStorage.setItem(LS,JSON.stringify(data));migrate(false);render()}else save()});});}catch(e){console.error(e);setIdentity(null);sync('Local admin saving ready')}}
function setup(){window.addEventListener('error',e=>{try{let m=e.message||'check app files'; if(m.includes('Illegal constructor')){console.warn('Notification display skipped');return} sync('Startup issue: '+m)}catch(_){}});sync('Admin on this device · local saving ready');parseHash();if(localStorage.getItem('ofa-entered'))enter();window.addEventListener('hashchange',()=>{parseHash();render()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});let mb=$('#menuBtn'); if(mb)mb.onclick=()=>$('#drawer')?.classList.toggle('open');migrate(false);initFirebase();setTimeout(()=>{if($('#sync')?.textContent?.includes('Starting'))sync('Admin on this device · local saving ready')},1200)}
function nav(){let dock=$('#dock'),drawer=$('#drawer');if(!dock||!drawer)return;let n=[['🏠','Home','home'],['🔐','Login','login'],['🧳','Trips','trips'],['🖼️','Media','media'],['📖','Scrapbook','scrapbook'],['✅','Lists','lists'],['💬','Chat','chat'],['⚙️','Settings','settings']];if(canAdmin())n.push(['🛡️','Admin','admin']);dock.innerHTML=n.map(x=>`<button onclick="app.go('${x[2]}')"><span>${x[0]}</span>${x[1]}</button>`).join('');let pages=['home','login','trips','people','media','memories','scrapbook','meals','grocery','packing','links','voting','analytics','chat','messages','settings','history','notifications'];if(canAdmin())pages.push('admin');drawer.innerHTML='<h2>Menu</h2>'+pages.map(r=>`<button onclick="app.go('${r}');document.querySelector('#drawer').classList.remove('open')">${r[0].toUpperCase()+r.slice(1)}</button>`).join('')+'<button onclick="app.exportData()">Download Backup</button><button onclick="app.importClick()">Import/Migrate Backup</button><input id="importFile" type="file" accept="application/json" class="hidden">'}
function render(){migrate(false);document.body.classList.toggle('dark',st().theme==='dark');nav();let badge=$('#badge'); if(badge)badge.textContent=arr('notifications').filter(n=>!n.read).length;let view=$('#view'); if(!view)return;if(route==='admin'&&!canAdmin())route='home';view.innerHTML=(views[route]||views.home)()+floatingChat(); if(route==='scrapbook') setTimeout(drawScrap,50); setTimeout(makeFloatingChatMoveable,50)}
function card(title,body,cls=''){return `<section class="card ${cls}"><h2>${title}</h2>${body}</section>`}
function form(entity,fields,tripScoped=false){let inputs=fields.map(f=>{if(f.type==='area')return `<textarea id="f_${f.k}" placeholder="${f.l}"></textarea>`; if(f.type==='select')return `<select id="f_${f.k}">${(f.options||[]).map(o=>`<option value="${escape(o.v||o)}">${escape(o.l||o)}</option>`).join('')}</select>`; if(f.type==='people')return `<div class="checks"><b>${escape(f.l)}</b>${peopleOptions().map(p=>`<label><input type="checkbox" name="f_${f.k}" value="${escape(p)}"> ${escape(p)}</label>`).join('')}</div>`; return `<input id="f_${f.k}" type="${f.type||'text'}" placeholder="${f.l}">`}).join('');return `<div class="formgrid">${inputs}</div><button class="primary" onclick='app.add("${entity}",${JSON.stringify(fields.map(f=>f.k))},${tripScoped})'>Add / Save</button>`}
function list(entity,items,fmt,allowDelete=true){items=Array.isArray(items)?items:[];return `<div class="list">${items.length?items.map(x=>`<div class="item"><div class="between row"><div>${fmt(x)}</div><div class="row">${allowDelete&&canEdit(x)?`<button onclick="app.del('${entity}','${x.id}')">Delete</button>`:''}</div></div></div>`).join(''):'<p class="muted">Nothing added yet.</p>'}</div>`}
function tripPicker(){let ts=tripsVisible();if(!selectedTrip&&ts[0])selectedTrip=ts[0].id;return `<select onchange="app.pickTrip(this.value)">${ts.map(t=>`<option ${t.id===selectedTrip?'selected':''} value="${t.id}">${escape(t.name||'Trip')}</option>`).join('')}</select>`}
function selectedTripDates(){let t=trip(); if(!t||!t.start||!t.end)return ['']; let out=[],d=new Date(t.start+'T00:00:00'),end=new Date(t.end+'T00:00:00'); for(let i=0; d<=end && i<45; i++,d.setDate(d.getDate()+1)){out.push(d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric',year:'numeric'}));} return out;}
function featureTabs(){let t=trip();if(!t)return '';return `<div class="navtabs">${['trip','meals','grocery','packing','links','voting','analytics','chat','memories','media','scrapbook'].map(r=>`<button onclick="app.go('${r}','${t.id}')">${r}</button>`).join('')}</div>`}
function recent(){return card('Recent Activity',list('activity',arr('activity').slice(0,8),a=>`<b>${escape(a.text)}</b><p class="muted">${new Date(a.at).toLocaleString()}</p>`,false))}
function floatingChat(){return route==='chat'?'':`<button id="floatChat" class="chat floatChat" onclick="app.go('chat')">💬</button>`}
function makeFloatingChatMoveable(){let b=$('#floatChat');if(!b)return;let pos=JSON.parse(localStorage.getItem('ofa-chat-pos')||'{}');if(pos.x){b.style.left=pos.x+'px';b.style.top=pos.y+'px';b.style.right='auto';b.style.bottom='auto'}let start; b.onpointerdown=e=>{start={x:e.clientX,y:e.clientY,l:b.offsetLeft,t:b.offsetTop,moved:false};b.setPointerCapture(e.pointerId)};b.onpointermove=e=>{if(!start)return;let dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)>6)start.moved=true;if(start.moved){b.style.left=Math.max(6,Math.min(innerWidth-66,start.l+dx))+'px';b.style.top=Math.max(65,Math.min(innerHeight-150,start.t+dy))+'px';b.style.right='auto';b.style.bottom='auto'}};b.onpointerup=e=>{if(start?.moved){localStorage.setItem('ofa-chat-pos',JSON.stringify({x:b.offsetLeft,y:b.offsetTop}));e.preventDefault();e.stopPropagation()}start=null}}
const views={
login(){return card('Admin Login / Family Sync',`<p>You are already opened as <b>Admin on this device</b>. Use this page to connect the app to Firebase so it saves for all family members.</p><div class="formgrid"><input id="loginEmail" type="email" placeholder="Email" value="mlehr1211@gmail.com"><input id="loginPass" type="password" placeholder="Password"></div><div class="row"><button class="primary" onclick="app.signIn()">Sign In</button><button onclick="app.signUpAdmin()">Create Admin Login</button><button onclick="app.signOut()">Sign Out</button></div><p class="muted">If Firebase says the sign-in method is disabled, enable Email/Password in Firebase Authentication. Until then, the app still saves on this device as Admin.</p>`)},
home(){let next=tripsVisible()[0];return card('Welcome Home',`<p>Version ${VERSION}: live family sync, moveable chat bubble, profile photos, family voting with analytics, scrapbook crop/zoom, settings, admin locks, maps/weather, group text/email tools, and rose-gold/greenery colors.</p><div class="grid">${['trips','voting','chat','media','scrapbook','admin'].map(x=>`<div class="card tile" onclick="app.go('${x}')"><h3>${x}</h3><p>Open ${x}</p></div>`).join('')}</div>${next?`<p><button class="primary" onclick="app.go('trip','${next.id}')">Open ${escape(next.name)}</button></p>`:''}<button class="chat" onclick="app.go('chat')">💬</button>`)+recent()},
people(){return card('People / Profiles',`<p class="muted">Family members can update their contact info and change their profile photo.</p><div class="formgrid"><input id="f_name" placeholder="Name"><input id="f_email" type="email" placeholder="Email"><input id="f_phone" placeholder="Phone"><input id="profilePhoto" type="file" accept="image/*"></div><button class="primary" onclick="app.addProfile()">Add / Save Profile</button>`+list('people',arr('people'),p=>`${p.photo?`<img src="${escape(p.photo)}" class="avatar">`:''}<b>${escape(p.name)}</b><p class="muted">${escape(p.email||'')} ${escape(p.phone||'')}</p><div class="row"><button onclick="app.editProfile('${p.id}')">Edit Info</button><label class="buttonLike">Change Photo<input class="hidden" type="file" accept="image/*" onchange="app.changeProfilePhoto('${p.id}',this.files[0])"></label></div>`))},
trips(){return card('Trips',form('trips',[{k:'name',l:'Trip name'},{k:'location',l:'Destination / address'},{k:'start',l:'Arrival date',type:'date'},{k:'end',l:'Departure date',type:'date'},{k:'visibility',l:'Visibility',type:'select',options:['family','private']}])+list('trips',tripsVisible(),t=>`<b>${escape(t.name)}</b><p class="muted">${escape(t.location||'No location')} · ${escape(t.start||'')} ${t.end?'to '+escape(t.end):''}</p><button class="primary" onclick="app.go('trip','${t.id}')">Open dedicated trip page</button>`))},
trip(){let t=trip();if(!t)return views.trips();let q=encodeURIComponent(t.location||t.name||'');let weatherQ=encodeURIComponent(t.location||'York, PA');return featureTabs()+card(escape(t.name||'Trip'),`<p class="muted">${escape(t.location||'Add a trip location for maps and weather')}</p><div class="grid"><iframe class="map" loading="lazy" src="https://www.google.com/maps?q=${q}&output=embed"></iframe><iframe class="weather" loading="lazy" src="https://weather.com/weather/today/l/${weatherQ}"></iframe><p class="muted">Weather Channel embedded forecast for ${escape(t.location||t.name||'trip location')}.</p></div><div class="grid">${['meals','grocery','packing','links','voting','chat','memories','media','scrapbook'].map(x=>`<div class="card tile" onclick="app.go('${x}','${t.id}')"><h3>${x}</h3><p>${byTrip(x==='voting'?'votes':x).length} items</p></div>`).join('')}</div>`)},
meals(){let dates=selectedTripDates();return featureTabs()+card('Meal Planning',tripPicker()+`<h3>Meal list</h3>`+list('meals',byTrip('meals'),m=>`<b>${escape(m.day)} · ${escape(m.type)}</b><p>${escape(m.name||'')}</p><p class="muted">${escape(m.address||'')} ${m.url?` · <a href="${escape(m.url)}" target="_blank">Open link</a>`:''}</p><p class="muted">Assigned: ${escape(m.assignedTo||'Everyone')}</p>`)+`<h3 class="addHead">Add another meal</h3>`+form('meals',[{k:'day',l:'Trip date',type:'select',options:dates},{k:'type',l:'Meal type',type:'select',options:['Breakfast','Lunch','Dinner','Snacks','Happy Hour','Dining Out']},{k:'name',l:'Meal / restaurant name'},{k:'address',l:'Restaurant address'},{k:'url',l:'Restaurant link / reservation URL'},{k:'assignedTo',l:'Assigned to',type:'people'}],true))},
grocery(){return featureTabs()+card('Grocery Lists',tripPicker()+`<h3>Grocery list</h3>`+list('grocery',byTrip('grocery'),g=>`<label class="bigcheck"><input type="checkbox" ${g.done?'checked':''} onchange="app.toggleDone('grocery','${g.id}')"> <b>${escape(g.name)}</b></label><p class="muted">${escape(g.qty||'')} · Assigned: ${escape(g.assignedTo||'Everyone')} ${g.private?'· Private':''}</p>`)+`<h3 class="addHead">Add another grocery item</h3>`+form('grocery',[{k:'name',l:'Item'},{k:'qty',l:'Quantity'},{k:'assignedTo',l:'Assigned to',type:'people'},{k:'private',l:'Private?',type:'select',options:[{v:'',l:'Shared'},{v:'yes',l:'Private'}]}],true))},
packing(){return featureTabs()+card('Packing Lists',tripPicker()+`<h3>Packing list</h3>`+list('packing',byTrip('packing'),p=>`<label class="bigcheck"><input type="checkbox" ${p.done?'checked':''} onchange="app.toggleDone('packing','${p.id}')"> <b>${escape(p.name)}</b></label><p class="muted">Assigned: ${escape(p.assignedTo||'Everyone')} ${p.private?'· Private':''}</p>`)+`<h3 class="addHead">Add another packing item</h3>`+form('packing',[{k:'name',l:'Packing item'},{k:'assignedTo',l:'Assigned to',type:'people'},{k:'private',l:'Private?',type:'select',options:[{v:'',l:'Shared'},{v:'yes',l:'Private'}]}],true))},
links(){return featureTabs()+card('Travel Links',tripPicker()+form('links',[{k:'name',l:'Travel link name'},{k:'url',l:'URL'},{k:'address',l:'Address'},{k:'type',l:'Type',type:'select',options:['Lodging','Restaurant','Activity','Reservation','Map','Other']}],true)+list('links',byTrip('links'),l=>`<b>${escape(l.name)}</b><p class="muted">${escape(l.type||'Link')} ${escape(l.address||'')}</p>${l.url?`<a href="${escape(l.url)}" target="_blank" rel="noopener">Open link</a>`:''}`))},
memories(){return featureTabs()+card('Memories',tripPicker()+`<div class="formgrid"><input id="memTitle" placeholder="Memory title"><input id="memDate" type="date"><textarea id="memText" placeholder="Journal entry"></textarea><input id="memFiles" type="file" multiple accept="image/*,video/*"></div><button class="primary" onclick="app.addMemory()">Save Memory with Photos</button>`+list('memories',byTrip('memories'),m=>`${(m.photos||[]).slice(0,3).map(u=>`<img src="${escape(u)}" style="max-width:100px;border-radius:12px;margin:4px">`).join('')}<b>${escape(m.title)}</b><p>${escape(m.text||'')}</p><p class="muted">${escape(m.date||'')}</p>`))},
media(){return featureTabs()+card('Media Library',tripPicker()+`<input id="mediaFile" type="file" multiple accept="image/*,video/*"><button class="primary" onclick="app.uploadMedia()">Add Media</button>`+list('media',byTrip('media'),m=>`${m.url?`<img src="${escape(m.url)}" style="max-width:120px;border-radius:12px">`:''}<b>${escape(m.name||'Media')}</b><p class="muted">${escape(m.type||'')}</p>${m.url?`<a download="${escape(m.name||'family-photo')}" href="${escape(m.url)}">Download</a>`:''}`))},
scrapbook(){return featureTabs()+card('Scrapbook Studio',tripPicker()+`<p class="muted">Design a page, move/crop/zoom photos, then save/finalize it. Saved pages are locked so photos no longer move.</p><div class="scrapTools"><select id="scrapBg" onchange="app.setScrapBg(this.value)"><option value="seaglass">Sea glass</option><option value="dustyrose">Dusty rose</option><option value="greenery">Greenery</option><option value="rosegold">Rose gold</option><option value="sunset">Sunset</option><option value="sand">Sand</option><option value="lighthouse">Lighthouse</option><option value="beach">Beach</option><option value="mountains">Mountains</option><option value="camping">Camping</option><option value="party">Party</option><option value="happy">Happy Hour</option><option value="city">City Life</option></select><select id="scrapFrame"><option value="soft">Soft frame</option><option value="polaroid">Polaroid</option><option value="gold">Rose-gold frame</option><option value="shell">Shell</option><option value="heart">Heart cutout</option><option value="scallop">Scalloped cutout</option><option value="flower">Flower cutout</option><option value="atv">ATV</option><option value="camping">Camping</option><option value="party">Party</option><option value="happy">Happy Hour</option><option value="beach">Beach</option><option value="mountain">Mountain</option><option value="city">City</option></select><select id="scrapPhotoSelect" multiple size="5">${byTrip('media').filter(m=>m.url&&String(m.type||'').startsWith('image')).map(m=>`<option value="${escape(m.id)}">${escape(m.name)}</option>`).join('')}</select><button onclick="app.addSelectedPhoto()">Add Selected Photo(s)</button><button onclick="app.addScrapText()">Add Text</button><button onclick="app.saveScrapbook()" class="primary">Save / Finalize Page</button></div><div class="scrapTools stickers">${['⭐','😀','😂','😍','❤️','🎉','🏖️','🌊','⛰️','🏕️','🍹','🍻','🍽️','🚗','🏙️','🧭','🧳','🏍️','🛶','🐟','🔥','🌸','☀️','🌙'].map(e=>`<button onclick="app.addSticker('${e}')">${e}</button>`).join('')}</div><div class="scrapTools"><button onclick="app.zoomPhoto(1.12)">Zoom +</button><button onclick="app.zoomPhoto(.88)">Zoom -</button><button onclick="app.cropPhoto()">Crop / Fit</button><button onclick="app.rotatePhoto()">Rotate</button><button onclick="app.bringForward()">Bring Forward</button></div><div class="canvasWrap"><div id="scrapCanvas" class="scrapCanvas seaglass trueLayout"></div></div><h3>Finalized scrapbook pages</h3>`+list('scrapbooks',byTrip('scrapbooks'),s=>`<b>${escape(s.title||'Scrapbook page')}</b><p class="muted">${new Date(s.createdAt).toLocaleString()} · finalized/locked</p><div class="savedScrap">${(s.objects||[]).slice(0,12).map(o=>o.img?`<img src="${escape(o.img)}">`:`<span>${escape(o.text||'')}</span>`).join('')}</div>`))},
voting(){return featureTabs()+card('Family Voting',tripPicker()+`<h3>Current voting options</h3>`+list('votes',byTrip('votes'),v=>`<b>${escape(v.category)}: ${escape(v.name)}</b><p class="muted">${escape(v.address||'')} ${v.url?` · <a href="${escape(v.url)}" target="_blank">Open link</a>`:''}</p><button onclick="app.castVote('${v.id}')">Vote / Change My Vote</button><p class="muted">Voted: ${(v.voters||[]).join(', ')||'No one yet'}</p>`)+`<h3>Add another voting option</h3>`+form('votes',[{k:'category',l:'Vote type',type:'select',options:['Dates','Location','Lodging','Activity','Restaurant']},{k:'name',l:'Voting option'},{k:'url',l:'Link for this option'},{k:'address',l:'Address / notes'}],true)+`<p><button onclick="app.go('analytics')">Open Voting Analytics</button></p>`)},
chat(){return featureTabs()+card('Live Group Chat',`<p class="muted">Messages sync live for signed-in family members. Use the floating chat bubble from any page.</p><div class="chatBox">${byTrip('chats').concat(arr('chats').filter(c=>!c.tripId)).slice(0,80).map(c=>`<div class="chatMsg"><b>${escape(c.userName||'Family')}</b><p>${escape(c.text)}</p><small>${new Date(c.createdAt).toLocaleString()}</small>${canAdmin()?` <button onclick="app.del('chats','${c.id}')">Delete</button>`:''}</div>`).join('')}</div><div class="row"><input id="chatText" placeholder="Message the family"><button class="primary" onclick="app.sendChat()">Send</button></div><p class="muted">Admin can delete old chat messages when the conversation gets too long.</p>` )},
lists(){return `<div class="grid">${['meals','grocery','packing','links','voting','chat'].map(x=>`<div class="card tile" onclick="app.go('${x}')"><h2>${x}</h2><p>Open ${x} page.</p></div>`).join('')}</div>`},
history(){return card('Trip History Map',`<p class="muted">Completed trips with locations become family adventure pins.</p><iframe class="map" src="https://www.google.com/maps?q=${encodeURIComponent(arr('trips').map(t=>t.location).filter(Boolean).join('|')||'United States')}&output=embed"></iframe>`+list('trips',arr('trips').filter(t=>t.location),t=>`📍 <b>${escape(t.name)}</b><p class="muted">${escape(t.location)}</p>`,false))},
notifications(){return card('Notifications',`<button onclick="app.markRead()">Mark all read</button><p class="muted">Notifications can be marked read here. Activity cleanup is under Admin.</p>`+list('notifications',arr('notifications'),n=>`<b>${escape(n.text)}</b><p class="muted">${new Date(n.at).toLocaleString()} ${n.read?'· read':'· unread'}</p>`,false))},

settings(){let n=st().notifications;return card('Settings',`<p>Each family member can choose notification categories and display theme.</p><div class="settingsGrid"><label><input type="checkbox" ${st().theme==='dark'?'checked':''} onchange="app.setTheme(this.checked?'dark':'light')"> Use dark theme</label>${['chat','votes','trips','lists','memories','admin'].map(k=>`<label><input type="checkbox" ${n[k]!==false?'checked':''} onchange="app.setNotify('${k}',this.checked)"> ${k[0].toUpperCase()+k.slice(1)} notifications</label>`).join('')}</div>`)},
analytics(){let rows=byTrip('votes');let cats=[...new Set(rows.map(v=>v.category||'General'))];return featureTabs()+card('Voting Analytics',tripPicker()+cats.map(cat=>`<h3>${escape(cat)}</h3>`+list('votes',rows.filter(v=>v.category===cat),v=>`<b>${escape(v.name)}</b><p class="muted">${(v.voters||[]).length} vote(s): ${(v.voters||[]).map(escape).join(', ')||'No votes yet'}</p>`,false)).join(''))},
messages(){return card('Group Text / Email',`<p>Select family members to send a private group text or email. This opens your phone's text/email app with the selected contacts.</p><div class="checks"><b>Recipients</b>${arr('people').map(p=>`<label><input type="checkbox" name="msgPeople" value="${escape(p.id)}"> ${p.photo?`<img src="${escape(p.photo)}" class="miniAvatar">`:''}${escape(p.name||p.email||'Family')}</label>`).join('')||'<p class="muted">Add profiles first.</p>'}</div><textarea id="msgBody" placeholder="Message"></textarea><div class="row"><button class="primary" onclick="app.sendGroupText()">Open Group Text</button><button onclick="app.sendGroupEmail()">Open Group Email</button></div>`)},
admin(){return canAdmin()?card('Admin Dashboard',`<div class="notice card"><b>Version ${VERSION}</b><p>Admin tools for invites, migration, duplicate prevention, activity cleanup, chat cleanup, push notifications, and backups.</p></div><div class="grid"><div>${form('invites',[{k:'email',l:'Invite email'},{k:'name',l:'Name'},{k:'role',l:'Role',type:'select',options:['Admin','Family','Guest','Child']}])}</div><div class="card"><h3>Tools</h3><button onclick="app.dedupe()">Remove Duplicates</button><button onclick="app.clearActivity()">Clear Activity Log</button><button onclick="app.clearChat()">Clear Chat</button><button onclick="app.requestPush()">Enable Push Notifications</button><button onclick="app.exportData()">Download Backup</button><button onclick="app.migrateNow()">Run Migration</button></div><div class="card"><h3>Admin Locks</h3>${['trips','meals','grocery','packing','links','voting','chat','media','memories','scrapbook'].map(a=>`<label><input type="checkbox" ${locks()[a]?'checked':''} onchange="app.toggleLock('${a}')"> Lock ${a}</label>`).join('')}</div></div>`+list('invites',arr('invites'),i=>`<b>${escape(i.email)}</b><p class="muted">${escape(i.role)} · code ${escape(i.code||'')}</p>`)+recent()):card('Admin Only','<p>This area is only visible to admins.</p>')}
};
function readPeopleChecks(k){return [...document.querySelectorAll(`input[name="f_${k}"]:checked`)].map(x=>x.value).join(', ')}
function add(entity,keys,tripScoped){if(isLocked(entity)){toast('This area is locked by Admin');return}let obj={id:id(),createdAt:Date.now(),owner:uid};keys.forEach(k=>{let checks=document.querySelectorAll(`input[name="f_${k}"]`);obj[k]=checks.length?readPeopleChecks(k):($(`#f_${k}`)||{}).value||''});if(tripScoped)obj.tripId=selectedTrip||((tripsVisible()[0]||{}).id);if(entity==='invites')obj.code=(Math.random().toString(36).slice(2,8)).toUpperCase();if(obj.private==='yes')obj.private=true;else delete obj.private;let dupe=arr(entity).some(x=>keys.every(k=>(x[k]||'')===(obj[k]||''))&&(x.tripId||'')===(obj.tripId||''));if(dupe){toast('Duplicate prevented');return}arr(entity).unshift(obj);save();activity(`Added ${entity.replace(/s$/,'')}`);keys.forEach(k=>{let el=$(`#f_${k}`);if(el)el.value='';document.querySelectorAll(`input[name="f_${k}"]`).forEach(c=>c.checked=false)});render()}
function del(entity,itemId){if(!canAdmin()&&entity==='activity'){toast('Only Admin can delete activity');return}if(!confirm('Delete this item?'))return;data[entity]=arr(entity).filter(x=>x.id!==itemId);save();activity(`Deleted ${entity} item`);render()}
function dedupe(){let count=0;COLS.forEach(k=>{let seen=new Set();data[k]=arr(k).filter(x=>{let sig=JSON.stringify([x.tripId,x.name,x.title,x.url,x.email,x.day,x.type,x.text]);if(seen.has(sig)){count++;return false}seen.add(sig);return true})});save();toast(`Removed ${count} duplicates`);render()}
function fileToDataURL(f){return new Promise(res=>{let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)})}
async function uploadOne(f,prefix='media'){let obj={id:id(),tripId:selectedTrip,owner:uid,name:f.name,type:f.type,createdAt:Date.now()};if(fb&&window.firebase&&firebase.storage){let path=`families/${FAMILY}/${prefix}/${obj.id}-${f.name}`;let snap=await firebase.storage().ref(path).put(f);obj.url=await snap.ref.getDownloadURL()}else obj.url=await fileToDataURL(f);return obj}
async function uploadMedia(){let files=[...($('#mediaFile')?.files||[])];for(const f of files){arr('media').unshift(await uploadOne(f,'media'))}save();activity(`Added ${files.length} media file(s)`);render()}
async function addMemory(){let files=[...($('#memFiles')?.files||[])],photos=[];for(const f of files){let m=await uploadOne(f,'memories');arr('media').unshift(m);photos.push(m.url)}arr('memories').unshift({id:id(),tripId:selectedTrip,owner:uid,title:$('#memTitle')?.value||'Memory',date:$('#memDate')?.value||'',text:$('#memText')?.value||'',photos,createdAt:Date.now()});save();activity('Added memory');render()}
async function signIn(){try{if(!window.firebase||!firebase.apps.length)initFirebase();if(!window.firebase||!firebase.apps.length){toast('Firebase is not loaded yet; local Admin saving is active');return}let e=$('#loginEmail').value.trim(),p=$('#loginPass').value;if(!e||!p){toast('Enter email and password');return}await firebase.auth().signInWithEmailAndPassword(e,p);toast('Signed in as Admin')}catch(err){console.error(err);toast(err.message||'Login failed')}}
async function signUpAdmin(){try{if(!window.firebase||!firebase.apps.length)initFirebase();if(!window.firebase||!firebase.apps.length){toast('Firebase is not loaded yet; local Admin saving is active');return}let e=$('#loginEmail').value.trim(),p=$('#loginPass').value;if(!e||!p){toast('Enter email and password');return}await firebase.auth().createUserWithEmailAndPassword(e,p);role='Admin';localStorage.setItem('ofa-role','Admin');toast('Admin login created')}catch(err){console.error(err);toast(err.message||'Could not create login')}}
async function signOut(){try{if(window.firebase&&firebase.auth)await firebase.auth().signOut();fb=false;setIdentity(null);toast('Signed out — still Admin on this device');render()}catch(e){toast('Signed out locally')}}
function requestPush(){try{if(!('Notification'in window)||typeof Notification.requestPermission!=='function'){toast('Notifications not supported');return}Notification.requestPermission().then(p=>toast(p==='granted'?'Notifications enabled':'Notifications not enabled')).catch(()=>toast('Notifications not enabled'))}catch(e){toast('Notifications not supported on this browser')}}
function markRead(){arr('notifications').forEach(n=>n.read=true);save();render()}
function install(){if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else toast('Use browser menu: Add to Home screen')}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='our-family-adventures-backup-8.1.4.json';a.click()}
function importClick(){$('#importFile').click();$('#importFile').onchange=e=>{let f=e.target.files[0];let r=new FileReader();r.onload=()=>{data=Object.assign(blank(),JSON.parse(r.result));migrate(false);save();toast('Backup imported')};r.readAsText(f)}}
function setScrapBg(v){let c=$('#scrapCanvas'); if(c){c.className='scrapCanvas '+v}}
function scrapObjs(){window.scrapObjs=window.scrapObjs||[];return window.scrapObjs}
function drawScrap(){let c=$('#scrapCanvas');if(!c)return;c.innerHTML='';scrapObjs().forEach(o=>{let d=document.createElement('div');d.className='scrapObj '+(o.frame||'soft')+(o.sticker?' stickerObj':'');d.style.left=o.x+'px';d.style.top=o.y+'px';d.style.width=o.w+'px';d.style.height=o.h+'px';d.style.zIndex=o.z||1;d.style.transform=`rotate(${o.rot||0}deg)`;d.innerHTML=o.img?`<img src="${o.img}" alt="photo" style="object-fit:${o.fit||'cover'};transform:scale(${o.zoom||1});transform-origin:center"><i class="handle"></i>`:`<span contenteditable="${o.sticker?'false':'true'}">${escape(o.text||'Text')}</span><i class="handle"></i>`;d.onclick=()=>{window.selectedScrapObj=o;document.querySelectorAll('.scrapObj').forEach(x=>x.classList.remove('selected'));d.classList.add('selected')};c.appendChild(d);makeDrag(d,o)})}
function makeDrag(el,o){let start,mode='move';el.onpointerdown=e=>{mode=e.target.className==='handle'?'size':'move';start={x:e.clientX,y:e.clientY,ox:o.x,oy:o.y,ow:o.w,oh:o.h};o.z=Date.now();window.selectedScrapObj=o;el.classList.add('selected');el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!start)return;let dx=e.clientX-start.x,dy=e.clientY-start.y;if(mode==='size'){o.w=Math.max(70,start.ow+dx);o.h=Math.max(70,start.oh+dy);el.style.width=o.w+'px';el.style.height=o.h+'px'}else{o.x=Math.max(0,start.ox+dx);o.y=Math.max(0,start.oy+dy);el.style.left=o.x+'px';el.style.top=o.y+'px'}};el.onpointerup=()=>{start=null}}
function addScrapText(){scrapObjs().push({text:'Family memory',x:60,y:60,w:190,h:90,z:1});drawScrap()}
function addSticker(s){scrapObjs().push({text:s,x:90,y:90,w:72,h:72,z:1,sticker:true,frame:'nofill'});drawScrap()}
function addSelectedPhoto(){let sel=[...($('#scrapPhotoSelect')?.selectedOptions||[])].map(o=>o.value);if(!sel.length&&$('#scrapPhotoSelect')?.value)sel=[$('#scrapPhotoSelect').value];let added=0;sel.forEach((mid,i)=>{let m=arr('media').find(x=>x.id===mid);if(m&&m.url){scrapObjs().push({img:m.url,frame:$('#scrapFrame')?.value||'soft',x:40+(i*28),y:60+(i*28),w:210,h:165,z:1,fit:'cover',zoom:1,rot:0});added++}});if(!added){toast('Add photos in Media first');return}drawScrap()}
function saveScrapbook(){arr('scrapbooks').unshift({id:id(),tripId:selectedTrip,owner:uid,title:'Scrapbook page',background:$('#scrapBg')?.value||'seaglass',objects:JSON.parse(JSON.stringify(scrapObjs())),locked:true,createdAt:Date.now()});window.scrapObjs=[];save();activity('Saved scrapbook page');render()}
function sendChat(){let text=$('#chatText')?.value?.trim(); if(!text)return;arr('chats').unshift({id:id(),tripId:selectedTrip||'',text,user:uid,userName:canAdmin()?'Melissa/Admin':'Family',createdAt:Date.now()});save();notify('New group chat message');render()}
function castVote(voteId){let v=arr('votes').find(x=>x.id===voteId);if(!v)return;let name=currentPersonName();arr('votes').filter(x=>x.tripId===v.tripId&&x.category===v.category).forEach(x=>{x.voters=(x.voters||[]).filter(n=>n!==name)});v.voters=v.voters||[];v.voters.push(name);save();activity('Added/changed vote');render()}

async function addProfile(){let obj={id:id(),name:$('#f_name')?.value||'',email:$('#f_email')?.value||'',phone:$('#f_phone')?.value||'',owner:uid,createdAt:Date.now()};let f=$('#profilePhoto')?.files?.[0];if(f)obj.photo=await fileToDataURL(f);let existing=arr('people').find(p=>(obj.email&&p.email===obj.email)||p.owner===uid&&p.name===obj.name);if(existing)Object.assign(existing,obj,{id:existing.id});else arr('people').unshift(obj);save();activity('Updated profile');render()}
function editProfile(pid){let p=arr('people').find(x=>x.id===pid);if(!p)return;let name=prompt('Name',p.name||'');if(name===null)return;let email=prompt('Email',p.email||'');if(email===null)return;let phone=prompt('Phone',p.phone||'');if(phone===null)return;Object.assign(p,{name,email,phone,updatedAt:Date.now()});save();activity('Updated profile');render()}
function zoomPhoto(factor){let o=window.selectedScrapObj;if(!o||!o.img){toast('Tap a photo first');return}o.zoom=(o.zoom||1)*factor;drawScrap()}
function cropPhoto(){let o=window.selectedScrapObj;if(!o||!o.img){toast('Tap a photo first');return}o.fit=o.fit==='cover'?'contain':'cover';drawScrap()}


async function changeProfilePhoto(pid,file){let p=arr('people').find(x=>x.id===pid);if(!p||!file)return;p.photo=await fileToDataURL(file);p.updatedAt=Date.now();save();activity('Changed profile photo');render()}
function setTheme(v){st().theme=v;save();render()}
function setNotify(k,v){st().notifications[k]=v;save();toast('Settings saved')}
function rotatePhoto(){let o=window.selectedScrapObj;if(!o){toast('Tap an object first');return}o.rot=((o.rot||0)+15)%360;drawScrap()}
function bringForward(){let o=window.selectedScrapObj;if(!o){toast('Tap an object first');return}o.z=Date.now();drawScrap()}
function selectedMsgPeople(){return [...document.querySelectorAll('input[name="msgPeople"]:checked')].map(i=>arr('people').find(p=>p.id===i.value)).filter(Boolean)}
function sendGroupText(){let ps=selectedMsgPeople(),body=encodeURIComponent($('#msgBody')?.value||'');let nums=ps.map(p=>(p.phone||'').replace(/[^0-9+]/g,'')).filter(Boolean);if(!nums.length){toast('Select people with phone numbers');return}location.href=`sms:${nums.join(',')}?&body=${body}`}
function sendGroupEmail(){let ps=selectedMsgPeople(),body=encodeURIComponent($('#msgBody')?.value||''),emails=ps.map(p=>p.email).filter(Boolean);if(!emails.length){toast('Select people with email addresses');return}location.href=`mailto:${emails.join(',')}?subject=Our Family Adventures&body=${body}`}
function toggleLock(area){if(!canAdmin())return;locks()[area]=!locks()[area];save();render()}

window.app={enter,signIn,signUpAdmin,signOut,go:setRoute,pickTrip:v=>{selectedTrip=v;render()},add,del,dedupe,uploadMedia,addMemory,requestPush,markRead,install,exportData,importClick,migrateNow:()=>{migrate(false);save();toast('Migration complete')},notify:()=>setRoute('notifications'),toggleDone:(e,i)=>{let x=arr(e).find(y=>y.id===i);if(x){x.done=!x.done;save();render()}},addScrapText,addSticker,addSelectedPhoto,saveScrapbook,setScrapBg,sendChat,castVote,clearActivity:()=>{if(confirm('Clear activity log?')){data.activity=[];save();render()}},clearChat:()=>{if(confirm('Clear chat messages?')){data.chats=[];save();render()}},addProfile,editProfile,zoomPhoto,cropPhoto,changeProfilePhoto,setTheme,setNotify,rotatePhoto,bringForward,sendGroupText,sendGroupEmail,toggleLock};
setup();
})();
