(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const key='ofa8-data'; let user=null, db=null, auth=null, unsub=[]; let selectedScrap=null, installPrompt=null;
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const blank={trips:[],profiles:[],invites:[],itineraries:[],reservations:[],budgets:[],links:[],meals:[],groceries:[],packing:[],notes:[],memories:[],pages:[],notifications:[],activity:[],presence:[],activeTripId:null,readAt:0};
let data={...blank,...JSON.parse(localStorage.getItem(key)||'{}')};
function me(){return user?.email||localStorage.getItem('ofaGuest')||(localStorage.setItem('ofaGuest','guest-'+uid()),localStorage.getItem('ofaGuest'));}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function save(){localStorage.setItem(key,JSON.stringify(data));renderAll();}
function log(text, privacy='shared', tripId='', people=[]){data.activity.unshift({id:uid(),text,privacy,tripId,people,owner:me(),at:Date.now()});data.notifications.unshift({id:uid(),text,owner:me(),at:Date.now(),read:false,tripId,privacy,people});localStorage.setItem(key,JSON.stringify(data));cloudSave('activity',data.activity[0]);cloudSave('notifications',data.notifications[0]);}
function canSee(o){ if(!o) return true; if(o.privacy!=='private') return true; if(o.owner===me()) return true; if((o.people||o.invitees||[]).includes(me())) return true; const t=data.trips.find(x=>x.id===o.tripId); return !!(t&&(t.owner===me()||(t.invitees||[]).includes(me()))); }
function activeTrip(){return data.trips.find(t=>t.id===data.activeTripId)||data.trips.filter(canSee)[0]||null;}
function tripPeople(t=activeTrip()){const emails=new Set([me(),...(t?.invitees||[]),...data.profiles.map(p=>p.email).filter(Boolean)]);return [...emails];}
function add(col,obj,msg){obj={id:uid(),owner:me(),createdAt:Date.now(),...obj};data[col].unshift(obj); if(!data.activeTripId&&col==='trips') data.activeTripId=obj.id; localStorage.setItem(key,JSON.stringify(data)); cloudSave(col,obj); log(msg||'Saved',obj.privacy||'shared',obj.tripId||obj.id,obj.people||obj.invitees||[]); clearForms(); renderAll(); toast(msg||'Saved');}
function del(col,id){const item=data[col].find(x=>x.id===id); data[col]=data[col].filter(x=>x.id!==id); localStorage.setItem(key,JSON.stringify(data)); cloudDelete(col,id); log('Deleted item',item?.privacy,item?.tripId,[item?.owner].filter(Boolean)); renderAll();}
function update(col,id,patch,msg){const i=data[col].findIndex(x=>x.id===id); if(i<0)return; data[col][i]={...data[col][i],...patch,updatedAt:Date.now()}; localStorage.setItem(key,JSON.stringify(data)); cloudSave(col,data[col][i]); if(msg) log(msg,data[col][i].privacy,data[col][i].tripId,data[col][i].people); renderAll();}
function clearForms(){ $$('input:not([type=file]):not([type=checkbox]), textarea').forEach(x=>x.value=''); $$('input[type=file]').forEach(x=>x.value=''); }
async function cloudSave(col,obj){ if(!db||!user)return; try{await db.collection('families').doc('main').collection(col).doc(obj.id).set(obj,{merge:true});}catch(e){console.warn(e)} }
async function cloudDelete(col,id){ if(!db||!user)return; try{await db.collection('families').doc('main').collection(col).doc(id).delete();}catch(e){console.warn(e)} }
function initFirebase(){try{ if(window.firebase&&window.firebaseConfig){firebase.initializeApp(window.firebaseConfig);auth=firebase.auth();db=firebase.firestore();db.enablePersistence({synchronizeTabs:true}).catch(()=>{});auth.onAuthStateChanged(u=>{user=u; $('#syncStatus').textContent=u?'Live sync on':'Sign in for live sync'; if(u){startLive(); setPresence();} renderAll();});}}catch(e){$('#syncStatus').textContent='Local mode';}}
function startLive(){unsub.forEach(f=>f());unsub=[];Object.keys(blank).filter(k=>Array.isArray(blank[k])).forEach(col=>{unsub.push(db.collection('families').doc('main').collection(col).onSnapshot(s=>{s.docChanges().forEach(ch=>{const obj={id:ch.doc.id,...ch.doc.data()}; if(ch.type==='removed') data[col]=data[col].filter(x=>x.id!==obj.id); else {const i=data[col].findIndex(x=>x.id===obj.id); if(i>=0)data[col][i]=obj; else data[col].unshift(obj);}});localStorage.setItem(key,JSON.stringify(data));renderAll();}));});}
function setPresence(){const p={id:me().replace(/[^a-z0-9]/gi,'_'),email:me(),name:user?.displayName||me().split('@')[0],at:Date.now(),online:true};data.presence=data.presence.filter(x=>x.id!==p.id);data.presence.push(p);cloudSave('presence',p);setInterval(()=>cloudSave('presence',{...p,at:Date.now(),online:true}),30000);}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#drawer').classList.remove('open'); if(id==='notifications'){data.notifications.forEach(n=>n.read=true);localStorage.setItem(key,JSON.stringify(data));} renderAll();}
function daysBetween(a,b){if(!a||!b)return[];let out=[],d=new Date(a+'T12:00');const end=new Date(b+'T12:00');while(d<=end){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out;}
function dateLabel(d){return d?new Date(d+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}):''}
function gmap(q){return 'https://www.google.com/maps?q='+encodeURIComponent(q||'');}
function weather(q){return 'https://www.google.com/search?q='+encodeURIComponent('live weather '+(q||''));}
function renderOptions(){const trips=data.trips.filter(canSee); const opts=trips.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join(''); ['#activeTripSelect','#memoryTrip'].forEach(s=>{const el=$(s); if(el){el.innerHTML=opts||'<option>No trips</option>'; if(data.activeTripId)el.value=data.activeTripId;}}); const people=data.profiles.map(p=>`<option value="${esc(p.email)}">${esc(p.name||p.email)}</option>`).join(''); $('#tripInvitees').innerHTML=people; $('#messageMembers').innerHTML=people; $('#mealPerson').innerHTML=tripPeople().map(e=>`<option>${esc(e)}</option>`).join(''); const t=activeTrip(); $('#mealDate').innerHTML=daysBetween(t?.arrival,t?.departure).map(d=>`<option value="${d}">${dateLabel(d)}</option>`).join('')||'<option value="">Select trip dates first</option>';}
function renderTrips(){const trips=data.trips.filter(canSee); $('#tripList').innerHTML=trips.map(t=>`<div class="listItem"><h3>${esc(t.name)} ${t.privacy==='private'?'🔒':''}</h3><p>${esc(t.destination||'No destination')}</p><p><b>Arrival:</b> ${esc(t.arrival||'')} <b>Departure:</b> ${esc(t.departure||'')}</p><p>${esc(t.notes||'')}</p><div class="actions"><button onclick="OFA.openTrip('${t.id}')">Open Trip Page</button><button onclick="OFA.completeTrip('${t.id}')">Mark Complete</button><button onclick="OFA.del('trips','${t.id}')">Delete</button></div></div>`).join('')||'<p class="muted">No trips yet.</p>';}
function renderDetail(){const t=activeTrip(); if(!t){$('#detailTitle').textContent='Trip Workspace'; return;} $('#detailTitle').textContent=t.name; $('#detailDates').innerHTML=`<p><b>Arrival:</b> ${esc(t.arrival||'')}</p><p><b>Departure:</b> ${esc(t.departure||'')}</p><p><b>Destination:</b> ${esc(t.destination||'')}</p>`; $('#mapFrame').src='https://maps.google.com/maps?q='+encodeURIComponent(t.destination||t.name)+'&output=embed'; $('#tripRsvp').innerHTML=`<h3>RSVP / Suggestions</h3><div class="row"><button onclick="OFA.rsvp('${t.id}','attending')">Attending</button><button onclick="OFA.rsvp('${t.id}','cant make it')">Can't Make It</button><button onclick="OFA.propose('${t.id}','date')">Propose New Date</button><button onclick="OFA.propose('${t.id}','location')">Suggest Location</button></div><p>${Object.entries(t.rsvps||{}).map(([k,v])=>esc(k+': '+v)).join('<br>')||'No RSVP yet.'}</p>`; const byTrip=c=>data[c].filter(x=>x.tripId===t.id).filter(canSee); $('#itineraryList').innerHTML=byTrip('itineraries').map(x=>item(x,`${dateLabel(x.date)} ${esc(x.time||'')} — ${esc(x.title)}`,'itineraries')).join(''); $('#reservationList').innerHTML=byTrip('reservations').map(x=>item(x,`${esc(x.title)} ${x.url?`<a href="${esc(x.url)}" target="_blank">Open</a>`:''}<br>${esc(x.notes||'')}`,'reservations')).join(''); $('#budgetList').innerHTML=byTrip('budgets').map(x=>item(x,`${esc(x.title)} — $${Number(x.amount||0).toFixed(2)}`,'budgets')).join('')+`<p><b>Total:</b> $${byTrip('budgets').reduce((a,b)=>a+Number(b.amount||0),0).toFixed(2)}</p>`; $('#linkList').innerHTML=byTrip('links').map(x=>item(x,`<a href="${esc(x.url)}" target="_blank">${esc(x.title||x.url)}</a>`,'links')).join(''); $('#mealList').innerHTML=byTrip('meals').map(x=>item(x,`${dateLabel(x.date)} ${esc(x.type)}: ${esc(x.title)}<br><small>Accepted by/assigned: ${esc(x.person||'')}</small>`,'meals')).join(''); $('#groceryList').innerHTML=byTrip('groceries').map(x=>checkItem(x,'groceries')).join(''); $('#packingList').innerHTML=byTrip('packing').map(x=>checkItem(x,'packing')).join(''); $('#noteList').innerHTML=byTrip('notes').map(x=>item(x,`${x.privacy==='private'?'🔒 ':''}${esc(x.text)}`,'notes')).join('');}
function item(x,body,col){return `<div class="listItem small">${body}<div class="actions"><button onclick="OFA.del('${col}','${x.id}')">Delete</button></div></div>`}
function checkItem(x,col){const checked=(x.checkedBy||[]).includes(me());return `<div class="listItem small"><label><input type="checkbox" ${checked?'checked':''} onchange="OFA.toggleCheck('${col}','${x.id}',this.checked)"> ${x.privacy==='private'?'🔒 ':''}${esc(x.text)}</label><div class="actions"><button onclick="OFA.del('${col}','${x.id}')">Delete</button></div></div>`}
function renderHistory(){const done=data.trips.filter(t=>t.completed&&canSee(t)); const q=done.map(t=>t.destination).filter(Boolean).join('|'); $('#historyFrame').src=done[0]?'https://maps.google.com/maps?q='+encodeURIComponent(q||done[0].destination)+'&output=embed':''; $('#historyPins').innerHTML=done.map(t=>`<div class="listItem"><h3>📍 ${esc(t.name)}</h3><p>${esc(t.destination)}</p><p>${esc(t.arrival)} - ${esc(t.departure)}</p><button onclick="OFA.openTrip('${t.id}')">Open Memories & Trip</button></div>`).join('')||'<p class="muted">Mark a trip complete to add a pin.</p>';}
function renderScrap(){ $('#pageList').innerHTML=data.pages.filter(canSee).map(p=>`<div class="listItem"><h3>${esc(p.title||'Scrapbook page')}</h3><button onclick="OFA.loadPage('${p.id}')">Open</button><button onclick="OFA.del('pages','${p.id}')">Delete</button></div>`).join('');}
function renderMemories(){ $('#memoryTimeline').innerHTML=data.memories.filter(canSee).map(m=>`<div class="memoryCard">${(m.files||[]).map(f=>f.type?.startsWith('video')?`<video controls src="${f.url}"></video>`:`<img src="${f.url}" alt="">`).join('')}<div><b>${esc(m.title||'Memory')}</b><p>${esc(m.text||'')}</p><small>${esc(m.album||'')} ${esc(m.date||'')}</small></div></div>`).join('')||'<p class="muted">No memories saved yet.</p>';}
function renderFamily(){ $('#familyList').innerHTML=data.profiles.map(p=>`<div class="listItem"><h3>${esc(p.name||p.email)}</h3><p>${esc(p.email||'')} ${esc(p.phone||'')}</p><small>${esc(p.role||'Family')}</small><div class="actions"><button onclick="OFA.del('profiles','${p.id}')">Delete</button></div></div>`).join('');}
function renderMessages(){ if($('#selectAllMembers').checked){[...$('#messageMembers').options].forEach(o=>o.selected=true);} }
function renderNotifications(){const unread=data.notifications.filter(n=>!n.read&&canSee(n)).length; $('#badge').textContent=unread; $('#statUnread').textContent=unread; $('#notificationList').innerHTML=data.notifications.filter(canSee).map(n=>`<div class="listItem"><h3>${n.read?'✓':'🔔'} Notification</h3><p>${esc(n.text)}</p><small>${new Date(n.at||Date.now()).toLocaleString()}</small></div>`).join('')||'<p class="muted">No notifications.</p>';}
function renderAdmin(){ $('#adminSummary').innerHTML=`Trips: ${data.trips.length}<br>Members: ${data.profiles.length}<br>Memories: ${data.memories.length}<br>Version: 8.0`; $('#activityList').innerHTML=data.activity.filter(canSee).map(a=>`<div class="listItem small">${a.privacy==='private'?'🔒 ':''}${esc(a.text)}<br><small>${new Date(a.at).toLocaleString()}</small></div>`).join(''); }
function renderOnline(){const now=Date.now(); $('#onlineList').innerHTML=data.presence.filter(p=>now-(p.at||0)<90000).map(p=>`<div class="listItem small">🟢 ${esc(p.name||p.email)} online</div>`).join('')||'<p class="muted">No signed-in users online.</p>';}
function renderAll(){renderOptions();renderTrips();renderDetail();renderHistory();renderScrap();renderMemories();renderFamily();renderMessages();renderNotifications();renderAdmin();renderOnline(); const trips=data.trips.filter(canSee); $('#statTrips').textContent=trips.length; $('#statMemories').textContent=data.memories.filter(canSee).length; $('#statOpen').textContent=data.groceries.length+data.packing.length; const next=trips.find(t=>t.arrival&&new Date(t.arrival)>=new Date()); if(next){$('#nextTripLine').textContent=next.name+' • '+next.destination; const days=Math.ceil((new Date(next.arrival)-new Date())/86400000); $('#countdown').textContent=days+' days until arrival';} }
function filesToData(files){return Promise.all([...files].map(f=>new Promise(res=>{const r=new FileReader();r.onload=()=>res({name:f.name,type:f.type,url:r.result});r.readAsDataURL(f)})));}
function makeScrap(type,content){const el=document.createElement('div');el.className='scrapItem selected '+(type==='frame'?'scrapFrame':'');el.dataset.id=uid();el.dataset.type=type;Object.assign(el.style,{left:'40px',top:'40px',width:type==='text'?'190px':'180px',height:type==='text'?'80px':'140px',fontSize:'28px'}); if(type==='image')el.innerHTML=`<img src="${content}">`;else if(type==='text')el.innerHTML=`<div class="scrapText" contenteditable="true">${esc(content)}</div>`;else if(type==='frame')el.innerHTML='';else el.textContent=content; $('#scrapCanvas').appendChild(el);selectScrap(el);dragScrap(el);}
function selectScrap(el){$$('.scrapItem').forEach(x=>x.classList.remove('selected'));selectedScrap=el;if(el)el.classList.add('selected');}
function dragScrap(el){if(el.dataset.drag)return;el.dataset.drag=1;let sx,sy,l,t;el.addEventListener('pointerdown',e=>{if(e.target.isContentEditable)return;selectScrap(el);sx=e.clientX;sy=e.clientY;l=parseFloat(el.style.left)||0;t=parseFloat(el.style.top)||0;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(sx==null)return;el.style.left=l+e.clientX-sx+'px';el.style.top=t+e.clientY-sy+'px'});el.addEventListener('pointerup',()=>sx=null);el.addEventListener('dblclick',()=>{el.style.width=(parseFloat(el.style.width)+35)+'px';el.style.height=(parseFloat(el.style.height)+35)+'px'});}
window.OFA={del,openTrip(id){data.activeTripId=id;save();showPage('tripDetail')},completeTrip(id){update('trips',id,{completed:true},'Trip completed and added to history map')},rsvp(id,status){const t=data.trips.find(x=>x.id===id);update('trips',id,{rsvps:{...(t.rsvps||{}),[me()]:status}},'RSVP updated')},propose(id,type){const v=prompt(type==='date'?'Propose new date':'Suggest new location');if(v){const t=data.trips.find(x=>x.id===id);update('trips',id,{proposals:[...(t.proposals||[]),{by:me(),type,value:v,at:Date.now()}]},'Trip proposal added')}},toggleCheck(col,id,on){const x=data[col].find(i=>i.id===id);const set=new Set(x.checkedBy||[]);on?set.add(me()):set.delete(me());update(col,id,{checkedBy:[...set]})},loadPage(id){const p=data.pages.find(x=>x.id===id);$('#scrapCanvas').innerHTML=p?.html||'';$$('.scrapItem').forEach(dragScrap);showPage('scrapbook')}};
function bind(){ $('#beginBtn').onclick=()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden')}; $('#menuBtn').onclick=()=>$('#drawer').classList.add('open'); $('#closeDrawer').onclick=()=>$('#drawer').classList.remove('open'); $$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page)); $('#notifyBtn').onclick=()=>showPage('notifications'); $('#loginBtn').onclick=()=>$('#authModal').classList.remove('hidden'); $('[data-close-auth]').onclick=()=>$('#authModal').classList.add('hidden'); $('#signInBtn').onclick=()=>auth?auth.signInWithEmailAndPassword($('#authEmail').value,$('#authPassword').value).then(()=>$('#authModal').classList.add('hidden')).catch(e=>toast(e.message)):toast('Firebase is not available'); $('#createAccountBtn').onclick=()=>auth?auth.createUserWithEmailAndPassword($('#authEmail').value,$('#authPassword').value).then(()=>$('#authModal').classList.add('hidden')).catch(e=>toast(e.message)):toast('Firebase is not available'); $('#resetPasswordBtn').onclick=()=>auth&&$('#authEmail').value?auth.sendPasswordResetEmail($('#authEmail').value).then(()=>toast('Reset email sent')):toast('Enter email first'); $('#signOut').onclick=()=>auth?.signOut(); window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e}); $('#installBtn').onclick=()=>installPrompt?installPrompt.prompt():toast('iPhone: Safari Share → Add to Home Screen. Android: browser menu → Install.');
$('#tripArrival').onchange=()=>{ if(!$('#tripDeparture').value) $('#tripDeparture').value=$('#tripArrival').value; $('#tripDeparture').min=$('#tripArrival').value;}; $('#saveTrip').onclick=()=>{const name=$('#tripName').value.trim(); if(!name)return toast('Trip name required'); const invitees=[...$('#tripInvitees').selectedOptions].map(o=>o.value); add('trips',{name,destination:$('#tripDestination').value,arrival:$('#tripArrival').value,departure:$('#tripDeparture').value,notes:$('#tripNotes').value,privacy:$('#tripPrivate').checked?'private':'shared',invitees},'Trip saved')}; $('#activeTripSelect').onchange=e=>{data.activeTripId=e.target.value;save()}; $('#openMap').onclick=()=>window.open(gmap(activeTrip()?.destination||''),'_blank'); $('#openWeather').onclick=()=>window.open(weather(activeTrip()?.destination||''),'_blank'); $('#addPhoneCalendar').onclick=()=>{const t=activeTrip(); if(!t)return; const s=(t.arrival||'').replaceAll('-',''), e=(t.departure||t.arrival||'').replaceAll('-',''); window.open(`data:text/calendar,BEGIN:VCALENDAR%0AVERSION:2.0%0ABEGIN:VEVENT%0ASUMMARY:${encodeURIComponent(t.name)}%0ADTSTART;VALUE=DATE:${s}%0ADTEND;VALUE=DATE:${e}%0ALOCATION:${encodeURIComponent(t.destination||'')}%0AEND:VEVENT%0AEND:VCALENDAR`,'_blank')};
$('#saveItinerary').onclick=()=>add('itineraries',{tripId:activeTrip()?.id,date:$('#itineraryDate').value,time:$('#itineraryTime').value,title:$('#itineraryTitle').value},'Itinerary added'); $('#saveReservation').onclick=()=>add('reservations',{tripId:activeTrip()?.id,title:$('#reservationTitle').value,url:$('#reservationUrl').value,notes:$('#reservationNotes').value},'Reservation added'); $('#saveBudget').onclick=()=>add('budgets',{tripId:activeTrip()?.id,title:$('#budgetTitle').value,amount:$('#budgetAmount').value},'Budget added'); $('#saveLink').onclick=()=>{const url=$('#linkUrl').value.trim(); if(data.links.some(l=>l.tripId===activeTrip()?.id&&l.url===url))return toast('That link is already saved'); add('links',{tripId:activeTrip()?.id,title:$('#linkTitle').value,url},'Travel link saved')}; $('#saveMeal').onclick=()=>add('meals',{tripId:activeTrip()?.id,date:$('#mealDate').value,type:$('#mealType').value,title:$('#mealTitle').value,person:$('#mealPerson').value},'Meal saved'); $('#saveGrocery').onclick=()=>add('groceries',{tripId:activeTrip()?.id,text:$('#groceryItem').value,privacy:$('#groceryPrivacy').value},'Grocery saved'); $('#savePacking').onclick=()=>add('packing',{tripId:activeTrip()?.id,text:$('#packingItem').value,privacy:$('#packingPrivacy').value},'Packing item saved'); $('#saveNote').onclick=()=>add('notes',{tripId:activeTrip()?.id,text:$('#tripQuickNote').value,privacy:$('#notePrivacy').value},'Note saved');
$('#scrapPhoto').onchange=async e=>(await filesToData(e.target.files)).forEach(f=>makeScrap('image',f.url)); $$('[data-add-sticker]').forEach(b=>b.onclick=()=>makeScrap('sticker',b.dataset.addSticker)); $('#addText').onclick=()=>makeScrap('text','Double tap to edit'); $('#addFrame').onclick=()=>makeScrap('frame',''); $('#scrapBg').onchange=e=>{$('#scrapCanvas').className='scrapCanvas bg-'+e.target.value}; $('#scrapLayout').onchange=e=>$('#scrapCanvas').dataset.layout=e.target.value; $('#clearPage').onclick=()=>{if(confirm('Clear scrapbook canvas?'))$('#scrapCanvas').innerHTML=''}; $('#savePage').onclick=()=>add('pages',{tripId:activeTrip()?.id,title:(activeTrip()?.name||'Trip')+' scrapbook',html:$('#scrapCanvas').innerHTML},'Scrapbook page saved'); $('#printPage').onclick=()=>window.print(); document.addEventListener('keydown',e=>{if(!selectedScrap)return; if(e.key==='Delete')selectedScrap.remove(); if(e.key==='+'||e.key==='='){selectedScrap.style.width=parseFloat(selectedScrap.style.width)+20+'px';selectedScrap.style.height=parseFloat(selectedScrap.style.height)+20+'px'} if(e.key==='-'){selectedScrap.style.width=Math.max(45,parseFloat(selectedScrap.style.width)-20)+'px';selectedScrap.style.height=Math.max(45,parseFloat(selectedScrap.style.height)-20)+'px'} if(e.key.toLowerCase()==='r')selectedScrap.style.transform='rotate('+(((parseInt(selectedScrap.dataset.rot||0)+15)%360))+'deg)'});
$('#saveMemory').onclick=async()=>{const files=await filesToData($('#memoryFiles').files); add('memories',{tripId:$('#memoryTrip').value,files,album:$('#memoryAlbum').value,title:$('#memoryTitle').value,date:$('#memoryDate').value,text:$('#memoryText').value},'Memory saved')}; $('#saveProfile').onclick=()=>add('profiles',{name:$('#profileName').value,email:$('#profileEmail').value,phone:$('#profilePhone').value,role:$('#profileRole').value},'Family member saved'); $('#saveInvite').onclick=()=>add('invites',{email:$('#inviteEmail').value,code:$('#inviteCode').value,role:$('#inviteRole').value},'Invite saved'); $('#selectAllMembers').onchange=renderMessages; $('#sendEmailLink').onclick=()=>{const to=[...$('#messageMembers').selectedOptions].map(o=>o.value).join(','); location.href=`mailto:${to}?subject=${encodeURIComponent($('#messageSubject').value)}&body=${encodeURIComponent($('#messageBody').value)}`}; $('#sendTextLink').onclick=()=>{const phones=data.profiles.filter(p=>[...$('#messageMembers').selectedOptions].map(o=>o.value).includes(p.email)).map(p=>p.phone).filter(Boolean).join(','); location.href=`sms:${phones}?&body=${encodeURIComponent($('#messageBody').value)}`}; $('#markAllNotifications').onclick=()=>{data.notifications.forEach(n=>n.read=true);save()}; $('#enablePush').onclick=async()=>{if(!('Notification'in window))return toast('Browser notifications not supported'); const p=await Notification.requestPermission(); toast('Notification permission: '+p); if(p==='granted')new Notification('Our Family Adventures',{body:'Notifications are enabled.'})}; $('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='our-family-adventures-8-backup.json';a.click()}; $('#importDataBtn').onclick=()=>$('#importData').click(); $('#importData').onchange=e=>{const r=new FileReader();r.onload=()=>{data={...blank,...JSON.parse(r.result)};save()};r.readAsText(e.target.files[0])};}
if('serviceWorker'in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=8.0.0').catch(console.warn));
document.addEventListener('DOMContentLoaded',()=>{initFirebase();bind();renderAll();});
})();
