const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d=[]){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let people=store.get('pl_people',[{name:'Melissa',photo:'',birthday:'',airport:'',email:'',phone:'',fav:'Story Keeper'},{name:'Bob',photo:'',birthday:'',airport:'',email:'',phone:'',fav:'Adventure Seeker'},{name:'Emily',photo:'',birthday:'',airport:'',email:'',phone:'',fav:'Memory Maker'}]);
let trips=store.get('pl_trips',[{title:'Nags Head 2027',location:'Nags Head, NC',start:'2027-06-12',end:'2027-06-19',cover:'',visibility:'Everyone',notes:'The first chapter captured in Our Family Adventures.',status:'Planning',invited:['Everyone'],rsvp:{Accept:0,Maybe:0,Decline:0}}]);
let proposals=store.get('pl_props',[]),stays=store.get('pl_stays',[]),pins=store.get('pl_pins',[]),memories=store.get('pl_mem',[]),journal=store.get('pl_journal',[]),chats=store.get('pl_chat',[{text:'Welcome to Our Family Adventures ❤️',time:new Date().toLocaleTimeString()}]);
let packing=store.get('pl_pack',['Sunscreen','Chargers','Beach towels']),food=store.get('pl_food',['Sam & Omie\'s','Ice cream night']);
function save(){store.set('pl_people',people);store.set('pl_trips',trips);store.set('pl_props',proposals);store.set('pl_stays',stays);store.set('pl_pins',pins);store.set('pl_mem',memories);store.set('pl_journal',journal);store.set('pl_chat',chats);store.set('pl_pack',packing);store.set('pl_food',food)}
function go(id){$$('.screen').forEach(s=>s.classList.remove('active'));const target=$('#'+id)||$('#home');target.classList.add('active');closeDrawer();window.scrollTo(0,0);renderAll()}
function wireNav(){document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b){go(b.dataset.go)}});$$('.menu-open').forEach(b=>b.addEventListener('click',()=>{$('#drawer').classList.add('open');$('#scrim').classList.add('show')}));$('#closeDrawer')?.addEventListener('click',closeDrawer);$('#scrim')?.addEventListener('click',closeDrawer);$('.heart-btn')?.addEventListener('click',()=>go('favorites'));$$('.tab').forEach(t=>t.addEventListener('click',()=>{const name=t.dataset.tab;$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$$('.tab-pane').forEach(p=>p.classList.remove('active'));$('#tab-'+name)?.classList.add('active')}))}
function closeDrawer(){$('#drawer')?.classList.remove('open');$('#scrim')?.classList.remove('show')}
function countdown(){const d=new Date('2027-06-12T00:00:00');const now=new Date();const days=Math.max(0,Math.ceil((d-now)/86400000));$('#countDays')&&( $('#countDays').textContent=days)}
function renderInvites(){const el=$('#inviteChecks');if(!el)return;el.innerHTML=`<label class="chip"><input type="checkbox" value="Everyone" checked>Everyone</label>`+people.map(p=>`<label class="chip"><input type="checkbox" value="${escapeHtml(p.name)}">${escapeHtml(p.name)}</label>`).join('')}
function selectedInvites(){return $$('#inviteChecks input:checked').map(x=>x.value)}
$('#addPerson')?.addEventListener('click',()=>{const name=$('#personName').value.trim();if(!name)return;people.push({name,photo:$('#personPhoto').value.trim(),birthday:$('#personBirthday').value,airport:$('#personAirport').value.trim(),email:$('#personEmail').value.trim(),phone:$('#personPhone').value.trim(),fav:$('#personFav').value.trim()});['personName','personPhoto','personBirthday','personAirport','personEmail','personPhone','personFav'].forEach(id=>$('#'+id).value='');save();renderPeople();renderInvites()});
function renderPeople(){const el=$('#peopleList');if(!el)return;el.innerHTML=people.map((p,i)=>`<div class="person"><div class="person-main">${p.photo?`<img class="avatar" src="${escapeAttr(p.photo)}">`:`<div class="avatar">${escapeHtml((p.name[0]||'?').toUpperCase())}</div>`}<div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.fav||'Family member')}</small><small>${p.birthday?'🎂 '+escapeHtml(p.birthday):''} ${p.airport?' • ✈️ '+escapeHtml(p.airport):''}</small></div></div><button class="mini-btn danger" onclick="removePerson(${i})">Remove</button></div>`).join('')}
window.removePerson=i=>{people.splice(i,1);save();renderPeople();renderInvites()};
$('#addTrip')?.addEventListener('click',()=>{const title=$('#tripTitle').value.trim();if(!title)return;trips.push({title,location:$('#tripLocation').value.trim(),start:$('#tripStart').value,end:$('#tripEnd').value,cover:$('#tripCover').value.trim(),visibility:$('#tripVisibility').value,notes:$('#tripNotes').value,status:'Planning',invited:selectedInvites(),rsvp:{Accept:0,Maybe:0,Decline:0}});['tripTitle','tripLocation','tripStart','tripEnd','tripCover','tripNotes'].forEach(id=>$('#'+id).value='');save();renderTrips();renderTimeline()});
function renderTrips(){const el=$('#tripList');if(!el)return;el.innerHTML=trips.map((t,i)=>`<div class="item"><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.location||'Location TBD')} ${t.start?`• ${escapeHtml(t.start)} to ${escapeHtml(t.end||'TBD')}`:''}</p><p>Status: <b>${escapeHtml(t.status)}</b> • ${escapeHtml(t.visibility||'Everyone')}</p><p><b>Invited:</b> ${escapeHtml((t.invited||[]).join(', ')||'Everyone')}</p><div class="item-actions"><button class="mini-btn" onclick="rsvp(${i},'Accept')">Accept (${t.rsvp.Accept})</button><button class="mini-btn" onclick="rsvp(${i},'Maybe')">Maybe (${t.rsvp.Maybe})</button><button class="mini-btn" onclick="rsvp(${i},'Decline')">Decline (${t.rsvp.Decline})</button><button class="mini-btn" onclick="completeTrip(${i})">Complete</button><button class="mini-btn danger" onclick="cancelTrip(${i})">Cancel Trip</button></div></div>`).join('')}
window.rsvp=(i,k)=>{trips[i].rsvp[k]++;save();renderTrips()};window.cancelTrip=i=>{trips[i].status='Canceled';save();renderTrips();renderTimeline()};window.completeTrip=i=>{trips[i].status='Completed';save();renderTrips();renderTimeline()};
$('#addProposal')?.addEventListener('click',()=>{const date=$('#proposalDate').value.trim(),place=$('#proposalPlace').value.trim();if(!date&&!place)return;proposals.push({date,place,votes:0});$('#proposalDate').value='';$('#proposalPlace').value='';save();renderProps()});
function renderProps(){const el=$('#proposalList');if(!el)return;el.innerHTML=proposals.map((p,i)=>`<div class="item"><b>${escapeHtml(p.date||'New date idea')}</b><p>${escapeHtml(p.place||'Location unchanged')}</p><button class="mini-btn" onclick="voteProp(${i})">Vote ❤️ ${p.votes}</button><button class="mini-btn danger" onclick="delProp(${i})">Delete</button></div>`).join('')}
window.voteProp=i=>{proposals[i].votes++;save();renderProps()};window.delProp=i=>{proposals.splice(i,1);save();renderProps()};
$('#addStay')?.addEventListener('click',()=>{const title=$('#stayTitle').value.trim(),url=$('#stayUrl').value.trim();if(!title&&!url)return;stays.push({title:title||url,url,votes:0,pass:0});$('#stayTitle').value='';$('#stayUrl').value='';save();renderStays()});
function renderStays(){const el=$('#stayList');if(!el)return;el.innerHTML=stays.map((s,i)=>`<div class="item"><b>${escapeHtml(s.title)}</b><p>${s.url?`<a href="${escapeAttr(s.url)}" target="_blank" rel="noopener">Open link</a>`:'No link'}</p><div class="item-actions"><button class="mini-btn" onclick="voteStay(${i})">Love it ❤️ ${s.votes}</button><button class="mini-btn" onclick="passStay(${i})">Pass 👎 ${s.pass||0}</button><button class="mini-btn danger" onclick="delStay(${i})">Delete</button></div></div>`).join('')}
window.voteStay=i=>{stays[i].votes++;save();renderStays()};window.passStay=i=>{stays[i].pass=(stays[i].pass||0)+1;save();renderStays()};window.delStay=i=>{stays.splice(i,1);save();renderStays()};
$('#saveTravel')?.addEventListener('click',()=>{$('#travelNotes').innerHTML=`<p><b>Flight:</b> ${escapeHtml($('#flightInfo').value||'Not added yet')}</p><p><b>Transportation:</b> ${escapeHtml($('#carInfo').value||'Not added yet')}</p>`});
$('#addPack')?.addEventListener('click',()=>{const v=$('#packItem').value.trim();if(!v)return;packing.push(v);$('#packItem').value='';save();renderPacking()});
function renderPacking(){const el=$('#packList');if(!el)return;el.innerHTML=packing.map((p,i)=>`<div class="item"><label class="check"><input type="checkbox"> ${escapeHtml(p)}</label><button class="mini-btn danger" onclick="delPack(${i})">Remove</button></div>`).join('')}
window.delPack=i=>{packing.splice(i,1);save();renderPacking()};
$('#addFood')?.addEventListener('click',()=>{const v=$('#foodIdea').value.trim();if(!v)return;food.push({text:v,votes:0});$('#foodIdea').value='';save();renderFood()});
function renderFood(){const el=$('#foodList');if(!el)return;el.innerHTML=food.map((f,i)=>{const obj=typeof f==='string'?{text:f,votes:0}:f;return `<div class="item"><b>${escapeHtml(obj.text)}</b><button class="mini-btn" onclick="voteFood(${i})">Vote ❤️ ${obj.votes||0}</button><button class="mini-btn danger" onclick="delFood(${i})">Remove</button></div>`}).join('')}
window.voteFood=i=>{if(typeof food[i]==='string')food[i]={text:food[i],votes:0};food[i].votes=(food[i].votes||0)+1;save();renderFood()};window.delFood=i=>{food.splice(i,1);save();renderFood()};
$('#addPin')?.addEventListener('click',()=>{const title=$('#pinTitle').value.trim(),addr=$('#pinAddress').value.trim(),type=$('#pinType').value;if(!title&&!addr)return;pins.push({title:title||addr,address:addr,type});$('#pinTitle').value='';$('#pinAddress').value='';save();renderPins()});
function renderPins(){const el=$('#pinList');if(!el)return;el.innerHTML=pins.map((p,i)=>`<div class="item"><b>${escapeHtml(p.type||'📍')} ${escapeHtml(p.title)}</b><p>${escapeHtml(p.address)}</p><div class="item-actions"><button class="mini-btn" onclick="window.open('https://www.google.com/maps/search/${encodeURIComponent(p.address||p.title)}','_blank')">Open Map</button><button class="mini-btn" onclick="editPin(${i})">Edit / Move</button><button class="mini-btn danger" onclick="delPin(${i})">Remove</button></div></div>`).join('')}
window.editPin=i=>{const n=prompt('New address or place',pins[i].address);if(n!==null){pins[i].address=n;save();renderPins()}};window.delPin=i=>{pins.splice(i,1);save();renderPins()};
$('#addMemory')?.addEventListener('click',()=>{const title=$('#memoryTitle').value.trim()||'Family memory';const tags=$('#memoryTags').value.split(',').map(x=>x.trim()).filter(Boolean);memories.push({title,tags,favs:0,type:$('#memoryFile').files?.[0]?.type||'memory'});$('#memoryTitle').value='';$('#memoryTags').value='';$('#memoryFile').value='';save();renderMem()});
function renderMem(){const el=$('#memoryList');if(!el)return;el.innerHTML=memories.map((m,i)=>`<div class="memory"><h3>${escapeHtml(m.title)}</h3><p>${(m.type||'').includes('video')?'🎥 Video':'📸 Photo'} preview saved for this device.</p><p>${m.tags.map((t,ti)=>`<span class="mini-btn">${escapeHtml(t)} <button onclick="remTag(${i},${ti})">×</button></span>`).join(' ')}</p><button class="mini-btn" onclick="favMem(${i})">Favorite ❤️ ${m.favs}</button><button class="mini-btn danger" onclick="delMem(${i})">Delete</button></div>`).join('')}
window.remTag=(i,ti)=>{memories[i].tags.splice(ti,1);save();renderMem()};window.favMem=i=>{memories[i].favs++;save();renderMem()};window.delMem=i=>{memories.splice(i,1);save();renderMem()};
$('#saveJournal')?.addEventListener('click',()=>{const text=$('#journalText').value.trim();if(!text)return;journal.unshift({text,date:new Date().toLocaleDateString(),time:new Date().toLocaleTimeString()});$('#journalText').value='';save();renderJournal()});
function renderJournal(){const el=$('#journalList');if(!el)return;el.innerHTML=journal.length?journal.map((j,i)=>`<div class="item journal-entry"><b>${escapeHtml(j.date)} • ${escapeHtml(j.time)}</b><p>${escapeHtml(j.text)}</p><button class="mini-btn danger" onclick="delJournal(${i})">Delete</button></div>`).join(''):'<p class="small">No journal entries yet. Add the first memory from today.</p>'}
window.delJournal=i=>{journal.splice(i,1);save();renderJournal()};
$('#sendChat')?.addEventListener('click',()=>{const text=$('#chatInput').value.trim();if(!text)return;chats.push({text,time:new Date().toLocaleTimeString()});$('#chatInput').value='';save();renderChat()});
function renderChat(){const el=$('#chatList');if(!el)return;el.innerHTML=chats.map(c=>`<div class="chat"><b>${escapeHtml(c.time)}</b><br>${escapeHtml(c.text).replace(/@(\w+)/g,'<b>@$1</b>')}</div>`).join('')}
function renderTimeline(){const el=$('#timelineList');if(!el)return;el.innerHTML=trips.map(t=>`<div class="item"><b>${escapeHtml((t.start||'Future').slice(0,4))}</b><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.location||'Location TBD')} • ${escapeHtml(t.status)}</p></div>`).join('')}
function renderAll(){countdown();renderInvites();renderPeople();renderTrips();renderProps();renderStays();renderPins();renderMem();renderJournal();renderChat();renderPacking();renderFood();renderTimeline()}
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function escapeAttr(s=''){return escapeHtml(s).replace(/'/g,'&#39;')}
wireNav();renderAll();if('serviceWorker'in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
