/* FINAL 6.4.1 cleanup/production patch */
(function(){
  const $=id=>document.getElementById(id);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const saveNow=()=>{try{ if(typeof save==='function') save(); else localStorage.setItem('ofaDataV5',JSON.stringify(data)); }catch(e){localStorage.setItem('ofaDataV5',JSON.stringify(data));}};
  const me=()=>{let n=(localStorage.getItem('ofa_family_user')||localStorage.getItem('ofa_voter_name')||'').trim(); if(!n){n='Melissa';localStorage.setItem('ofa_family_user',n);localStorage.setItem('ofa_voter_name',n);} return n;};
  function peopleOptions(def='Volunteer needed'){const names=(data.people||[]).map(p=>p.name).filter(Boolean); return [def,'Everyone / Group',...names].filter((v,i,a)=>a.indexOf(v)===i).map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');}
  function dedupeFormLabels(){
    // Remove old radio/chip controls and duplicate label blocks added by previous patch builds.
    $$('label').forEach(l=>{const t=(l.textContent||'').trim(); if(/^(Group list|Individual\/private)$/.test(t)) l.remove();});
    $$('.card.formCard').forEach(card=>{
      const keep={};
      $$('label',card).forEach(l=>{const name=(l.childNodes[0]?.textContent||l.textContent||'').trim().replace(/\s+/g,' '); if(['Meal type','List privacy','Assigned to','Who is bringing it?'].includes(name)){ if(keep[name]) l.remove(); else keep[name]=l; }});
    });
    ['mealPerson','groceryPerson','packingPerson','mealTitle'].forEach(x=>{const el=$(x); if(el){el.required=false; if(x==='mealTitle'){el.closest('label')?.classList.add('hidden');}}});
  }
  function setupCleanForms(){
    dedupeFormLabels();
    if($('mealItem')&&!$('mealType641')) $('mealItem').closest('label')?.insertAdjacentHTML('beforebegin','<label>Meal type<select id="mealType641"><option>Breakfast</option><option>Snack</option><option>Dining out</option><option>Lunch</option><option selected>Dinner</option><option>Late snack</option><option>Happy hour</option></select></label>');
    if($('mealItem')&&!$('mealPrivacy641')) $('mealItem').closest('label')?.insertAdjacentHTML('beforebegin','<label>List privacy<select id="mealPrivacy641"><option value="group">Group/shared meal</option><option value="private">My private meal</option></select></label>');
    if($('mealItem')&&!$('mealAssign641')) $('mealItem').closest('label')?.insertAdjacentHTML('afterend',`<label>Assigned to<select id="mealAssign641">${peopleOptions()}</select></label>`);
    if($('groceryItem')&&!$('groceryPrivacy641')) $('groceryItem').closest('label')?.insertAdjacentHTML('beforebegin','<label>List privacy<select id="groceryPrivacy641"><option value="group">Group list</option><option value="private">My private list</option></select></label>');
    if($('groceryItem')&&!$('groceryAssign641')) $('groceryItem').closest('label')?.insertAdjacentHTML('afterend',`<label>Assigned to<select id="groceryAssign641">${peopleOptions()}</select></label>`);
    if($('packingItem')&&!$('packingPrivacy641')) $('packingItem').closest('label')?.insertAdjacentHTML('beforebegin','<label>List privacy<select id="packingPrivacy641"><option value="group">Group list</option><option value="private">My private list</option></select></label>');
    if($('packingItem')&&!$('packingAssign641')) $('packingItem').closest('label')?.insertAdjacentHTML('afterend',`<label>Assigned to<select id="packingAssign641">${peopleOptions('Everyone / Group')}</select></label>`);
    dedupeFormLabels();
  }
  function addList(kind){
    const trip=$(kind==='meal'?'mealTrip':kind==='grocery'?'groceryTrip':'packingTrip')?.value || 'General';
    const item=$(kind==='meal'?'mealItem':kind==='grocery'?'groceryItem':'packingItem')?.value?.trim();
    if(!item) return alert('Add an item first.');
    const priv=$(kind==='meal'?'mealPrivacy641':kind==='grocery'?'groceryPrivacy641':'packingPrivacy641')?.value==='private';
    const assign=priv?me():($(kind==='meal'?'mealAssign641':kind==='grocery'?'groceryAssign641':'packingAssign641')?.value || 'Volunteer needed');
    const obj={id:id(),trip,item,person:assign,assignedTo:assign,private:priv,scope:priv?'private':'group',owner:priv?me():'group',addedBy:me(),done:false,createdAt:new Date().toISOString()};
    if(kind==='meal'){obj.title=$('mealType641')?.value||'Dinner';obj.mealType=obj.title;data.meals=data.meals||[];data.meals.push(obj);$('mealItem').value='';}
    if(kind==='grocery'){data.groceries=data.groceries||[];data.groceries.push(obj);$('groceryItem').value='';}
    if(kind==='packing'){data.packing=data.packing||[];data.packing.push(obj);$('packingItem').value='';}
    addNotice(`${kind} item added: ${item}`,kind); saveNow(); render();
  }
  window.toggleDone=function(kind,itemId){const x=(data[kind]||[]).find(a=>a.id===itemId); if(x){x.done=!x.done; saveNow(); render();}};
  window.assignItem=function(kind,itemId,val){const x=(data[kind]||[]).find(a=>a.id===itemId); if(x){x.person=val;x.assignedTo=val; saveNow(); render();}};
  window.editListItem=function(kind,itemId){const x=(data[kind]||[]).find(a=>a.id===itemId); if(!x)return; const v=prompt('Edit item',x.item||''); if(v!==null){x.item=v.trim()||x.item; saveNow(); render();}};
  function visible(x){return !x.private || x.owner===me() || x.addedBy===me();}
  function row(kind,x,title,sub){return `<div class="item checklistItem ${x.done?'doneSoft':''}"><label class="checkLine"><input type="checkbox" ${x.done?'checked':''} onchange="toggleDone('${kind}','${x.id}')"><span><b>${esc(title)}</b><small>${esc(sub||'')}</small></span></label><p class="helperText">${x.private?'Private — only you can see this':'Group/shared'}${x.person?' • Assigned: '+esc(x.person):''}</p>${!x.private?`<label class="inlineAssign">Assign/claim<select onchange="assignItem('${kind}','${x.id}',this.value)">${peopleOptions(x.person||'Volunteer needed')}</select></label>`:''}<div class="itemActions"><button onclick="editListItem('${kind}','${x.id}')" class="secondary smallBtn">Edit</button><button onclick="del('${kind}','${x.id}')" class="secondary smallBtn">Delete</button></div></div>`;}
  window.renderMeals=function(){const box=$('mealList'); if(!box)return; const meals=(data.meals||[]).filter(visible), groceries=(data.groceries||[]).filter(visible); box.innerHTML=`<div class="card"><h3>Group Meal Plan</h3>${meals.filter(x=>!x.private).map(m=>row('meals',m,`${m.mealType||m.title||'Meal'}: ${m.item}`,m.trip)).join('')||'<p>No group meals yet.</p>'}</div><div class="card"><h3>My Private Meal Plan</h3>${meals.filter(x=>x.private).map(m=>row('meals',m,`${m.mealType||m.title||'Meal'}: ${m.item}`,m.trip)).join('')||'<p>No private meals yet.</p>'}</div><div class="card"><h3>Group Grocery List</h3>${groceries.filter(x=>!x.private).map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No group grocery items yet.</p>'}</div><div class="card"><h3>My Private Grocery List</h3>${groceries.filter(x=>x.private).map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No private grocery items yet.</p>'}</div>`;};
  window.renderPacking=function(){const box=$('packingList'); if(!box)return; const items=(data.packing||[]).filter(visible); box.innerHTML=`<div class="card"><h3>Group Packing List</h3>${items.filter(x=>!x.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No group packing items yet.</p>'}</div><div class="card"><h3>My Private Packing List</h3>${items.filter(x=>x.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No private packing items yet.</p>'}</div>`;};

  function splitLines(t){return String(t||'').split(/\n+/).map(s=>s.trim()).filter(Boolean)}
  function hostTitle(u){try{return new URL(u).hostname.replace(/^www\./,'');}catch{return u;}}
  window.addVoteOptionsBulk=function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; const opts=splitLines($('voteInput-'+tripId)?.value); const links=splitLines($('voteLink-'+tripId)?.value); if(!opts.length&&!links.length)return alert('Add at least one voting option or link.'); t.voteOptions=t.voteOptions||[]; opts.forEach(o=>t.voteOptions.push({id:id(),text:o,link:/^https?:\/\//i.test(o)?o:'',votes:{}})); links.forEach(l=>t.voteOptions.push({id:id(),text:hostTitle(l),link:l,votes:{}})); $$(`#voteInput-${tripId},#voteLink-${tripId}`).forEach(e=>e.value=''); addNotice('Voting option added','votes'); saveNow(); render(); show('voting');};
  window.voteTrip=function(tripId,index){const t=(data.trips||[]).find(x=>x.id===tripId); const v=t?.voteOptions?.[index]; if(!v)return; const voter=me(); t.voteOptions.forEach(o=>{o.votes=o.votes||{}; delete o.votes[voter];}); v.votes=v.votes||{}; v.votes[voter]=new Date().toISOString(); addNotice(`${voter} voted on ${t.name}`,'votes'); saveNow(); render();};
  window.voteCount=v=>Object.keys(v.votes||{}).length+Number(v.legacyCount||0);
  function voteCard(t){return `<div class="card"><h3>${esc(t.name)}</h3>${(t.voteOptions||[]).map((v,i)=>`<div class="voteRow"><div><b>${esc(v.text)}</b>${v.link?`<br><a target="_blank" href="${esc(v.link)}">${esc(v.link)}</a>`:''}<br><small>${Object.keys(v.votes||{}).join(', ')||'No votes yet'}</small></div><strong>${voteCount(v)} vote(s)</strong><button onclick="voteTrip('${t.id}',${i})" class="secondary">Vote / Change</button></div>`).join('')||'<p>No voting options yet.</p>'}<div class="voteAdd"><textarea id="voteInput-${t.id}" placeholder="Add voting options, one per line"></textarea><textarea id="voteLink-${t.id}" placeholder="Optional links, one per line. Each link becomes its own vote option."></textarea><button onclick="addVoteOptionsBulk('${t.id}')" class="secondary">Add voting item(s)</button></div></div>`;}
  function renderVoting(){const box=$('votingList'); if(box) box.innerHTML=(data.trips||[]).map(voteCard).join('')||'<div class="card"><p>Add a trip first.</p></div>';}

  function addNotice(text,type='system'){data.notifications=data.notifications||[]; data.notifications.unshift({id:id(),text,type,read:false,at:new Date().toISOString()}); updateBadges();}
  window.addAppNotification=addNotice;
  function ensureNotif(){
    $$('.notificationBell,.chatPopButton,.floatingNotif').forEach((e,i)=>{ if(i>0) e.remove(); });
    if(!$('notifyBell641')) document.body.insertAdjacentHTML('beforeend','<button id="notifyBell641" class="floatingNotif">🔔 <span id="notifBadge641">0</span></button><div id="notifPanel641" class="notificationCenter hidden"><div class="card"><button id="closeNotif641" class="closeNotif">×</button><h3>Notifications</h3><div id="notifList641"></div><button id="markRead641" class="secondary">Mark all read</button><button id="clearNotif641" class="secondary">Clear all</button></div></div>');
    $('notifyBell641').onclick=()=>{$('notifPanel641').classList.remove('hidden'); renderNotifList();}; $('closeNotif641').onclick=()=>$('notifPanel641').classList.add('hidden'); $('markRead641').onclick=()=>{(data.notifications||[]).forEach(n=>n.read=true); saveNow(); renderNotifList(); updateBadges();}; $('clearNotif641').onclick=()=>{data.notifications=[]; saveNow(); renderNotifList(); updateBadges();};
  }
  function renderNotifList(){const box=$('notifList641'); if(!box)return; const list=data.notifications||[]; box.innerHTML=list.length?list.map(n=>`<div class="notificationNote ${n.read?'read':'unread'}"><b>${esc(n.type)}</b><p>${esc(n.text)}</p><small>${new Date(n.at).toLocaleString()}</small></div>`).join(''):'<p>No notifications.</p>';}
  function updateBadges(){const unread=(data.notifications||[]).filter(n=>!n.read).length; if($('notifBadge641')) $('notifBadge641').textContent=unread; if('setAppBadge' in navigator){ if(unread) navigator.setAppBadge(unread).catch(()=>{}); else navigator.clearAppBadge?.().catch(()=>{});} }

  function ensureChat(){
    $$('.chatFloat,.floatingChat,.chatPopButton').forEach((e,i)=>{ if(i>0) e.remove(); });
    if(!$('chatFloat641')) document.body.insertAdjacentHTML('beforeend','<button id="chatFloat641" class="chatFloat">💬 <span id="chatBadge641">0</span></button><div id="chatPanel641" class="chatFloatPanel hidden"><div class="chatFloatHeader"><b>Family Chat</b><button id="closeChat641">×</button></div><div id="chatLog641" class="chatFloatLog"></div><div class="chatFloatSend"><input id="chatInput641" placeholder="Write a message or @name"><button id="sendChat641" class="primary">Send</button></div></div>');
    const b=$('chatFloat641'); let drag=false, moved=false, dx=0,dy=0; b.onpointerdown=e=>{drag=true;moved=false;dx=e.clientX-b.offsetLeft;dy=e.clientY-b.offsetTop;b.setPointerCapture(e.pointerId)}; b.onpointermove=e=>{if(drag){moved=true;b.style.left=(e.clientX-dx)+'px';b.style.top=(e.clientY-dy)+'px';b.style.right='auto';b.style.bottom='auto';}}; b.onpointerup=e=>{drag=false;try{b.releasePointerCapture(e.pointerId)}catch{}; if(!moved){$('chatPanel641').classList.toggle('hidden'); renderChat();}};
    $('closeChat641').onclick=()=>$('chatPanel641').classList.add('hidden'); $('sendChat641').onclick=()=>{const msg=$('chatInput641').value.trim(); if(!msg)return; $('chatInput641').value=''; data.chat=data.chat||[]; data.chat.push({id:id(),name:me(),text:msg,at:new Date().toISOString()}); addNotice(msg.includes('@')?'You were mentioned in chat':'New family chat','chat'); saveNow(); renderChat();};
  }
  window.renderChat=function(){const html=(data.chat||[]).slice(-80).map(c=>`<div class="bubble"><b>${esc(c.name||c.author||'Family')}</b><br>${esc(c.text).replace(/@\w+/g,m=>`<b>${m}</b>`)}<br><small>${new Date(c.at).toLocaleString()}</small></div>`).join('')||'<p>No chat messages yet.</p>'; if($('chatLog')) $('chatLog').innerHTML=html; if($('chatLog641')) {$('chatLog641').innerHTML=html; $('chatLog641').scrollTop=$('chatLog641').scrollHeight;} const unread=(data.notifications||[]).filter(n=>!n.read&&n.type==='chat').length; if($('chatBadge641')) $('chatBadge641').textContent=unread;};

  window.addItinerary=function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; const time=$(`itineraryCustom-${tripId}`)?.value || ($$(`input[name="itSlot-${tripId}"]`).find(r=>r.checked)?.value||'Activity'); const title=$(`itineraryTitle-${tripId}`)?.value?.trim(); const link=$(`itineraryLink-${tripId}`)?.value?.trim()||''; if(!title)return alert('Add the itinerary activity first.'); t.itinerary=t.itinerary||[]; t.itinerary.push({id:id(),time,title,link}); saveNow(); render();};
  async function liveWeather(place){ if(!place)return 'Add a city, state, destination, or address.'; try{let q=String(place).split(',').slice(0,2).join(','); const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=en&format=json`).then(r=>r.json()); const g=geo.results?.[0]; if(!g)return 'Weather could not find that location. Try city and state.'; const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${g.latitude}&longitude=${g.longitude}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&timezone=auto`).then(r=>r.json()); return `${g.name}: ${Math.round(w.current.temperature_2m)}°F now. High ${Math.round(w.daily.temperature_2m_max[0])}° / Low ${Math.round(w.daily.temperature_2m_min[0])}°. Rain chance ${w.daily.precipitation_probability_max?.[0]??0}%.`; }catch(e){return 'Live weather could not load. Check internet or use city/state.';}}
  window.refreshTripWeather=async function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId)||data.trips?.[0]; if(!t)return; t.weather='Loading live weather...'; saveNow(); render(); t.weather=await liveWeather(t.address||t.destination||t.tripAddress||t.name); addNotice('Weather updated','weather'); saveNow(); render();};
  window.openTripMap=function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId); const q=encodeURIComponent(t?.address||t?.destination||t?.name||''); if(q) window.open(`https://www.google.com/maps/search/?api=1&query=${q}`,'_blank');};

  function setupProfileEdit(){
    if(!$('profilePhoto641')) document.body.insertAdjacentHTML('beforeend','<input id="profilePhoto641" type="file" accept="image/*" class="hidden">');
    $('profilePhoto641').onchange=e=>{const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{localStorage.setItem('ofa_profile_photo',r.result); let p=(data.people||[]).find(x=>x.name===me()); if(p)p.photo=r.result; saveNow(); render();}; r.readAsDataURL(f);};
    if($('profileEditBtn')) $('profileEditBtn').onclick=()=>{const n=prompt('Display name',me()); if(n){localStorage.setItem('ofa_family_user',n.trim()); localStorage.setItem('ofa_voter_name',n.trim());} const em=prompt('Email',localStorage.getItem('ofa_profile_email')||''); if(em!==null)localStorage.setItem('ofa_profile_email',em); const ph=prompt('Phone',localStorage.getItem('ofa_profile_phone')||''); if(ph!==null)localStorage.setItem('ofa_profile_phone',ph); if(confirm('Change profile photo?')) $('profilePhoto641').click(); render();};
  }
  function renderProfile(){const box=$('profileSummary'); if(!box)return; const pic=localStorage.getItem('ofa_profile_photo')||(data.people||[]).find(p=>p.name===me())?.photo||'icons/icon-192.png'; box.innerHTML=`<div class="profileSummary"><img class="profileAvatarBig" src="${pic}"><div><h3>${esc(me())}</h3><p>${esc(localStorage.getItem('ofa_profile_email')||'Not signed in yet')}</p><p>${esc(localStorage.getItem('ofa_profile_phone')||'')}</p><button class="secondary" onclick="document.getElementById('profileEditBtn')?.click()">Edit Profile</button></div></div>`;}

  function ensureHomeButtons(){ $$('.page').forEach(p=>{const head=p.querySelector('.pageHead'); if(head && p.id!=='home' && !head.querySelector('.pageHomeBtn')) head.insertAdjacentHTML('afterbegin','<button class="secondary pageHomeBtn" data-go="home">🏠 Home</button>');}); $$('.miniCard').forEach((c,i)=>{c.setAttribute('data-go',['people','adventures','memories','scrapbook'][i]||'home')});}
  function rebindNav(){ $$('[data-go]').forEach(btn=>{btn.onclick=e=>{e.preventDefault(); const page=btn.getAttribute('data-go'); show(page); setTimeout(()=>{document.querySelector('.page.active')?.scrollIntoView({block:'start'}); window.scrollTo(0,0);},20);};}); $$('.dock button').forEach(b=>b.classList.toggle('active',b.getAttribute('data-go')===document.querySelector('.page.active')?.id));}

  function themeStickers(theme){const t=String(theme||'').toLowerCase(); if(t.includes('atv'))return ['🏁','🛞','🛻','🌲','⛰️','💨','🥾','🧤','🧢']; if(t.includes('fish'))return ['🎣','🐟','🚤','🌊','🪱','🧢','☀️']; if(t.includes('camp'))return ['⛺','🔥','🌲','🧭','🥾','⭐','🪵']; if(t.includes('birthday'))return ['🎂','🎈','🎁','🥳','✨','🎉']; if(t.includes('happy')||t.includes('drink'))return ['🍹','🍻','🥂','🍷','🧊','🌅']; if(t.includes('party'))return ['🎉','🎈','🥳','🍰','✨','🎊']; if(t.includes('mount'))return ['⛰️','🌲','🥾','🔥','🧭','🏕️']; return ['🐚','⭐','🌊','🏖️','☀️','📷','🩴','🕶️'];}
  function renderScrapbook(){const box=$('scrapbookPages'); if(!box)return; box.innerHTML=(data.pages||[]).map(p=>`<div class="scrapPage theme-${esc(String(p.theme||'beach').toLowerCase().replace(/[^a-z0-9]+/g,'-'))}"><h3>${esc(p.title)}</h3><div class="stickerStrip">${themeStickers(p.theme).map(s=>`<span>${s}</span>`).join('')}</div><div class="cutoutStrip"><span>polaroid</span><span>ticket cutout</span><span>circle cutout</span><span>postcard</span><span>torn paper</span></div><div class="trueCollage">${(p.photos||[]).map((src,i)=>`<figure class="size-${i%8} frame-${['polaroid','ticket-stub','circle-cutout','postcard','torn-paper','gold','shell'][i%7]}"><img draggable="true" src="${src}" ondragstart="event.dataTransfer.setData('text/plain','${p.id}:${i}')" ondrop="dropScrapPhoto(event,'${p.id}',${i})" ondragover="event.preventDefault()"><button onclick="alert('Use drag-and-drop to rearrange. Full pinch crop editor is planned for 7.0.')">Crop</button></figure>`).join('')||'<p>No photos selected for this page.</p>'}</div><p>${esc(p.note||'')}</p><div class="scrapTools noPrint"><button onclick="window.print()" class="secondary">PDF / Print</button><button onclick="del('pages','${p.id}')" class="secondary">Delete</button></div></div>`).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>';}
  window.dropScrapPhoto=function(e,pid,to){e.preventDefault();const [idp,from]=String(e.dataTransfer.getData('text/plain')).split(':'); if(idp!==pid)return; const p=(data.pages||[]).find(x=>x.id===pid); if(!p)return; const f=Number(from); [p.photos[f],p.photos[to]]=[p.photos[to],p.photos[f]]; saveNow(); render();};

  const oldShow=window.show; window.show=function(page){ if(oldShow) oldShow(page); $$('.page').forEach(p=>p.classList.toggle('active',p.id===page)); document.body.classList.toggle('homeMode',page==='home'); document.body.classList.toggle('sectionMode',page!=='home'); $$('.dock button').forEach(b=>b.classList.toggle('active',b.getAttribute('data-go')===page)); window.scrollTo(0,0); };
  const oldRender=window.render; window.render=function(){try{oldRender&&oldRender();}catch(e){console.warn(e)} setupCleanForms(); ensureNotif(); ensureChat(); setupProfileEdit(); ensureHomeButtons(); rebindNav(); renderVoting(); renderProfile(); renderScrapbook(); renderNotifList(); updateBadges(); if($('saveMeal')) $('saveMeal').onclick=()=>addList('meal'); if($('saveGrocery')) $('saveGrocery').onclick=()=>addList('grocery'); if($('savePacking')) $('savePacking').onclick=()=>addList('packing');};
  setTimeout(()=>{me(); render();},500);
})();
