(()=>{'use strict';
const DK='ofa-9-data',JK='ofa-media-journal-v1',HIDDEN='scrapbook';let busy=false;
const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v||{}));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function redirect(){const p=(location.hash||'#').slice(1).split('/');if(p[0]===HIDDEN)location.replace('#media'+(p[1]?'/'+encodeURIComponent(p[1]):''))}
function hideScrapbook(){document.querySelectorAll('#dock button,#drawer button,.homeTiles .tile,.tripModule,.adminLockList label,.featureChecklist label,.backupStat').forEach(el=>{const s=((el.textContent||'')+' '+(el.getAttribute('onclick')||'')).toLowerCase();if(s.includes('scrapbook')){el.hidden=true;el.style.display='none';el.setAttribute('aria-hidden','true')}});document.querySelectorAll('#view p').forEach(p=>{if(p.textContent?.includes('media, memories, or scrapbook pages.'))p.textContent=p.textContent.replace('media, memories, or scrapbook pages.','media and memories.')})}
function wrapRoute(){if(!window.app||app.__hideScrapbook)return;const go=app.go;app.go=(r,...a)=>go(r===HIDDEN?'media':r,...a);app.__hideScrapbook=true}
const data=()=>read(DK,{}),journal=()=>read(JK,{}),photos=d=>(Array.isArray(d.media)?d.media:[]).filter(x=>x?.id&&x?.url&&String(x.type||'image').startsWith('image'));
const trip=(d,id)=>(Array.isArray(d.trips)?d.trips:[]).find(x=>String(x.id)===String(id));
function path(d,p){const base=`families/${String(d.settings?.template?.familyId||'default-family').toLowerCase().replace(/[^a-z0-9_-]+/g,'-')||'default-family'}`;if(!p.tripId)return `${base}/publicData/shared/media/${p.id}`;return `${base}/${trip(d,p.tripId)?.visibility==='private'?'privateTrips':'familyTrips'}/${p.tripId}/collections/media/${p.id}`}
function cache(id,v){const d=data(),p=photos(d).find(x=>String(x.id)===String(id));if(!p)return;Object.entries(v).forEach(([k,x])=>x==null?delete p[k]:p[k]=x);try{write(DK,d)}catch(e){console.warn(e)}}
async function remote(d,p,v){if(!window.firebase?.database||!firebase.auth?.().currentUser)throw Error('Firebase sync is not ready');await firebase.database().ref(path(d,p)).update(v)}
function merge(d,ps){const j=journal();let changed=false;ps.forEach(p=>{if(!p.journalCaption)return;const r={caption:p.journalCaption,emoji:p.journalEmoji||'📖',updatedAt:+p.journalUpdatedAt||0,by:p.journalByName||'Family member',pending:false};if(!j[p.id]||(!j[p.id].pending&&r.updatedAt>=+j[p.id].updatedAt)){j[p.id]=r;changed=true}});if(changed)write(JK,j);return j}
function note(sec,text,state=''){const e=sec.querySelector('#mediaJournalMessage');if(e){e.textContent=text;e.dataset.state=state}}
function jpgName(name='family-photo'){const base=String(name).replace(/\.[^.]+$/,'').replace(/[\\/:*?"<>|]+/g,'-').trim()||'family-photo';return `${base}.jpg`}
async function imageFromBlob(blob){if('createImageBitmap'in window)return createImageBitmap(blob);return new Promise((resolve,reject)=>{const u=URL.createObjectURL(blob),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(Error('This photo format cannot be converted on this device'))};img.src=u})}
function saveBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
async function downloadJpg(p,button){if(!window.firebase?.auth?.().currentUser){alert('Sign in with an invited family account to download photos.');return}const old=button?.textContent;if(button){button.disabled=true;button.textContent='Preparing…'}try{const response=await fetch(p.url,{cache:'no-store'});if(!response.ok)throw Error(`Photo download failed (${response.status})`);const blob=await response.blob();if(/^image\/jpe?g$/i.test(blob.type||p.type||'')){saveBlob(blob,jpgName(p.name));return}const img=await imageFromBlob(blob),w=img.naturalWidth||img.width,h=img.naturalHeight||img.height;if(!w||!h)throw Error('The photo dimensions could not be read');const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);if(img.close)img.close();const jpg=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('JPG conversion failed')),'image/jpeg',.98));saveBlob(jpg,jpgName(p.name))}catch(e){console.error(e);alert(e.message||'This photo could not be downloaded as a JPG.')}finally{if(button){button.disabled=false;button.textContent=old}}}
function entry(p,m,d){return `<article class="mediaJournalEntry"><div class="mediaJournalEmoji">${esc(m.emoji||'📖')}</div><button class="mediaJournalPhoto" data-open="${esc(p.id)}"><img loading="lazy" src="${esc(p.url)}" alt="${esc(p.name||'Journal photo')}"></button><div class="mediaJournalCopy"><p>${esc(m.caption)}</p><small>${trip(d,p.tripId)?esc(trip(d,p.tripId).name)+' · ':''}${esc(m.by||'Family member')} · ${esc(new Date(+m.updatedAt||Date.now()).toLocaleString())}${m.pending?' · Sync pending':''}</small></div><div class="mediaJournalEntryActions"><button data-download="${esc(p.id)}">Download JPG</button><button data-edit="${esc(p.id)}">Edit</button></div></article>`}
function renderEntries(sec,d,ps,j){const h=sec.querySelector('.mediaJournalEntries'),rows=ps.filter(p=>j[p.id]?.caption).sort((a,b)=>+j[b.id].updatedAt-+j[a.id].updatedAt);h.innerHTML=`<h3>Photo Journal Entries</h3>${rows.length?rows.map(p=>entry(p,j[p.id],d)).join(''):'<p class="muted">No photo captions yet.</p>'}`;h.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>String(x.id)===b.dataset.open);if(p)app.openPhotoViewer(p.url,p.name||'Photo')});h.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>String(x.id)===b.dataset.download);if(p)downloadJpg(p,b)});h.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{sec.querySelector('#mediaJournalPhoto').value=b.dataset.edit;load(sec,ps,j);sec.scrollIntoView({behavior:'smooth',block:'start'})})}
function load(sec,ps,j){const id=sec.querySelector('#mediaJournalPhoto').value,p=ps.find(x=>String(x.id)===id),m=j[id]||{};sec.querySelector('#mediaJournalEmoji').value=m.emoji||'❤️';sec.querySelector('#mediaJournalCaption').value=m.caption||'';sec.querySelector('.mediaJournalRemove').hidden=!m.caption;sec.querySelectorAll('[data-pick]').forEach(b=>{const selected=b.dataset.pick===id;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected?'true':'false')});note(sec,p?(p.name||'Family photo'):'Choose an uploaded photo to begin.')}
async function save(sec,d,ps,j){const id=sec.querySelector('#mediaJournalPhoto').value,p=ps.find(x=>String(x.id)===id),caption=sec.querySelector('#mediaJournalCaption').value.trim();if(!p)return note(sec,'Choose an uploaded photo before saving.','error');if(!caption)return note(sec,'Add a caption before saving.','error');const m={caption,emoji:sec.querySelector('#mediaJournalEmoji').value.trim()||'📖',updatedAt:Date.now(),by:document.querySelector('#who')?.textContent?.trim()||'Family member',pending:true};j[id]=m;write(JK,j);cache(id,{journalCaption:m.caption,journalEmoji:m.emoji,journalUpdatedAt:m.updatedAt,journalByName:m.by});renderEntries(sec,d,ps,j);note(sec,'Caption saved. Syncing…');try{await remote(d,p,{journalCaption:m.caption,journalEmoji:m.emoji,journalUpdatedAt:m.updatedAt,journalByName:m.by});m.pending=false;write(JK,j);renderEntries(sec,d,ps,j);note(sec,'Photo journal caption saved and synced.','success')}catch(e){console.warn(e);note(sec,'Caption saved on this device. It will retry when connected.','pending')}}
async function remove(sec,d,ps,j){const id=sec.querySelector('#mediaJournalPhoto').value,p=ps.find(x=>String(x.id)===id);if(!p||!j[id])return;note(sec,'Removing caption…');try{await remote(d,p,{journalCaption:null,journalEmoji:null,journalUpdatedAt:null,journalByName:null});delete j[id];write(JK,j);cache(id,{journalCaption:null,journalEmoji:null,journalUpdatedAt:null,journalByName:null});renderEntries(sec,d,ps,j);load(sec,ps,j);note(sec,'Photo journal caption removed.','success')}catch(e){note(sec,'Reconnect to remove this caption.','error')}}
function picker(d,ps){return `<div class="mediaJournalPicker" role="group" aria-label="Choose a photo">${ps.length?ps.map(p=>`<button type="button" class="mediaJournalPick" data-pick="${esc(p.id)}" aria-pressed="false"><img loading="lazy" src="${esc(p.url)}" alt="${esc(p.name||'Family photo')}"><span>${esc(p.name||'Family photo')}</span><small>${trip(d,p.tripId)?esc(trip(d,p.tripId).name):'Shared family media'}</small></button>`).join(''):'<p class="muted">Upload photos in Media first.</p>'}</div>`}
function enhanceMediaDownloads(ps){document.querySelectorAll('#view .mediaTile').forEach(tile=>{if(tile.dataset.jpgReady)return;const img=tile.querySelector('img'),p=ps.find(x=>x.url===img?.src||x.url===img?.getAttribute('src'));if(!p)return;const old=tile.querySelector('.mediaActions a[download]');if(old){const b=document.createElement('button');b.type='button';b.textContent='Download JPG';b.onclick=()=>downloadJpg(p,b);old.replaceWith(b)}tile.dataset.jpgReady='yes'});const card=[...document.querySelectorAll('#view .card')].find(x=>x.querySelector(':scope > h2')?.textContent.trim()==='Media Library');if(card&&!card.querySelector('.mediaHighResNote')){const p=document.createElement('p');p.className='muted mediaHighResNote';p.textContent='Photos are uploaded at their original full resolution (up to 20 MB each). Any signed-in invited family member can download a full-size JPG copy.';const upload=card.querySelector('#mediaFile');(upload?.nextElementSibling||upload)?.after(p)}}
function inject(){const card=[...document.querySelectorAll('#view .card')].find(x=>x.querySelector(':scope > h2')?.textContent.trim()==='Media Library');if(!card)return;const d=data(),ps=photos(d);enhanceMediaDownloads(ps);if(card.querySelector('.mediaJournalSection'))return;const j=merge(d,ps),sec=document.createElement('section');sec.className='mediaJournalSection';sec.innerHTML=`<div class="mediaJournalHeading"><div><h3>Family Photo Journal</h3><p class="muted">Tap a photo thumbnail, then add a caption and emoji.</p></div><span>📔</span></div><div class="mediaJournalComposer"><label class="mediaJournalPhotoLabel">Choose an uploaded photo</label>${picker(d,ps)}<select id="mediaJournalPhoto" hidden aria-hidden="true"><option value=""></option>${ps.map(p=>`<option value="${esc(p.id)}">${esc(p.name||'Family photo')}</option>`).join('')}</select><label>Emoji<input id="mediaJournalEmoji" maxlength="12" value="❤️"></label><div class="mediaJournalEmojiChoices">${['❤️','😊','😂','🎉','🥳','📍','🌊','🏕️','✈️','🐾','🎂','✨'].map(e=>`<button type="button" data-emoji="${e}">${e}</button>`).join('')}</div><label class="mediaJournalCaptionLabel">Caption<textarea id="mediaJournalCaption" maxlength="1200" placeholder="Write the story or memory for this photo..."></textarea></label><p id="mediaJournalMessage" class="mediaJournalMessage" role="status">Choose an uploaded photo to begin.</p><div class="mediaJournalActions"><button class="primary mediaJournalSave">Save Caption</button><button class="danger mediaJournalRemove" hidden>Remove Caption</button></div></div><div class="mediaJournalEntries"></div>`;card.insertBefore(sec,card.querySelector('.mediaGrid'));sec.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{sec.querySelector('#mediaJournalPhoto').value=b.dataset.pick;load(sec,ps,j)});sec.querySelectorAll('[data-emoji]').forEach(b=>b.onclick=()=>sec.querySelector('#mediaJournalEmoji').value=b.dataset.emoji);sec.querySelector('.mediaJournalSave').onclick=()=>save(sec,d,ps,j);sec.querySelector('.mediaJournalRemove').onclick=()=>remove(sec,d,ps,j);renderEntries(sec,d,ps,j)}
async function retry(){if(!window.firebase?.database||!firebase.auth?.().currentUser)return;const d=data(),ps=photos(d),j=journal();for(const p of ps){const m=j[p.id];if(!m?.pending)continue;try{await remote(d,p,{journalCaption:m.caption,journalEmoji:m.emoji,journalUpdatedAt:m.updatedAt,journalByName:m.by});m.pending=false}catch(e){console.warn(e)}}write(JK,j)}
function enhance(){if(busy)return;busy=true;try{wrapRoute();redirect();hideScrapbook();inject();retry()}finally{busy=false}}
function start(){enhance();addEventListener('hashchange',enhance);addEventListener('online',retry);new MutationObserver(()=>queueMicrotask(enhance)).observe(document.body,{childList:true,subtree:true})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();
