/* Our Family Adventures - 6.5.1 deploy patch */
(function(){
  'use strict';
  const VERSION='6.5.1';
  const $=id=>document.getElementById(id);
  const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const toast=msg=>(window.toast?window.toast(msg):alert(msg));
  const save=()=>{try{ if(window.saveNow) return window.saveNow(); if(window.save) return window.save(); localStorage.setItem('ourFamilyAdventuresData',JSON.stringify(data)); }catch(e){console.warn(e)}};
  function ensure(){ if(!window.data && typeof data!=='undefined') window.data=data; if(!window.data)return null; const d=window.data; ['notifications','meals','trips','pages','memories','people'].forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]}); if(!d.profile)d.profile={}; if(!d.settings)d.settings={}; if(!d.settings.notifications)d.settings.notifications={}; return d; }
  function currentName(){const d=ensure()||{};return (d.profile?.name||localStorage.getItem('ofa_family_user')||localStorage.getItem('ofa_voter_name')||'').trim();}
  function currentUid(){try{return firebase.auth().currentUser?.uid||'local'}catch(e){return 'local'}}
  function firebaseDb(){try{ if(window.firebase&&firebase.apps?.length&&firebase.firestore) return firebase.firestore(); }catch(e){} return null;}
  function appFamily(){return localStorage.getItem('ofa_family_id')||'melissa-family';}

  /* Notifications */
  window.addNotification651=function(message,type='system',userSpecific=true){const d=ensure(); if(!d)return; const n={id:id(),message:String(message||''),type,read:false,userId:userSpecific?currentUid():'all',name:currentName(),at:new Date().toISOString(),version:VERSION}; d.notifications.unshift(n); d.notifications=d.notifications.slice(0,150); save(); renderNotifications651(); try{const db=firebaseDb(); if(db&&currentUid()!=='local') db.collection('families').doc(appFamily()).collection('notifications').doc(n.id).set(n,{merge:true});}catch(e){console.warn(e)} };
  window.markNotificationRead651=function(nid){const d=ensure(); const n=d.notifications.find(x=>x.id===nid); if(n)n.read=true; save(); renderNotifications651();};
  window.markAllNotificationsRead651=function(){const d=ensure(); d.notifications.forEach(n=>n.read=true); save(); renderNotifications651();};
  function renderNotifications651(){const d=ensure(); if(!d)return; const mine=d.notifications.filter(n=>!n.userId||n.userId==='all'||n.userId===currentUid()||currentUid()==='local'); const unread=mine.filter(n=>!n.read).length; document.querySelectorAll('.notifBadge').forEach(x=>x.remove()); ['loginBtn','settingsNotifyBtn','enableNotifications'].forEach(bid=>{const b=$(bid); if(b&&unread){b.style.position='relative'; b.insertAdjacentHTML('beforeend',`<span class="notifBadge">${unread}</span>`);}}); const log=$('notificationLog'); if(log) log.innerHTML=`<div class="buttonRow"><button class="secondary smallBtn" onclick="markAllNotificationsRead651()">Mark all read</button><button class="secondary smallBtn" onclick="addNotification651('Test notification is working.','system',true)">Test</button></div>`+(mine.length?mine.slice(0,30).map(n=>`<div class="notifItem ${n.read?'':'unread'}"><span>${n.read?'🔔':'🔴'}</span><div><b>${E(n.type||'Notice')}</b><p>${E(n.message||n.text||'')}</p><small>${new Date(n.at||Date.now()).toLocaleString()}${n.name?' • '+E(n.name):''}</small><br><button class="secondary smallBtn" onclick="markNotificationRead651('${n.id}')">Mark read</button></div></div>`).join(''):'<p>No notifications yet.</p>'); }
  function attachNotifListener(){try{const db=firebaseDb(); const u=currentUid(); if(!db||u==='local'||attachNotifListener.done)return; attachNotifListener.done=true; db.collection('families').doc(appFamily()).collection('notifications').orderBy('at','desc').limit(50).onSnapshot(s=>{const d=ensure(); s.forEach(doc=>{const n={id:doc.id,...doc.data()}; if(!d.notifications.some(x=>x.id===n.id))d.notifications.unshift(n);}); save(); renderNotifications651();});}catch(e){console.warn(e)}}

  /* Weather and maps */
  function tripPlace(t){return t?.address||t?.tripAddress||t?.destination||t?.name||'';}
  async function geocode(place){let r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(place)}&count=1&language=en&format=json`); let j=await r.json(); if(j.results?.[0])return j.results[0]; throw new Error('Location not found');}
  async function liveWeather(place){const g=await geocode(place); const url=`https://api.open-meteo.com/v1/forecast?latitude=${g.latitude}&longitude=${g.longitude}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`; const j=await fetch(url).then(r=>r.json()); if(!j.current)throw new Error('Provider did not return current weather'); return `${Math.round(j.current.temperature_2m)}°F now, feels ${Math.round(j.current.apparent_temperature)}° • High ${Math.round(j.daily.temperature_2m_max[0])}° / Low ${Math.round(j.daily.temperature_2m_min[0])}° • Rain ${j.daily.precipitation_probability_max[0]??0}% • Wind ${Math.round(j.current.wind_speed_10m)} mph`;}
  window.refreshTripWeather=async function(tid){const d=ensure(); const t=d.trips.find(x=>x.id===tid); const p=tripPlace(t); if(!p)return toast('Add a destination or address first.'); const boxes=document.querySelectorAll(`[data-weather-for="${tid}"]`); boxes.forEach(b=>{b.textContent='Loading live weather...';b.classList.add('weatherLoading')}); try{t.weather=await liveWeather(p); t.weatherUpdatedAt=new Date().toISOString(); save(); if(window.render)window.render(); addNotification651(`Weather updated for ${t.name||p}.`,'weather',true); toast('Weather updated');}catch(e){boxes.forEach(b=>{b.textContent='Live weather could not load. Check the destination/address or try a nearby city.';b.classList.remove('weatherLoading')}); toast('Live weather could not load. Try a nearby city or full address.'); console.warn(e);} };
  window.googleDirections651=p=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p||'')}`;
  function mapCard(place){return place?`<a class="mapCard" href="${googleDirections651(place)}" target="_blank" rel="noopener"><b>📍 ${E(place)}</b><br><small>Tap to open Google Maps directions</small></a>`:'';}

  /* Voting with names */
  function voteNames(v){return Object.keys(v.votes||{}).filter(Boolean);}
  function voteCount(v){return voteNames(v).length+(v.legacyCount||0);}
  function voteHtml(t){return (t.voteOptions||[]).map((v,i)=>{const names=voteNames(v); const links=(v.links||[]).map((l,n)=>` <a href="${E(l)}" target="_blank">Link ${n+1}</a>`).join(''); return `<div class="voteRow"><span><b>${E(v.text)}</b>${links}<br><small>${names.length?'Voted: '+E(names.join(', ')):'No votes yet'}</small></span><strong>${voteCount(v)} vote(s)</strong><button onclick="voteTrip('${t.id}',${i})" class="secondary">Vote / Change</button><button onclick="removeVoteOption('${t.id}',${i})" class="secondary">Admin Remove</button></div>`}).join('')||'<p>No voting options yet.</p>';}
  window.voteTrip=function(tid,index){const d=ensure(); const t=d.trips.find(x=>x.id===tid); const opt=t?.voteOptions?.[index]; if(!opt)return; let voter=currentName(); if(!voter)voter=(prompt('Your name for voting')||'').trim(); if(!voter)return toast('Vote canceled.'); localStorage.setItem('ofa_family_user',voter); localStorage.setItem('ofa_voter_name',voter); (t.voteOptions||[]).forEach(v=>{v.votes=v.votes||{}; delete v.votes[voter];}); opt.votes=opt.votes||{}; opt.votes[voter]=new Date().toISOString(); save(); if(window.render)window.render(); addNotification651(`${voter} voted on ${t.name}.`,'votes',false); toast('Vote saved');};
  window.renderVoting=function(){const box=$('votingList'); const d=ensure(); if(!box||!d)return; box.innerHTML=d.trips.map(t=>`<div class="card"><h3>${E(t.name)}</h3>${voteHtml(t)}<textarea id="voteInput-${t.id}" placeholder="Add several voting options, one per line"></textarea><textarea id="voteLinks-${t.id}" placeholder="Optional links, one per line"></textarea><button onclick="addVoteOptionsBulk('${t.id}')" class="secondary">Add voting item</button></div>`).join('')||'<div class="card"><p>No trips yet.</p></div>';};

  /* Meal type fix */
  function installMeals651(){const mt=$('mealTitle'); if(mt){const wrap=$('mealButtonsFinal'); if(wrap)wrap.remove(); mt.style.display=''; mt.outerHTML='<label>Meal type<select id="mealTitle"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option><option>Dessert</option><option>Drinks</option><option>Dining Out</option><option>Happy Hour</option></select></label>';}
    const b=$('saveMeal'); if(b)b.onclick=function(){const d=ensure(); const type=$('mealTitle')?.value||document.querySelector('input[name="mealTypeFinal"]:checked')?.value||'Dinner'; const item=($('mealItem')?.value||'').trim()||type; const person=$('mealPersonFinal')?.value||$('mealPerson')?.value||currentName()||'Volunteer needed'; d.meals.push({id:id(),trip:$('mealTrip')?.value||'General',title:type,mealType:type,item,person,scope:'group',private:false,done:false,createdAt:new Date().toISOString()}); if($('mealItem'))$('mealItem').value=''; save(); if(window.render)window.render(); addNotification651(`${type} added: ${item}`,'meals',false); toast(`${type} added`);};}

  /* Profile edit form with photo */
  function renderProfile(){const d=ensure(); if(!d)return; const p=d.profile; const box=$('profileSummary'); if(!box)return; const photo=p.photo||localStorage.getItem('ofa_profile_photo')||''; const name=p.name||currentName()||'Family Member'; const email=p.email||localStorage.getItem('ofa_family_email')||''; const phone=p.phone||localStorage.getItem('ofa_profile_phone')||''; box.innerHTML=`${photo?`<img class="profileAvatarBig" src="${E(photo)}" alt="Profile photo">`:`<div class="profileAvatarBig profileInitial">${E(name.slice(0,1).toUpperCase())}</div>`}<div class="profileDetails"><h3>${E(name)}</h3><p>${E(email||'No email saved')}</p><p>${E(phone||'No phone saved')}</p></div><div class="profileEditGrid"><label>Name<input id="profileName651" value="${E(name)}"></label><label>Email address<input id="profileEmail651" type="email" value="${E(email)}"></label><label>Phone number<input id="profilePhone651" type="tel" value="${E(phone)}"></label><label>Profile photo<input id="profilePhoto651" type="file" accept="image/*"></label><button id="profileSave651" class="primary">Save Profile</button></div>`; $('profileSave651').onclick=saveProfile;}
  function fileToDataURL(f){return new Promise((res,rej)=>{const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(f);});}
  async function saveProfile(){const d=ensure(); const p=d.profile; p.name=($('profileName651')?.value||'').trim()||'Family Member'; p.email=($('profileEmail651')?.value||'').trim(); p.phone=($('profilePhone651')?.value||'').trim(); const f=$('profilePhoto651')?.files?.[0]; if(f)p.photo=await fileToDataURL(f); localStorage.setItem('ofa_family_user',p.name); localStorage.setItem('ofa_family_email',p.email); localStorage.setItem('ofa_profile_phone',p.phone); if(p.photo)localStorage.setItem('ofa_profile_photo',p.photo); save(); try{const db=firebaseDb(); const u=firebase.auth().currentUser; if(db&&u&&!u.isAnonymous) await db.collection('users').doc(u.uid).set({...p,uid:u.uid,updatedAt:new Date().toISOString()},{merge:true});}catch(e){console.warn(e)} renderProfile(); toast('Profile saved');}
  window.renderProfile650=renderProfile;

  /* Scrapbook draft studio */
  const stickers=['🐚','⭐','🌊','☀️','⚓','❤️','🗼','🏖️','🏕️','⛰️','🛶','🚤','✈️','🧳','📍','🗺️','🔥','🌲','🌻','🌸','🦋','🐐','🐾','🎣','🍔','🌭','🍕','🍦','🎂','🎈','🇺🇸','🎆','🎄','🎃','🦃','❄️','💙','💛','😂','😍','🥰','😎','🙌'];
  const frames=['soft','polaroid','heart','scallop','star','moon','sun','wood'];
  let draft={ids:[],layout:'grid',frame:'soft',bg:'seaGlass',stickers:[],texts:[]};
  function photoPool(){const d=ensure(); const out=[]; (d.memories||[]).forEach(m=>(m.media||[]).forEach((x,i)=>{const src=typeof x==='string'?x:(x.src||x.url||x.data); if(src&&String(src).startsWith('data:image')||/^https?:|^\.\//.test(src||'')) out.push({id:`${m.id||'m'}-${i}`,src,title:m.title||'Memory'});})); return out;}
  function installScrapbook(){const host=$('scrapbookPhotoPicker'); if(!host)return; host.innerHTML=`<h3>Draft Scrapbook Page</h3><p>Pick photos, rearrange them, choose a layout, crop/zoom, add or remove stickers, then save the finished page.</p><div class="scrapDraftStudio"><div class="scrapToolbar"><label>Layout<select id="draftLayout"><option value="grid">Grid</option><option value="feature">Feature Photo</option><option value="collage">Collage</option><option value="freeform">Freeform</option></select></label><label>Frame<select id="draftFrame">${frames.map(f=>`<option value="${f}">${f[0].toUpperCase()+f.slice(1)}</option>`).join('')}</select></label><label>Background<select id="draftBg"><option value="seaGlass">Sea Glass</option><option value="sunset">Sunset</option><option value="sand">Beach Sand</option><option value="roseGold">Rose Gold</option><option value="lighthouse">Lighthouse</option></select></label><button id="addDraftText" class="secondary">Add Text</button><button id="clearDraft" class="secondary">Clear Draft</button></div><h4>Photos</h4><div id="draftPhotoChoices" class="scrapDraftPickGrid"></div><h4>Rearrange Selected Photos</h4><div id="draftStrip" class="draftStrip"></div><h4>Stickers & Emojis</h4><div class="stickerPalette">${stickers.map(s=>`<button class="secondary" data-sticker="${s}">${s}</button>`).join('')}</div><div id="draftCanvas" class="scrapCanvas"></div></div>`; ['draftLayout','draftFrame','draftBg'].forEach(x=>$(x).onchange=()=>{draft[x.replace('draft','').toLowerCase()]=$(x).value; renderDraft();}); $('addDraftText').onclick=()=>{const txt=prompt('Text for scrapbook page',$('pageTextBox')?.value||''); if(txt)draft.texts.push({id:id(),text:txt,x:40,y:160,size:18}); renderDraft();}; $('clearDraft').onclick=()=>{draft.ids=[];draft.stickers=[];draft.texts=[];renderDraft();renderChoices();}; document.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>{draft.stickers.push({id:id(),emoji:b.dataset.sticker,x:50,y:220,size:44});renderDraft();}); renderChoices(); renderDraft(); const saveBtn=$('savePage'); if(saveBtn)saveBtn.onclick=savePage; }
  function renderChoices(){const pool=photoPool(); const box=$('draftPhotoChoices'); if(!box)return; box.innerHTML=pool.length?pool.map(p=>`<button class="draftPhotoChoice ${draft.ids.includes(p.id)?'selected':''}" data-pid="${p.id}"><img src="${p.src}"><small>${E(p.title)}</small></button>`).join(''):'<p>No memory photos yet. Add photos in Memories first.</p>'; box.querySelectorAll('[data-pid]').forEach(b=>b.onclick=()=>{const pid=b.dataset.pid; draft.ids.includes(pid)?draft.ids=draft.ids.filter(x=>x!==pid):draft.ids.push(pid); renderChoices(); renderDraft();});}
  function renderStrip(pool){const strip=$('draftStrip'); if(!strip)return; strip.innerHTML=draft.ids.map((pid,i)=>{const p=pool.find(x=>x.id===pid); return p?`<div class="draftStripItem"><img src="${p.src}"><br><button onclick="scrapMove651(${i},-1)">←</button><button onclick="scrapMove651(${i},1)">→</button><button onclick="scrapRemove651('${pid}')">Remove</button></div>`:''}).join('')||'<p>No photos selected.</p>';}
  window.scrapMove651=(i,dir)=>{const j=i+dir;if(j<0||j>=draft.ids.length)return; [draft.ids[i],draft.ids[j]]=[draft.ids[j],draft.ids[i]]; renderChoices(); renderDraft();};
  window.scrapRemove651=pid=>{draft.ids=draft.ids.filter(x=>x!==pid); renderChoices(); renderDraft();};
  function renderDraft(){const pool=photoPool(); renderStrip(pool); const canvas=$('draftCanvas'); if(!canvas)return; draft.layout=$('draftLayout')?.value||draft.layout; draft.frame=$('draftFrame')?.value||draft.frame; draft.bg=$('draftBg')?.value||draft.bg; const title=$('pageTitle')?.value||'Draft Scrapbook Page'; const note=$('pageNote')?.value||''; canvas.className=`scrapCanvas bg-${draft.bg} layout-${draft.layout}`; canvas.innerHTML=`<h3>${E(title)}</h3><div class="photoLayer">${draft.ids.map(pid=>{const p=pool.find(x=>x.id===pid); return p?`<div class="scrapPhotoBox frame-${draft.frame}"><img src="${p.src}"><button class="secondary smallBtn" onclick="scrapRemove651('${pid}')">Remove</button></div>`:''}).join('')}</div><p class="pageNote">${E(note)}</p>`+draft.stickers.map(s=>`<div class="movableSticker" data-mid="${s.id}" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${s.emoji}<span class="resizeHandle">↘</span></div>`).join('')+draft.texts.map(t=>`<div class="movableText" data-mid="${t.id}" style="left:${t.x}px;top:${t.y}px;font-size:${t.size}px">${E(t.text)}<span class="resizeHandle">↘</span></div>`).join(''); makeMovable(canvas);}
  function makeMovable(canvas){canvas.querySelectorAll('.movableSticker,.movableText').forEach(el=>{let target=[...draft.stickers,...draft.texts].find(x=>x.id===el.dataset.mid); if(!target)return; let start=null; el.onpointerdown=e=>{if(e.target.classList.contains('resizeHandle')){start={resize:true,x:e.clientX,size:target.size};}else start={x:e.clientX,y:e.clientY,left:target.x,top:target.y}; el.setPointerCapture(e.pointerId);}; el.onpointermove=e=>{if(!start)return; if(start.resize){target.size=Math.max(18,Math.min(120,start.size+(e.clientX-start.x)/2));}else{target.x=Math.max(0,start.left+e.clientX-start.x);target.y=Math.max(0,start.top+e.clientY-start.y);} renderDraft();}; el.onpointerup=()=>start=null; el.ondblclick=()=>{draft.stickers=draft.stickers.filter(x=>x.id!==target.id);draft.texts=draft.texts.filter(x=>x.id!==target.id);renderDraft();};});}
  function savePage(){const d=ensure(); const pool=photoPool(); const photos=draft.ids.map(pid=>pool.find(p=>p.id===pid)?.src).filter(Boolean); const page={id:id(),title:($('pageTitle')?.value||'Scrapbook Page').trim(),note:($('pageNote')?.value||'').trim(),layout:draft.layout,frame:draft.frame,bg:draft.bg,photos,stickers:JSON.parse(JSON.stringify(draft.stickers)),texts:JSON.parse(JSON.stringify(draft.texts)),createdAt:new Date().toISOString(),version:VERSION}; if(!photos.length&&!page.title&&!page.note)return toast('Select photos or add a title/note first.'); d.pages.push(page); draft.ids=[];draft.stickers=[];draft.texts=[]; save(); renderChoices(); renderDraft(); renderPages651(); addNotification651(`Scrapbook page saved: ${page.title}`,'scrapbook',false); toast('Scrapbook page saved');}
  window.renderPages=window.renderPages651=function(){const d=ensure(); const box=$('scrapbookPages'); if(!box)return; box.innerHTML=d.pages.map(p=>`<div class="scrapPage scrapCanvas bg-${p.bg||'seaGlass'} layout-${p.layout||'grid'}"><h3>${E(p.title)}</h3><div>${(p.photos||[]).map(src=>`<div class="scrapPhotoBox frame-${p.frame||'soft'}"><img src="${src}"></div>`).join('')||'<p>No photos selected.</p>'}</div><p>${E(p.note||'')}</p>${(p.stickers||[]).map(s=>`<span class="movableSticker" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${s.emoji}</span>`).join('')}${(p.texts||[]).map(t=>`<span class="movableText" style="left:${t.x}px;top:${t.y}px;font-size:${t.size}px">${E(t.text)}</span>`).join('')}<div class="scrapTools noPrint"><button onclick="exportScrapbookPage&&exportScrapbookPage('${p.id}')" class="secondary">Export JPG</button><button onclick="del('pages','${p.id}')" class="secondary">Delete</button></div></div>`).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>';};

  function patchTripsRender(){const old=window.renderTrips; window.renderTrips=function(){const d=ensure(); const box=$('tripList'); if(!box||!d)return old&&old(); box.innerHTML=d.trips.map(t=>{const place=tripPlace(t); return `<div class="item tripCard"><h3>${E(t.name)}</h3><p>${E(t.destination||'')} ${t.start?`• ${E(t.start)} to ${E(t.end||'')}`:''}</p>${mapCard(place)}<p class="weatherBox" data-weather-for="${t.id}">${E(t.weather||'No live weather loaded yet.')}</p><div class="itemActions"><button onclick="editTrip('${t.id}')" class="primary">Edit Trip</button><button onclick="refreshTripWeather('${t.id}')" class="secondary">Live Weather</button><button onclick="window.open(googleDirections651('${E(place)}'),'_blank')" class="secondary">Directions</button></div><div class="voteBox"><h4>Family Voting</h4>${voteHtml(t)}<textarea id="voteInput-${t.id}" placeholder="Add voting options, one per line"></textarea><textarea id="voteLinks-${t.id}" placeholder="Optional links, one per line"></textarea><button onclick="addVoteOptionsBulk('${t.id}')" class="secondary">Add voting item</button></div></div>`}).join('')||'<div class="card"><p>No trips yet.</p></div>';};}

  function init(){ensure(); document.documentElement.setAttribute('data-version',VERSION); installMeals651(); installScrapbook(); patchTripsRender(); renderProfile(); renderNotifications651(); attachNotifListener(); if($('testNotifyBtn'))$('testNotifyBtn').onclick=()=>addNotification651('Test notification is working.','system',true); if($('enableNotifications'))$('enableNotifications').onclick=()=>addNotification651('Notifications are turned on inside the app.','system',true); const oldRender=window.render; window.render=function(){try{oldRender&&oldRender();}catch(e){console.warn(e)} installMeals651(); patchTripsRender(); renderProfile(); renderNotifications651(); if(window.renderVoting)renderVoting(); if(window.renderPages651)renderPages651();}; setTimeout(()=>{try{window.render&&window.render()}catch(e){}},300);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init); else init();
})();
