/* Our Family Adventures 6.6.2 — travel links save/load repair */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const now=()=>new Date().toISOString();
  const me=()=>{try{return data?.profile?.name||firebase?.auth?.().currentUser?.displayName||firebase?.auth?.().currentUser?.email||localStorage.getItem('ofa_family_user')||'Family member'}catch{return 'Family member'}};
  const toastMsg=m=>{try{typeof toast==='function'?toast(m):alert(m)}catch{console.log(m)}};
  function ensure(){ if(!window.data)return false; ['trips','links','activity'].forEach(k=>{if(!Array.isArray(data[k]))data[k]=[]}); data.trips.forEach(t=>{if(!Array.isArray(t.tripLinks))t.tripLinks=[]}); return true; }
  function normUrl(u){ u=String(u||'').trim(); if(!u)return ''; if(!/^https?:\/\//i.test(u))u='https://'+u; return u; }
  function keyLink(l){ return ((l.url||'').replace(/\/$/,'')+'|'+(l.title||'').trim()+'|'+(l.tripId||l.trip||'')).toLowerCase(); }
  function allLinks(){ ensure(); const map=new Map(); (data.links||[]).forEach(l=>{ if(l&&l.url) map.set(keyLink(l), l); }); (data.trips||[]).forEach(t=>{ (t.tripLinks||[]).forEach(l=>{ if(!l||!l.url)return; const x={...l, tripId:l.tripId||t.id, trip:l.trip||t.name}; map.set(keyLink(x), x); }); }); return [...map.values()]; }
  function saveNow(){ try{ if(typeof normalizeData==='function')normalizeData(); }catch{} try{ localStorage.setItem('ofaDataFinalV4',JSON.stringify(data)); localStorage.setItem('ofaData',JSON.stringify(data)); }catch{} try{ if(typeof queueFirebaseSave==='function')queueFirebaseSave(); else if(typeof pushFirebaseData==='function')pushFirebaseData(); else if(typeof save==='function')save(); }catch(e){console.warn(e)} }
  function addGlobalLink(){ if(!ensure())return; const title=($('linkTitle')?.value||'Travel link').trim(); const url=normUrl($('linkUrl')?.value); if(!url){toastMsg('Add the travel link first.'); return;} const tripVal=$('linkTrip')?.value||'General'; const t=data.trips.find(x=>x.name===tripVal||x.id===tripVal); const link={id:uid(),title,url,trip:t?.name||tripVal,tripId:t?.id||'',createdAt:now(),addedBy:me()}; data.links.push(link); if(t){t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link);} dedupeLinks(); if($('linkTitle'))$('linkTitle').value=''; if($('linkUrl'))$('linkUrl').value=''; saveNow(); renderTravel(); try{ if(typeof renderTrips==='function')renderTrips(); }catch{} toastMsg('Travel link saved'); }
  function addTripLinkFixed(tripId){ if(!ensure())return; const t=data.trips.find(x=>x.id===tripId); if(!t)return; const title=($(`tripLinkTitle-${tripId}`)?.value||'Travel link').trim(); const url=normUrl($(`tripLinkUrl-${tripId}`)?.value); if(!url){toastMsg('Add the travel link first.'); return;} const link={id:uid(),title,url,trip:t.name,tripId:t.id,createdAt:now(),addedBy:me()}; data.links.push(link); t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link); dedupeLinks(); if($(`tripLinkTitle-${tripId}`))$(`tripLinkTitle-${tripId}`).value=''; if($(`tripLinkUrl-${tripId}`))$(`tripLinkUrl-${tripId}`).value=''; saveNow(); renderTravel(); try{ if(typeof renderTrips==='function')renderTrips(); }catch{} toastMsg('Trip link saved'); }
  function dedupeLinks(){ if(!ensure())return; const map=new Map(); allLinks().forEach(l=>map.set(keyLink(l),l)); data.links=[...map.values()]; data.trips.forEach(t=>{const tm=new Map(); data.links.filter(l=>l.tripId===t.id||l.trip===t.name).forEach(l=>tm.set(keyLink(l),l)); t.tripLinks=[...tm.values()];}); }
  window.addTripLink=addTripLinkFixed;
  window.tripLinkRows=function(t){ const arr=allLinks().filter(l=>l.tripId===t.id||l.trip===t.name); return arr.length?`<div class="tripLinks"><h4>Travel Links</h4>${arr.map(l=>`<div class="linkRow"><a href="${esc(normUrl(l.url))}" target="_blank" rel="noopener">${esc(l.title||'Travel link')}</a><button onclick="removeTripLink662('${t.id}','${l.id}')" class="secondary smallBtn">Remove</button></div>`).join('')}</div>`:'<p class="helperText">No travel links yet.</p>'; };
  window.removeTripLink662=function(tid,lid){ ensure(); data.links=data.links.filter(l=>l.id!==lid); data.trips.forEach(t=>{t.tripLinks=(t.tripLinks||[]).filter(l=>l.id!==lid)}); saveNow(); renderTravel(); try{ if(typeof renderTrips==='function')renderTrips(); }catch{} };
  window.renderTravel=function(){ const box=$('travelList'); if(!box)return; dedupeLinks(); const arr=allLinks(); box.innerHTML=arr.length?arr.map(l=>`<div class="item"><h3>${esc(l.title||'Travel link')}</h3><p>${esc(l.trip||'General')}</p><a href="${esc(normUrl(l.url))}" target="_blank" rel="noopener">Open link</a><br><button onclick="removeTripLink662('${esc(l.tripId||'')}','${esc(l.id)}')" class="secondary">Delete</button></div>`).join(''):'<div class="card"><p>No travel links yet.</p></div>'; };
  function fillLinkTrips(){ const sel=$('linkTrip'); if(!sel||!ensure())return; const cur=sel.value; sel.innerHTML=(data.trips||[]).map(t=>`<option value="${esc(t.name)}">${esc(t.name)}</option>`).join('')+'<option value="General">General</option>'; if(cur) sel.value=cur; }
  // 6.6.1 stopped button clicks during capture. This capture listener performs the save directly.
  document.addEventListener('click',e=>{ const b=e.target.closest('button'); if(!b)return; const txt=(b.textContent||'').trim().toLowerCase(); if(txt==='save link' || txt==='add travel link'){ e.preventDefault(); addGlobalLink(); } else if(txt==='add trip link'){ e.preventDefault(); const input=b.parentElement?.querySelector('input[id^="tripLinkUrl-"]'); const id=input?.id?.replace('tripLinkUrl-',''); if(id)addTripLinkFixed(id); } }, true);
  const oldRender=window.render;
  window.render=function(){ try{oldRender&&oldRender();}catch(e){console.warn(e)} fillLinkTrips(); renderTravel(); };
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{fillLinkTrips();renderTravel();},500));
  setTimeout(()=>{fillLinkTrips();renderTravel();},1200);
})();
