/* Version 6.5.2 corrective build: weather, voting, scrapbook draft, lists, explore map, notifications, profile, links */
(function(){
  const VERSION='6.5.2';
  const q=id=>document.getElementById(id);
  const qa=s=>Array.from(document.querySelectorAll(s));
  const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const canData=()=>typeof data!=='undefined';
  const saveApp=()=>{try{ if(typeof save==='function') save(); else localStorage.setItem('ofa_v5_data',JSON.stringify(data)); }catch(e){console.warn(e)}};
  const msg=m=>{try{toast(m)}catch{console.log(m)}};
  function ensure(){ if(!canData())return false; ['people','trips','memories','pages','links','meals','groceries','packing','pins','chat','notifications'].forEach(k=>{if(!Array.isArray(data[k]))data[k]=[]}); if(!data.profile)data.profile={}; (data.trips||[]).forEach(t=>{ if(!Array.isArray(t.voteOptions))t.voteOptions=[]; if(!Array.isArray(t.tripLinks))t.tripLinks=[]; if(t.address&&!t.tripAddress)t.tripAddress=t.address; }); return true; }
  const me=()=> (data?.profile?.name || localStorage.getItem('ofa_voter_name') || firebase?.auth?.().currentUser?.displayName || firebase?.auth?.().currentUser?.email || 'Family Member').trim();
  const profileEmail=()=> data?.profile?.email || firebase?.auth?.().currentUser?.email || '';
  function placeFor(t){return (t.tripAddress||t.address||t.destination||t.name||'').trim();}
  function mapsUrl(place){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place||'');}
  function directionsUrl(place){return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(place||'');}
  function mapCard(place,label='Map'){ if(!place)return '<p class="helperWarn">Add a destination or trip address to show the map and weather.</p>'; return `<div class="mapCard"><b>${E(label)}</b><iframe class="mapEmbed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=${encodeURIComponent(place)}&output=embed"></iframe><div class="mapActions"><a class="secondary" href="${directionsUrl(place)}" target="_blank" rel="noopener">Open Google Maps Directions</a></div></div>`; }

  // Save address/budget fields that the original save handler missed.
  function patchTripSave(){ const btn=q('saveTrip'); if(!btn||btn.dataset.v652)return; btn.dataset.v652='1'; const old=btn.onclick; btn.onclick=function(e){ const address=q('tripAddress')?.value.trim()||''; const budget=q('tripBudget')?.value||''; old&&old.call(this,e); const t=(data.trips||[]).slice().reverse().find(x=>(x.name||'')===(q('tripName')?.value||'') || !x.tripAddress); const newest=(data.trips||[])[data.trips.length-1]; const target=editingTripId?(data.trips||[]).find(x=>x.id===editingTripId):(newest||t); if(target){ if(address){target.tripAddress=address; target.address=address;} if(budget)target.budget=budget; saveApp(); } render652(); } }

  // Weather: use destination/address, not a separate destination prompt. Works on HTTPS with open-meteo.
  async function liveWeather(place){ if(!place)return {text:'Add a destination or trip address first.',ok:false}; try{ const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(place)}&count=1&language=en&format=json`,{cache:'no-store'}).then(r=>r.json()); const g=geo?.results?.[0]; if(!g)return {text:'Weather could not find that destination. Try city and state, like Mariposa, CA.',ok:false}; const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${g.latitude}&longitude=${g.longitude}&current=temperature_2m,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`,{cache:'no-store'}).then(r=>r.json()); const now=Math.round(w?.current?.temperature_2m); const hi=Math.round(w?.daily?.temperature_2m_max?.[0]); const lo=Math.round(w?.daily?.temperature_2m_min?.[0]); const rain=w?.daily?.precipitation_probability_max?.[0]; return {text:`${g.name}${g.admin1?`, ${g.admin1}`:''}: ${Number.isFinite(now)?now+'°F now':''} • High ${Number.isFinite(hi)?hi+'°':''} / Low ${Number.isFinite(lo)?lo+'°':''}${rain!=null?' • Rain chance '+rain+'%':''}`,ok:true}; }catch(e){return {text:'Live weather could not load. Check internet, then try city/state instead of a full address.',ok:false};} }
  window.refreshTripWeather=async function(tripId){ ensure(); const t=(data.trips||[]).find(x=>x.id===tripId) || (typeof byNextTrip==='function'?byNextTrip():null); if(!t)return msg('Add a trip first.'); const box=q(`weather-${t.id}`)||q('dashWeather'); if(box)box.innerHTML='<span class="weatherStatus"><span class="weatherSpinner"></span> Loading live weather...</span>'; const res=await liveWeather(placeFor(t)); t.weather=res.text; t.weatherUpdatedAt=new Date().toISOString(); saveApp(); addNotify(`Weather updated for ${t.name||'trip'}`,'weather'); render652(); };
  window.refreshDashboardWeather=()=>{ const t=typeof byNextTrip==='function'?byNextTrip():(data.trips||[])[0]; if(t)refreshTripWeather(t.id); else msg('Add an adventure first.'); };

  // Voting names always visible; voting tab also works when trips exist but no options yet.
  function voteCount2(v){return Object.keys(v.votes||{}).length + Number(v.legacyCount||0)}
  window.voteTrip=function(tripId,index){ ensure(); const t=(data.trips||[]).find(x=>x.id===tripId); const v=t?.voteOptions?.[index]; if(!v)return; const voter=(data.profile?.name||localStorage.getItem('ofa_voter_name')||prompt('Your name for voting')||'').trim(); if(!voter)return; localStorage.setItem('ofa_voter_name',voter); (t.voteOptions||[]).forEach(o=>{o.votes=o.votes||{}; delete o.votes[voter];}); v.votes=v.votes||{}; v.votes[voter]=new Date().toISOString(); saveApp(); addNotify(`${voter} voted on ${t.name}`,'votes'); render652(); };
  window.addVoteOptionsBulk=function(tripId){ ensure(); const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; const opts=(q('voteInput-'+tripId)?.value||'').split(/[\n,]+/).map(s=>s.trim()).filter(Boolean); const links=(q('voteLink-'+tripId)?.value||q('voteLinks-'+tripId)?.value||'').split(/[\n,]+/).map(s=>s.trim()).filter(Boolean); if(!opts.length&&!links.length)return msg('Add a voting option or link first.'); if(!Array.isArray(t.voteOptions))t.voteOptions=[]; const count=Math.max(opts.length,links.length); for(let i=0;i<count;i++){ const text=opts[i]||links[i]||`Option ${i+1}`; const link=links[i]||(/^https?:\/\//i.test(text)?text:''); t.voteOptions.push({id:id(),text,link,votes:{}}); } if(q('voteInput-'+tripId))q('voteInput-'+tripId).value=''; if(q('voteLink-'+tripId))q('voteLink-'+tripId).value=''; if(q('voteLinks-'+tripId))q('voteLinks-'+tripId).value=''; saveApp(); addNotify('New voting option added','votes'); render652(); };
  function votingBlock(t){ return `<div class="voteBox"><h4>Family Voting</h4>${(t.voteOptions||[]).map((v,i)=>`<div class="voteRow"><div><b>${E(v.text)}</b>${v.link?`<br><a href="${E(v.link)}" target="_blank" rel="noopener">Open link</a>`:''}<small class="voteNames">Voted: ${Object.keys(v.votes||{}).map(E).join(', ')||'No one yet'}</small></div><strong>${voteCount2(v)} vote(s)</strong><button onclick="voteTrip('${t.id}',${i})" class="secondary">Vote / Change</button><button onclick="removeVoteOption&&removeVoteOption('${t.id}',${i})" class="secondary">Remove</button></div>`).join('')||'<p class="helperText">No voting options yet. Add options below.</p>'}<div class="voteAdd"><textarea id="voteInput-${t.id}" placeholder="Add choices, one per line"></textarea><textarea id="voteLink-${t.id}" placeholder="Optional links, one per line"></textarea><button onclick="addVoteOptionsBulk('${t.id}')" class="secondary">Add voting option(s)</button></div></div>`; }
  function renderVoting652(){ const box=q('votingList'); if(!box)return; ensure(); box.innerHTML=(data.trips||[]).map(t=>`<div class="card"><h3>${E(t.name||'Adventure')}</h3><p>${E(placeFor(t)||'No destination yet')}</p>${votingBlock(t)}</div>`).join('') || '<div class="card"><p>No trips added yet. Add an adventure first, then return here to add voting options.</p></div>'; }

  // Trip links save in both trip and global links so old dashboard renderers can find them.
  window.addTripLink=function(tripId){ ensure(); const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; const title=(q('tripLinkTitle-'+tripId)?.value||'Travel link').trim(); let url=(q('tripLinkUrl-'+tripId)?.value||'').trim(); if(url && !/^https?:\/\//i.test(url))url='https://'+url; if(!url)return msg('Add a travel link first.'); const link={id:id(),tripId:t.id,trip:t.name,title,url,createdAt:new Date().toISOString(),addedBy:me()}; t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link); data.links=data.links||[]; data.links.push(link); saveApp(); addNotify(`Travel link saved: ${title}`,'trips'); render652(); };

  // Group/private list adders. Meal type comes from select, never defaults to dinner unless dinner selected.
  function setupListForms(){ const mt=q('mealTitle'); if(mt){ mt.closest('label')?.classList.add('hidden'); if(!q('mealTypeSelect652')) mt.closest('label')?.insertAdjacentHTML('beforebegin',`<label>Meal type<select id="mealTypeSelect652"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option><option>Dessert</option><option>Drinks</option><option>Dining out</option><option>Happy hour</option></select></label><label>List type<select id="mealScopeSelect652"><option value="group">Group meal</option><option value="private">Private meal</option></select></label>`); }
    [['groceryItem','groceryScopeSelect652','Group grocery list','Private grocery item'],['packingItem','packingScopeSelect652','Group packing list','Private packing item']].forEach(([anchor,sel,g,p])=>{const a=q(anchor); if(a&&!q(sel))a.insertAdjacentHTML('beforebegin',`<label>List type<select id="${sel}"><option value="group">${g}</option><option value="private">${p}</option></select></label>`);});
    if(q('saveMeal'))q('saveMeal').onclick=()=>addList('meal'); if(q('saveGrocery'))q('saveGrocery').onclick=()=>addList('grocery'); if(q('savePacking'))q('savePacking').onclick=()=>addList('packing'); }
  function addList(kind){ ensure(); const trip=q(kind==='meal'?'mealTrip':kind+'Trip')?.value||'General'; const item=(q(kind==='meal'?'mealItem':kind+'Item')?.value||'').trim(); if(!item)return msg('Add an item first.'); const scope=q(kind==='meal'?'mealScopeSelect652':kind+'ScopeSelect652')?.value||'group'; const person=(q(kind+'Person')?.value||q(kind+'PersonSelect64')?.value||'Volunteer needed').trim(); const obj={id:id(),trip,item,person:scope==='private'?me():person,private:scope==='private',scope,owner:scope==='private'?me():person,addedBy:me(),done:false,createdAt:new Date().toISOString()}; if(kind==='meal'){obj.title=q('mealTypeSelect652')?.value||'Dinner'; obj.mealType=obj.title; data.meals.push(obj); q('mealItem').value=''; addNotify(`${scope==='private'?'Private':'Group'} ${obj.title} added`,'meals');} if(kind==='grocery'){data.groceries.push(obj); q('groceryItem').value=''; addNotify('Grocery item added','meals');} if(kind==='packing'){data.packing.push(obj); q('packingItem').value=''; addNotify('Packing item added','trips');} saveApp(); render652(); }
  function row(key,x,title,sub){return `<div class="item checklistItem"><label class="checkLine"><input type="checkbox" ${x.done?'checked':''} onchange="toggleDone&&toggleDone('${key}','${x.id}')"><span><b>${E(title)}</b><small>${E(sub||'')}</small></span></label><p class="helperText">${x.private?'Private item':'Group item'}${x.person?' • Assigned: '+E(x.person):''}</p><div class="itemActions"><button onclick="editListItem&&editListItem('${key}','${x.id}')" class="secondary smallBtn">Edit</button><button onclick="del&&del('${key}','${x.id}')" class="secondary smallBtn">Delete</button></div></div>`;}
  function renderMeals652(){ const box=q('mealList'); if(!box)return; ensure(); const mine=me(); const vis=x=>!x.private||x.owner===mine||x.addedBy===mine||x.person===mine; const meals=data.meals.filter(vis), groceries=data.groceries.filter(vis); box.innerHTML=`<div class="card"><h3>Group Meal Plan</h3>${meals.filter(x=>!x.private).map(m=>row('meals',m,`${m.mealType||m.title||'Meal'}: ${m.item}`,m.trip)).join('')||'<p>No group meals added yet.</p>'}</div><div class="card"><h3>My Private Meal Plan</h3>${meals.filter(x=>x.private).map(m=>row('meals',m,`${m.mealType||m.title||'Meal'}: ${m.item}`,m.trip)).join('')||'<p>No private meals added yet.</p>'}</div><div class="card"><h3>Group Grocery List</h3>${groceries.filter(x=>!x.private).map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No group grocery items added yet.</p>'}</div><div class="card"><h3>My Private Grocery List</h3>${groceries.filter(x=>x.private).map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No private grocery items added yet.</p>'}</div>`; }
  function renderPacking652(){ const box=q('packingList'); if(!box)return; const mine=me(); const items=(data.packing||[]).filter(x=>!x.private||x.owner===mine||x.addedBy===mine||x.person===mine); box.innerHTML=`<div class="card"><h3>Group Packing List</h3>${items.filter(x=>!x.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No group packing items added yet.</p>'}</div><div class="card"><h3>My Private Packing List</h3>${items.filter(x=>x.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No private packing items added yet.</p>'}</div>`; }

  // Scrapbook draft editor: photos display from memories and can be selected, reordered, zoom/cropped, removed, framed, stickered.
  const stickers='📷 💕 ❤️ 💛 💙 ⭐ ✨ 🌙 ☀️ 🌈 🏖️ 🐚 🌊 ⚓ 🗼 🏕️ 🔥 🌲 ⛰️ 🥾 🛶 🚤 🎣 🐟 🐐 🐾 🦋 🌻 🌸 🎂 🎈 🎉 🇺🇸 🎆 🎄 🎃 🦃 ❄️ 🍔 🌭 🍕 🍦 🍹 🍻 🥂 🧭 🗺️ 📍 ✈️ 🧳 😎 😂 🥰 🙌'.split(' ');
  const frameTypes=['soft','polaroid','heart','scallop','star','moon','sun','wood'];
  let draft={photos:[],layout:'grid',frame:'soft',bg:'seaGlass',stickers:[],texts:[],zooms:{}};
  function imgPool(){ const out=[]; (data.memories||[]).forEach(m=>(m.media||[]).forEach((media,i)=>{ let src=typeof media==='string'?media:(media.src||media.url||media.data||''); const type=(media.type||'').toLowerCase(); if(src && (src.startsWith('data:image')||src.startsWith('http')||src.startsWith('./')||type==='image'))out.push({id:media.id||`${m.id}-${i}`,src,title:m.title||m.memoryTitle||'Memory'}); })); return out; }
  function installScrapbook652(){ const host=q('scrapbookPhotoPicker'); if(!host||host.dataset.v652)return; host.dataset.v652='1'; host.innerHTML=`<h3>Draft Scrapbook Page</h3><p>Select photos, rearrange them, crop/zoom, add frames, add moveable/resizable stickers, then save the page.</p><div class="scrapDraftStudio"><div class="scrapTopTools"><label>Layout<select id="draftLayout652"><option value="grid">Grid</option><option value="feature">Feature Photo</option><option value="collage">Collage</option><option value="freeform">Freeform</option></select></label><label>Frame category<select id="draftFrame652">${frameTypes.map(f=>`<option value="${f}">${f}</option>`).join('')}</select></label><label>Background<select id="draftBg652"><option value="seaGlass">Sea Glass</option><option value="sunset">Sunset</option><option value="sand">Beach Sand</option><option value="roseGold">Rose Gold</option><option value="lighthouse">Lighthouse</option></select></label><button id="addDraftText652" class="secondary">Add Text</button></div><h4>Pick Photos</h4><div id="draftPhotoChoices652" class="scrapPhotoPickerGrid"></div><h4>Selected Photos — rearrange / crop / remove</h4><div id="draftStrip652" class="draftStrip"></div><h4>Frames / Cutouts</h4><div class="framePalette">${frameTypes.map(f=>`<button class="secondary" data-frame652="${f}">${f}</button>`).join('')}</div><h4>Stickers & Emojis</h4><div class="stickerPalette">${stickers.map(s=>`<button class="secondary" data-sticker652="${s}">${s}</button>`).join('')}</div><div id="draftCanvas652" class="scrapCanvas"></div></div>`; ['draftLayout652','draftFrame652','draftBg652'].forEach(x=>q(x).onchange=()=>renderDraft()); q('addDraftText652').onclick=()=>{const text=prompt('Text for this scrapbook page',q('pageTextBox')?.value||''); if(text){draft.texts.push({id:id(),text,x:34,y:80,size:22});renderDraft();}}; qa('[data-sticker652]').forEach(b=>b.onclick=()=>{draft.stickers.push({id:id(),emoji:b.dataset.sticker652,x:40+draft.stickers.length*12,y:260,size:46});renderDraft();}); qa('[data-frame652]').forEach(b=>b.onclick=()=>{draft.frame=b.dataset.frame652; q('draftFrame652').value=draft.frame; renderDraft();}); if(q('savePage'))q('savePage').onclick=saveScrapPage652; renderDraftChoices(); renderDraft(); }
  function renderDraftChoices(){ const pool=imgPool(), box=q('draftPhotoChoices652'); if(!box)return; box.innerHTML=pool.length?pool.map(p=>`<button class="scrapPick ${draft.photos.includes(p.id)?'selected':''}" data-pick="${p.id}"><img src="${p.src}"><small>${E(p.title)}</small></button>`).join(''):'<p class="helperWarn">No photos found yet. Add photos under Memories first, then come back here.</p>'; box.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const pid=b.dataset.pick; draft.photos=draft.photos.includes(pid)?draft.photos.filter(x=>x!==pid):[...draft.photos,pid]; renderDraftChoices(); renderDraft();}); }
  window.scrapMove652=function(i,d){const j=i+d;if(j<0||j>=draft.photos.length)return; [draft.photos[i],draft.photos[j]]=[draft.photos[j],draft.photos[i]]; renderDraft(); renderDraftChoices();}; window.scrapRemove652=function(pid){draft.photos=draft.photos.filter(x=>x!==pid); renderDraft(); renderDraftChoices();}; window.scrapZoom652=function(pid,delta){draft.zooms[pid]=Math.max(.7,Math.min(2.4,(draft.zooms[pid]||1)+delta)); renderDraft();};
  function renderStrip(pool){ const strip=q('draftStrip652'); if(!strip)return; strip.innerHTML=draft.photos.map((pid,i)=>{const p=pool.find(x=>x.id===pid); return p?`<div class="draftStripItem"><img src="${p.src}"><div><button onclick="scrapMove652(${i},-1)" class="secondary smallBtn">←</button><button onclick="scrapMove652(${i},1)" class="secondary smallBtn">→</button><button onclick="scrapZoom652('${pid}',.1)" class="secondary smallBtn">Crop +</button><button onclick="scrapZoom652('${pid}',-.1)" class="secondary smallBtn">Crop -</button><button onclick="scrapRemove652('${pid}')" class="secondary smallBtn">Remove</button></div></div>`:''}).join('')||'<p>No photos selected yet.</p>'; }
  function renderDraft(){ const pool=imgPool(); renderStrip(pool); const canvas=q('draftCanvas652'); if(!canvas)return; draft.layout=q('draftLayout652')?.value||draft.layout; draft.frame=q('draftFrame652')?.value||draft.frame; draft.bg=q('draftBg652')?.value||draft.bg; canvas.className=`scrapCanvas layout-${draft.layout} bg-${draft.bg}`; canvas.innerHTML=`<h3>${E(q('pageTitle')?.value||'Draft Scrapbook Page')}</h3><div class="photoLayer">${draft.photos.map(pid=>{const p=pool.find(x=>x.id===pid); return p?`<div class="scrapPhotoBox frame-${draft.frame}"><img src="${p.src}" style="--zoom:${draft.zooms[pid]||1}"><button class="secondary smallBtn" onclick="scrapRemove652('${pid}')">Remove</button></div>`:''}).join('')}</div><p>${E(q('pageNote')?.value||'')}</p>${draft.stickers.map(s=>`<span class="movableSticker" data-move="${s.id}" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${s.emoji}<span class="resizeHandle">↘</span></span>`).join('')}${draft.texts.map(t=>`<span class="movableText" data-move="${t.id}" style="left:${t.x}px;top:${t.y}px;font-size:${t.size}px">${E(t.text)}<span class="resizeHandle">↘</span></span>`).join('')}`; makeMove(canvas); }
  function makeMove(canvas){ canvas.querySelectorAll('[data-move]').forEach(el=>{ const obj=[...draft.stickers,...draft.texts].find(x=>x.id===el.dataset.move); if(!obj)return; let start=null; el.onpointerdown=e=>{e.preventDefault(); start=e.target.classList.contains('resizeHandle')?{resize:true,x:e.clientX,size:obj.size}:{x:e.clientX,y:e.clientY,left:obj.x,top:obj.y}; el.setPointerCapture(e.pointerId);}; el.onpointermove=e=>{ if(!start)return; if(start.resize)obj.size=Math.max(18,Math.min(132,start.size+(e.clientX-start.x)/2)); else{obj.x=Math.max(0,start.left+e.clientX-start.x);obj.y=Math.max(0,start.top+e.clientY-start.y);} renderDraft();}; el.onpointerup=()=>{start=null}; el.ondblclick=()=>{draft.stickers=draft.stickers.filter(x=>x.id!==obj.id);draft.texts=draft.texts.filter(x=>x.id!==obj.id);renderDraft();}; }); }
  function saveScrapPage652(){ ensure(); const pool=imgPool(); const photos=draft.photos.map(pid=>{const p=pool.find(x=>x.id===pid);return p&&{id:pid,src:p.src,zoom:draft.zooms[pid]||1}}).filter(Boolean); if(!photos.length)return msg('Select at least one photo for the scrapbook page.'); data.pages.push({id:id(),title:q('pageTitle')?.value||'Scrapbook Page',note:q('pageNote')?.value||'',theme:q('pageTheme')?.value||'',layout:draft.layout,frame:draft.frame,bg:draft.bg,photos:photos.map(p=>p.src),photoItems:photos,stickers:JSON.parse(JSON.stringify(draft.stickers)),texts:JSON.parse(JSON.stringify(draft.texts)),createdAt:new Date().toISOString(),version:VERSION}); draft={photos:[],layout:'grid',frame:'soft',bg:'seaGlass',stickers:[],texts:[],zooms:{}}; saveApp(); addNotify('Scrapbook page saved','scrapbook'); render652(); }
  function renderPages652(){ const box=q('scrapbookPages'); if(!box)return; box.innerHTML=(data.pages||[]).map(p=>`<div class="scrapPage scrapCanvas layout-${E(p.layout||'grid')} bg-${E(p.bg||'seaGlass')}"><h3>${E(p.title)}</h3><div class="photoLayer">${(p.photoItems||p.photos||[]).map((ph,i)=>{const src=typeof ph==='string'?ph:ph.src; const zoom=typeof ph==='string'?1:(ph.zoom||1); return `<div class="scrapPhotoBox frame-${E(p.frame||'soft')}"><img src="${src}" style="--zoom:${zoom}"></div>`}).join('')}</div><p>${E(p.note||'')}</p>${(p.stickers||[]).map(s=>`<span class="movableSticker" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${s.emoji}</span>`).join('')}${(p.texts||[]).map(t=>`<span class="movableText" style="left:${t.x}px;top:${t.y}px;font-size:${t.size}px">${E(t.text)}</span>`).join('')}<div class="scrapTools noPrint"><button onclick="window.print()" class="secondary">Print / PDF</button><button onclick="del&&del('pages','${p.id}')" class="secondary">Delete</button></div></div>`).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>'; }

  // Explore map panel with pins.
  function ensureExplore(){ if(q('explore'))return; const after=q('chat')||q('packing')||q('meals'); after?.insertAdjacentHTML('afterend',`<section id="explore" class="page"><div class="pageHead"><h2>Explore Map</h2><p>Saved places, trip pins, and directions.</p></div><div class="card formCard"><h3>Add Map Pin</h3><label>Pin name<input id="pinName" placeholder="Beach house, restaurant, trailhead..."></label><label>Address or place<input id="pinAddress" placeholder="Place or full address"></label><button id="savePin652" class="primary">Add Pin</button></div><div id="exploreMap" class="exploreMapPanel"></div></section>`); const nav=document.querySelector('.bottomNav,.drawerNav'); if(nav&&!document.querySelector('[data-go="explore"]'))nav.insertAdjacentHTML('beforeend','<button data-go="explore">🗺️<span>Explore</span></button>'); const grid=document.querySelector('.storybookGrid'); if(grid&&!grid.querySelector('[data-go="explore"]'))grid.insertAdjacentHTML('beforeend','<button data-go="explore" class="storybookCard">🗺️<span>Explore Map</span><small>View pins and open directions.</small></button>'); if(q('savePin652'))q('savePin652').onclick=()=>{const name=q('pinName').value.trim()||'Saved place'; const address=q('pinAddress').value.trim(); if(!address)return msg('Add an address or place first.'); data.pins.push({id:id(),name,address,createdAt:new Date().toISOString(),addedBy:me()}); saveApp(); render652();}; }
  function renderExplore(){ const box=q('exploreMap'); if(!box)return; ensure(); const tripPins=(data.trips||[]).map(t=>placeFor(t)?{id:t.id,name:t.name,address:placeFor(t),trip:t.name}:null).filter(Boolean); const pins=[...tripPins,...(data.pins||[])]; const first=pins[0]?.address||''; box.innerHTML=first?`${mapCard(first,'Map with saved pins')}<div class="explorePinList">${pins.map(p=>`<div class="explorePin"><b>${E(p.name)}</b><br><small>${E(p.address)}</small><br><a class="secondary" href="${directionsUrl(p.address)}" target="_blank">Directions</a></div>`).join('')}</div>`:'<p class="helperWarn">No pins yet. Add a trip destination or save a map pin.</p>'; }

  // Notifications center + app badge + local phone notification when permission granted and app is open.
  function addNotify(text,type='general',system=false){ ensure(); const n={id:id(),text,type,read:false,at:new Date().toISOString(),user:profileEmail()||me()}; data.notifications.unshift(n); data.notifications=data.notifications.slice(0,80); saveApp(); updateBadge(); if(Notification?.permission==='granted' && !document.hasFocus()){ try{navigator.serviceWorker?.ready?.then(reg=>reg.showNotification('Our Family Adventures',{body:text,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:n.id,data:{url:location.href}}));}catch{} } }
  window.addAppNotification=addNotify; window.addNotification651=addNotify; window.markNotificationRead652=function(nid){const n=data.notifications.find(x=>x.id===nid); if(n)n.read=true; saveApp(); renderNotifications();};
  function ensureNotifUI(){ if(!q('notifyBell652'))document.body.insertAdjacentHTML('beforeend',`<button id="notifyBell652" class="roundBtn notificationBell" title="Notifications">🔔<span id="notifyCount652" class="notifyDot" hidden>0</span></button><div id="notificationPanel652" class="chatPopout hidden"><div class="chatHeader"><b>Notifications</b><button id="closeNotify652">×</button></div><div id="notificationList652"></div></div>`); q('notifyBell652').onclick=()=>{renderNotifications();q('notificationPanel652').classList.toggle('hidden')}; q('closeNotify652').onclick=()=>q('notificationPanel652').classList.add('hidden'); if(q('enableNotifications'))q('enableNotifications').onclick=async()=>{ if('Notification'in window){await Notification.requestPermission();} addNotify('Notifications are enabled in the app. Phone screen notifications work while the installed app/browser is allowed to send notifications.','system',true); renderNotifications();}; }
  function updateBadge(){ const unread=(data.notifications||[]).filter(n=>!n.read).length; const b=q('notifyCount652'); if(b){b.hidden=!unread;b.textContent=unread;} try{navigator.setAppBadge?navigator.setAppBadge(unread):navigator.clearAppBadge&&unread===0&&navigator.clearAppBadge();}catch{} }
  function renderNotifications(){ const list=q('notificationList652'); if(!list)return; list.innerHTML=(data.notifications||[]).map(n=>`<div class="item ${n.read?'':'unread'}"><b>${E(n.type||'Notice')}</b><p>${E(n.text)}</p><small>${new Date(n.at).toLocaleString()}</small><br><button class="secondary smallBtn" onclick="markNotificationRead652('${n.id}')">Mark read</button></div>`).join('')||'<p>No notifications yet.</p>'; updateBadge(); }

  // Profile editor allows name, phone, photo, and contact email. Firebase Auth email update attempted when signed in.
  function ensureProfileEditor(){ const people=q('people'); if(!people||q('profileEditor652'))return; people.insertAdjacentHTML('afterbegin',`<div id="profileEditor652" class="profileEditor651 card"><h3>My Profile</h3><div class="twoCols"><div><img id="profilePhotoPreview652" class="profilePhotoPreview" src="icons/icon-192.png" alt="Profile photo"></div><div><label>Name<input id="profileName652"></label><label>Email address<input id="profileEmail652" type="email"></label><label>Phone<input id="profilePhone652" type="tel"></label><label>Profile photo<input id="profilePhoto652" type="file" accept="image/*"></label><button id="saveProfile652" class="primary">Save My Profile</button><p class="helperText">Changing your login email may require recent sign-in. If Firebase blocks the login email change, your profile contact email will still save.</p></div></div></div>`); q('profilePhoto652').onchange=e=>{const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{data.profile.photo=r.result; q('profilePhotoPreview652').src=r.result;}; r.readAsDataURL(f);}; q('saveProfile652').onclick=saveProfile652; fillProfileForm(); }
  function fillProfileForm(){ ensure(); q('profileName652')&&(q('profileName652').value=data.profile.name||me()); q('profileEmail652')&&(q('profileEmail652').value=data.profile.email||profileEmail()); q('profilePhone652')&&(q('profilePhone652').value=data.profile.phone||''); q('profilePhotoPreview652')&&(q('profilePhotoPreview652').src=data.profile.photo||'icons/icon-192.png'); }
  async function saveProfile652(){ ensure(); const email=q('profileEmail652').value.trim(); data.profile.name=q('profileName652').value.trim()||me(); data.profile.email=email; data.profile.phone=q('profilePhone652').value.trim(); try{ const user=firebase?.auth?.().currentUser; if(user){ if(user.updateProfile)await user.updateProfile({displayName:data.profile.name,photoURL:data.profile.photo||user.photoURL}); if(email && email!==user.email && user.updateEmail)await user.updateEmail(email); } }catch(e){ msg('Profile saved. Firebase login email may require signing out and back in before it can change.'); } saveApp(); addNotify('Profile updated','profile'); render652(); }

  function renderTrips652(){ const box=q('tripList'); if(!box)return; ensure(); box.innerHTML=(data.trips||[]).map(t=>{const place=placeFor(t); const links=[...(t.tripLinks||[]),...(data.links||[]).filter(l=>l.tripId===t.id||l.trip===t.name)]; return `<div class="item tripCard"><h3>${E(t.name)}</h3><p>${E(t.destination||'')} ${t.start?`• ${E(t.start)} to ${E(t.end||'')}`:''}</p>${mapCard(place,t.name||'Trip map')}<div id="weather-${t.id}" class="weatherLiveCard"><b>Live Weather</b><p>${E(t.weather||'Tap Refresh Live Weather to load the forecast.')}</p><button onclick="refreshTripWeather('${t.id}')" class="secondary">Refresh Live Weather</button></div><div class="linkBox"><h4>Travel Links</h4>${links.length?links.map(l=>`<div class="linkRow"><a href="${E(l.url)}" target="_blank" rel="noopener">${E(l.title||l.url)}</a><button onclick="removeTripLink&&removeTripLink('${t.id}','${l.id}')" class="secondary smallBtn">Remove</button></div>`).join(''):'<p>No travel links saved yet.</p>'}<div class="voteAdd"><input id="tripLinkTitle-${t.id}" placeholder="Link title"><input id="tripLinkUrl-${t.id}" placeholder="website.com or https://..."><button onclick="addTripLink('${t.id}')" class="secondary">Add travel link</button></div></div>${votingBlock(t)}<div class="itemActions"><button onclick="editTrip&&editTrip('${t.id}')" class="primary">Edit Trip</button><button onclick="openTripMap652('${t.id}')" class="secondary">Open Directions</button><button onclick="del&&del('trips','${t.id}')" class="secondary">Delete</button></div></div>`}).join('')||'<div class="card"><p>No trips added yet. Add an adventure first.</p></div>'; }
  window.openTripMap652=function(tripId){ const t=(data.trips||[]).find(x=>x.id===tripId); const p=placeFor(t||{}); if(!p)return msg('Add a destination or address first.'); data.pins=data.pins||[]; if(!data.pins.some(x=>x.address===p))data.pins.push({id:id(),name:t.name,address:p,trip:t.name,createdAt:new Date().toISOString()}); saveApp(); window.open(directionsUrl(p),'_blank'); };

  function patchDashboard(){ const btn=q('refreshWeatherBtn'); if(btn&&!btn.dataset.v652){btn.dataset.v652='1';btn.onclick=window.refreshDashboardWeather;} const t=typeof byNextTrip==='function'?byNextTrip():(data.trips||[])[0]; if(q('dashWeather')&&t){q('dashWeather').innerHTML=`<b>Live Weather</b><p>${E(t.weather||'Tap refresh to load live weather.')}</p>`;} if(q('dashMaps')&&t)q('dashMaps').innerHTML=mapCard(placeFor(t),t.name||'Trip map'); }

  const oldRender=window.render;
  function render652(){ if(!ensure())return; try{oldRender&&oldRender();}catch(e){console.warn('old render failed',e)} setupListForms(); installScrapbook652(); ensureExplore(); ensureNotifUI(); ensureProfileEditor(); renderTrips652(); renderVoting652(); renderMeals652(); renderPacking652(); renderPages652(); renderDraftChoices(); renderDraft(); renderExplore(); renderNotifications(); patchDashboard(); if(typeof bindNav==='function'){try{bindNav()}catch{}} qa('[data-go]').forEach(b=>b.onclick=()=>{if(typeof show==='function')show(b.dataset.go); setTimeout(render652,50);}); }
  window.render=render652;
  document.addEventListener('DOMContentLoaded',()=>{ensure(); patchTripSave(); setupListForms(); installScrapbook652(); ensureExplore(); ensureNotifUI(); ensureProfileEditor(); render652();});
  setTimeout(()=>{ensure(); patchTripSave(); render652();},600);
})();
