/* Our Family Adventures 6.6.1 — fixes from screenshots: meal dropdowns, duplicate links/votes, weather geocoding, scrapbook draft/edit, people merge */
(function(){
  'use strict';
  const VERSION='6.6.1';
  const $=id=>document.getElementById(id);
  const $$=s=>Array.from(document.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const now=()=>new Date().toISOString();
  const toastMsg=m=>{try{typeof toast==='function'?toast(m):console.log(m)}catch{console.log(m)}};
  const me=()=>{try{return data?.profile?.name||firebase?.auth?.().currentUser?.displayName||firebase?.auth?.().currentUser?.email||localStorage.getItem('ofa_family_user')||'Family member'}catch{return 'Family member'}};
  function ensure(){ if(!window.data)return false; ['people','trips','memories','pages','links','meals','groceries','packing','pins','chat','activity','notifications'].forEach(k=>{if(!Array.isArray(data[k]))data[k]=[]}); data.trips.forEach(t=>{if(!Array.isArray(t.tripLinks))t.tripLinks=[]; if(!Array.isArray(t.voteOptions))t.voteOptions=[]}); return true; }
  function saveNow(){try{if(typeof normalizeData==='function')normalizeData()}catch{}; try{localStorage.setItem('ofaDataFinalV4',JSON.stringify(data)); localStorage.setItem('ofaData',JSON.stringify(data));}catch{}; try{ if(typeof queueFirebaseSave==='function')queueFirebaseSave(); else if(typeof pushFirebaseData==='function')pushFirebaseData(); else if(typeof save==='function')save(); }catch(e){console.warn(e)} }
  function prettyDate(d){ if(!d)return ''; const x=new Date(String(d).slice(0,10)+'T12:00:00'); return isNaN(x)?String(d):x.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}); }
  function dateRange(start,end){ const out=[]; if(!start)return out; const s=new Date(start+'T12:00:00'), e=new Date((end||start)+'T12:00:00'); if(isNaN(s)||isNaN(e))return out; for(let d=new Date(s); d<=e; d.setDate(d.getDate()+1)){out.push(d.toISOString().slice(0,10)); if(out.length>45)break;} return out; }
  function mealTypes(i,total){ if(total<=1)return ['Breakfast','Lunch','Dinner','Snack']; if(i===0)return ['Lunch','Dinner','Snack']; if(i===total-1)return ['Breakfast','Lunch']; return ['Breakfast','Lunch','Dinner','Snack']; }
  function currentTrip(){ const v=$('mealTrip661')?.value||$('mealTrip')?.value; return data.trips.find(t=>String(t.id)===v||t.name===v)||data.trips[0]||null; }
  function normUrl(u){ u=String(u||'').trim(); if(!u)return ''; if(!/^https?:\/\//i.test(u))u='https://'+u; return u; }
  function keyLink(l){return ((l.url||'').replace(/\/$/,'')+'|'+(l.title||'').trim()+'|'+(l.tripId||l.trip||'')).toLowerCase();}
  function dedupeAll(){ if(!ensure())return; const seenP=new Set(); data.people=data.people.filter(p=>{const k=(p.email||'').toLowerCase().trim()||String(p.phone||'').replace(/\D/g,'')||String(p.name||'').toLowerCase().trim(); if(!k)return true; if(seenP.has(k))return false; seenP.add(k); return true;}); const seenL=new Set(); data.links=data.links.filter(l=>{const k=keyLink(l); if(seenL.has(k))return false; seenL.add(k); return true;}); data.trips.forEach(t=>{const seenTL=new Set(); t.tripLinks=(t.tripLinks||[]).filter(l=>{const k=keyLink({...l,tripId:t.id}); if(seenTL.has(k))return false; seenTL.add(k); return true;}); const seenV=new Set(); t.voteOptions=(t.voteOptions||[]).filter(v=>{const k=((v.text||'').trim()+'|'+(v.link||v.url||'')).toLowerCase(); if(!k.trim())return false; if(seenV.has(k))return false; seenV.add(k); if(!v.votes)v.votes={}; return true;}); }); }

  function fixButtonsNoRefresh(){ document.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; const txt=(b.textContent||'').toLowerCase(); if(/add travel link|save link|add voting|add vote|add option|add meal|add grocery/i.test(txt)){e.preventDefault(); e.stopPropagation();}},true); }

  function patchTripDates(){ const start=$('tripStart'), end=$('tripEnd'); if(!start||!end||start.dataset.v661)return; start.dataset.v661='1'; start.addEventListener('change',()=>{ if(start.value){ end.min=start.value; if(!end.value || end.value<start.value) end.value=start.value; }}); }

  function enhanceMealUI(){ if(!ensure())return; const section=$('meals'); if(!section)return; const form=section.querySelector('.formCard'); if(form&&!$('mealDate661')){
      const titleLabel=$('mealTitle')?.closest('label');
      titleLabel?.insertAdjacentHTML('afterend',`<div class="twoCols mealDropdown661"><label>Date<select id="mealDate661"></select></label><label>Meal<select id="mealType661"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option><option>Dessert</option><option>Drinks</option><option>Dining Out</option></select></label></div><label>Meal list<select id="mealScope661"><option value="group">Group meal list</option><option value="private">My private meal list</option></select></label>`);
      $('mealTrip')?.addEventListener('change',fillMealDates661);
    }
    fillMealDates661(); const btn=$('saveMeal'); if(btn&&!btn.dataset.v661){btn.dataset.v661='1'; btn.onclick=function(ev){ev&&ev.preventDefault(); const trip=$('mealTrip')?.value||currentTrip()?.name||'General'; const date=$('mealDate661')?.value||''; const type=$('mealType661')?.value||$('mealTitle')?.value||'Meal'; const scope=$('mealScope661')?.value||'group'; const item=($('mealItem')?.value||'').trim()||type; const person=($('mealPerson')?.value||'').trim()||'Volunteer needed'; data.meals.push({id:uid(),trip,date,mealDate:date,title:type,mealType:type,item,person,scope,private:scope==='private',owner:scope==='private'?me():person,addedBy:me(),done:false,createdAt:now()}); if($('mealItem'))$('mealItem').value=''; if($('mealPerson'))$('mealPerson').value=''; saveNow(); render(); toastMsg('Meal added');};}
  }
  function fillMealDates661(){ const sel=$('mealDate661'); if(!sel)return; const trip=(data.trips||[]).find(t=>t.name===$('mealTrip')?.value||t.id===$('mealTrip')?.value)||currentTrip(); const dates=trip?dateRange(trip.start,trip.end):[]; sel.innerHTML=dates.length?dates.map(d=>`<option value="${d}">${esc(prettyDate(d))}</option>`).join(''):'<option value="">Add trip dates first</option>'; }
  function rowMeal(m){return `<div class="item mealRow"><b>${esc(prettyDate(m.date||m.mealDate))} ${esc(m.mealType||m.title||'Meal')}</b><br>${esc(m.item||'Meal item')}<br><small>${esc(m.person||'Volunteer needed')} • ${esc(m.trip||'General')}</small><button onclick="deleteMeal661('${m.id}')" class="secondary smallBtn">Delete</button></div>`;}
  window.deleteMeal661=id=>{data.meals=data.meals.filter(m=>m.id!==id); saveNow(); render();};
  window.renderMeals=function(){ const box=$('mealList'); if(!box)return; ensure(); const mine=me(); const group=data.meals.filter(m=>m.scope!=='private'&&!m.private); const priv=data.meals.filter(m=>m.scope==='private'||m.private||m.owner===mine); const groGroup=data.groceries.filter(g=>g.scope!=='private'&&!g.private); const groPriv=data.groceries.filter(g=>g.scope==='private'||g.private||g.owner===mine); box.innerHTML=`<div class="card"><h3>Group Meal List</h3>${group.map(rowMeal).join('')||'<p>No group meals yet.</p>'}</div><div class="card"><h3>My Private Meal List</h3>${priv.map(rowMeal).join('')||'<p>No private meals yet.</p>'}</div><div class="card"><h3>Group Grocery List</h3>${groGroup.map(g=>`<div class="item"><b>${esc(g.item)}</b><br><small>${esc(g.person||'Unassigned')} • ${esc(g.trip||'General')}</small></div>`).join('')||'<p>No group groceries yet.</p>'}</div><div class="card"><h3>My Private Grocery List</h3>${groPriv.map(g=>`<div class="item"><b>${esc(g.item)}</b><br><small>${esc(g.person||'You')} • ${esc(g.trip||'General')}</small></div>`).join('')||'<p>No private groceries yet.</p>'}</div>`; };

  window.addTripLink=function(id){ ensure(); const t=data.trips.find(x=>x.id===id); if(!t)return; const title=($(`tripLinkTitle-${id}`)?.value||'Trip link').trim(); const url=normUrl($(`tripLinkUrl-${id}`)?.value); if(!url)return toastMsg('Add the link first.'); const link={id:uid(),trip:t.name,tripId:t.id,title,url,createdAt:now(),addedBy:me()}; t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link); data.links.push(link); dedupeAll(); saveNow(); render(); toastMsg('Travel link saved once'); };
  if(typeof window.tripLinkRows!=='function') window.tripLinkRows=function(t){ const map=new Map(); [...(t.tripLinks||[]),...data.links.filter(l=>l.tripId===t.id||l.trip===t.name)].forEach(l=>map.set(keyLink(l),l)); const arr=[...map.values()]; return arr.length?arr.map(l=>`<div class="linkRow"><a href="${esc(normUrl(l.url))}" target="_blank" rel="noopener">${esc(l.title||'Travel link')}</a><button onclick="removeTripLink661('${t.id}','${l.id}')" class="secondary smallBtn">Remove</button></div>`).join(''):'<p>No trip links yet.</p>'; };
  window.removeTripLink661=function(tid,lid){ const t=data.trips.find(x=>x.id===tid); if(t)t.tripLinks=(t.tripLinks||[]).filter(l=>l.id!==lid); data.links=data.links.filter(l=>l.id!==lid); saveNow(); render(); };
  function patchSaveLink(){ const b=$('saveLink'); if(!b||b.dataset.v661)return; b.dataset.v661='1'; b.onclick=function(ev){ev&&ev.preventDefault(); const title=($('linkTitle')?.value||'Travel link').trim(); const url=normUrl($('linkUrl')?.value); if(!url)return toastMsg('Add the travel link first.'); const tripName=$('linkTrip')?.value||'General'; const t=data.trips.find(x=>x.name===tripName||x.id===tripName); const link={id:uid(),trip:t?.name||tripName,tripId:t?.id||'',title,url,createdAt:now(),addedBy:me()}; data.links.push(link); if(t){t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link);} $('linkTitle').value=''; $('linkUrl').value=''; dedupeAll(); saveNow(); render(); toastMsg('Travel link saved');}; }
  window.renderTravel=function(){ const box=$('travelList'); if(!box)return; dedupeAll(); box.innerHTML=(data.links||[]).map(l=>`<div class="item"><h3>${esc(l.title||'Travel link')}</h3><p>${esc(l.trip||'General')}</p><a href="${esc(normUrl(l.url))}" target="_blank" rel="noopener">Open link</a><br><button onclick="del('links','${l.id}')" class="secondary">Delete</button></div>`).join('')||'<div class="card"><p>No travel links yet.</p></div>'; };

  window.addVoteOptionsBulk=function(tripId){ ensure(); const t=data.trips.find(x=>x.id===tripId); if(!t)return; const txt=($(`voteInput-${tripId}`)?.value||'').split(/\n|,/).map(s=>s.trim()).filter(Boolean); const links=($(`voteLinks-${tripId}`)?.value||$(`voteLink-${tripId}`)?.value||'').split(/\n|,/).map(s=>normUrl(s)).filter(Boolean); if(!txt.length&&!links.length)return toastMsg('Add a voting option first.'); t.voteOptions=t.voteOptions||[]; (txt.length?txt:links.map((_,i)=>`Link option ${i+1}`)).forEach((text,i)=>t.voteOptions.push({id:uid(),text,link:links[i]||'',votes:{},createdAt:now(),addedBy:me()})); if($(`voteInput-${tripId}`))$(`voteInput-${tripId}`).value=''; if($(`voteLinks-${tripId}`))$(`voteLinks-${tripId}`).value=''; if($(`voteLink-${tripId}`))$(`voteLink-${tripId}`).value=''; dedupeAll(); saveNow(); render(); toastMsg('Voting option saved'); };

  function geocodeCandidates(place){ const p=String(place||'').trim(); const parts=p.split(',').map(x=>x.trim()).filter(Boolean); const out=[p]; if(parts.length>=3)out.push(parts[1]+', '+parts[2].replace(/\d{5}.*/,'')); if(parts.length>=2)out.push(parts.slice(-2).join(', ').replace(/\d{5}.*/,'')); const zip=(p.match(/\b\d{5}\b/)||[])[0]; if(zip)out.push(zip); return [...new Set(out.filter(Boolean))]; }
  async function liveWeather661(place){ for(const q of geocodeCandidates(place)){ try{ const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=en&format=json`).then(r=>r.json()); const r=g.results&&g.results[0]; if(!r)continue; const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${r.latitude}&longitude=${r.longitude}&current=temperature_2m,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`).then(r=>r.json()); return `${r.name}${r.admin1?', '+r.admin1:''}: ${Math.round(w.current.temperature_2m)}°F now. High ${Math.round(w.daily.temperature_2m_max[0])}° / Low ${Math.round(w.daily.temperature_2m_min[0])}° • Rain ${Math.round(w.daily.precipitation_probability_max[0]||0)}%`; }catch(e){console.warn(e)} } return 'Live weather could not find that destination. Try city and state, such as Dunmore, PA.'; }
  window.refreshTripWeather=async function(id){ const t=data.trips.find(x=>x.id===id)||data.trips[0]; if(!t)return; toastMsg('Loading live weather...'); const place=t.address||t.tripAddress||t.destination||t.name; t.weather=await liveWeather661(place); t.weatherUpdatedAt=now(); saveNow(); render(); };

  function imageMedia661(){ const out=[]; (data.memories||[]).forEach(m=>(m.media||[]).forEach((mm,i)=>{const src=mm.src||mm.url||mm.dataUrl||mm; if(src&&String(src).startsWith('data:image')||/^https?:|^blob:/.test(String(src)))out.push({id:mm.id||`${m.id}-${i}`,src,title:m.title||'Memory'});})); return out; }
  function draftPhotos(){ const imgs=imageMedia661(); try{return imgs.filter(x=>window.selectedScrapPhotos?.includes(x.id));}catch{return []} }
  function renderDraft661(){ const host=$('scrapbookPhotoPicker')||$('scrapbookPages')?.parentElement; if(!host)return; let box=$('draftPage661'); if(!box){host.insertAdjacentHTML('afterend',`<div id="draftPage661" class="card draftPage661"><h3>Draft Scrapbook Page</h3><div id="draftCanvas661" class="draftCanvas661"></div><div class="buttonRow noPrint"><button id="saveDraftPage661" class="primary">Save Draft as Scrapbook Page</button><button id="clearDraft661" class="secondary">Clear Draft</button></div></div>`); box=$('draftPage661'); $('clearDraft661').onclick=()=>{try{window.selectedScrapPhotos=[]}catch{}; renderDraft661();}; $('saveDraftPage661').onclick=()=>{const photos=draftPhotos().map(x=>x.src); const page={id:uid(),title:$('pageTitle')?.value||'Scrapbook Page',note:$('pageNote')?.value||'',theme:$('pageTheme')?.value||'Beach Day',layout:$('pageLayout')?.value||'freeform',frame:$('pageFrame')?.value||'soft',photos,stickers:[],createdAt:now()}; data.pages.push(page); try{window.selectedScrapPhotos=[]}catch{}; saveNow(); render(); toastMsg('Scrapbook page saved');}; }
    const photos=draftPhotos(); $('draftCanvas661').innerHTML=photos.length?photos.map((p,i)=>`<img class="draftPhoto661" src="${p.src}" style="left:${8+(i%2)*44}%;top:${8+Math.floor(i/2)*32}%;width:40%;">`).join(''):'<p>Select photos above to preview and edit before saving.</p>'; }
  function renderPages661(){ const box=$('scrapbookPages'); if(!box)return; box.innerHTML=(data.pages||[]).map(p=>{const photos=p.photos||[]; return `<div class="scrapPage661 card" id="page-${p.id}"><h3>${esc(p.title||'Scrapbook Page')}</h3><div class="scrapCanvas661">${photos.map((src,i)=>`<img class="scrapPhoto661" src="${src}" style="left:${6+(i%2)*46}%;top:${8+Math.floor(i/2)*30}%;width:42%;">`).join('')}${(p.stickers||[]).map(s=>`<div class="sticker661" data-page="${p.id}" data-id="${s.id}" style="left:${s.x||50}px;top:${s.y||50}px;font-size:${s.size||42}px">${esc(s.text||'💗')}<span class="resize661">↘</span></div>`).join('')}</div>${p.note?`<p>${esc(p.note)}</p>`:''}<div class="scrapTools noPrint"><button onclick="addSticker661('${p.id}')" class="secondary">Add Sticker</button><button onclick="downloadPage661('${p.id}')" class="secondary">Download / Print</button><button onclick="del('pages','${p.id}')" class="secondary">Delete</button></div></div>`}).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>'; bindStickers661(); renderDraft661(); }
  window.renderPages=renderPages661;
  window.addSticker661=function(pid){ const p=data.pages.find(x=>x.id===pid); if(!p)return; p.stickers=p.stickers||[]; p.stickers.push({id:uid(),text:prompt('Sticker emoji or word','💗')||'💗',x:60,y:60,size:44}); saveNow(); renderPages661(); };
  window.downloadPage661=function(pid){ const el=$(`page-${pid}`); if(!el)return; el.scrollIntoView(); setTimeout(()=>window.print(),100); };
  function bindStickers661(){ $$('.sticker661').forEach(el=>{ let drag=false, resize=false, sx=0, sy=0, sl=0, st=0, ss=0; const move=e=>{if(!drag&&!resize)return; e.preventDefault(); const t=e.touches?e.touches[0]:e; const p=data.pages.find(x=>x.id===el.dataset.page), s=p?.stickers?.find(x=>x.id===el.dataset.id); if(!s)return; if(resize){s.size=Math.max(20,ss+(t.clientX-sx)/2); el.style.fontSize=s.size+'px';} else {s.x=sl+(t.clientX-sx); s.y=st+(t.clientY-sy); el.style.left=s.x+'px'; el.style.top=s.y+'px';}}; const up=()=>{if(drag||resize)saveNow(); drag=false; resize=false; window.removeEventListener('mousemove',move); window.removeEventListener('touchmove',move);}; el.onmousedown=el.ontouchstart=e=>{const t=e.touches?e.touches[0]:e; resize=e.target.classList.contains('resize661'); drag=!resize; sx=t.clientX; sy=t.clientY; sl=parseFloat(el.style.left)||0; st=parseFloat(el.style.top)||0; ss=parseFloat(el.style.fontSize)||42; window.addEventListener('mousemove',move); window.addEventListener('touchmove',move,{passive:false}); window.addEventListener('mouseup',up,{once:true}); window.addEventListener('touchend',up,{once:true});}; }); }

  function patchPeople(){ const b=$('savePerson'); if(b&&!b.dataset.v661){ const old=b.onclick; b.dataset.v661='1'; b.onclick=async function(ev){ev&&ev.preventDefault(); const email=($('personEmail')?.value||'').toLowerCase().trim(), phone=String($('personPhone')?.value||'').replace(/\D/g,''); const found=data.people.find(p=>(email&&String(p.email||'').toLowerCase().trim()===email)||(phone&&String(p.phone||'').replace(/\D/g,'')===phone)); if(found){found.name=$('personName')?.value||found.name; found.birthday=$('personBirthday')?.value||found.birthday; found.email=email||found.email; found.phone=$('personPhone')?.value||found.phone; found.role=$('personRole')?.value||found.role; dedupeAll(); saveNow(); render(); toastMsg('Existing person updated instead of duplicated'); return;} if(old) await old.call(this,ev); dedupeAll(); saveNow(); render(); }; } }

  const oldRender=window.render;
  window.render=function(){ dedupeAll(); try{oldRender&&oldRender();}catch(e){console.warn(e)} patchTripDates(); enhanceMealUI(); patchSaveLink(); try{renderTravel()}catch{}; try{renderMeals()}catch{}; try{renderPages661()}catch{}; patchPeople(); };
  document.addEventListener('DOMContentLoaded',()=>{fixButtonsNoRefresh(); setTimeout(()=>{try{render()}catch(e){console.warn(e)}},700);});
  setTimeout(()=>{try{render()}catch(e){console.warn(e)}},1300);
})();
