/* Our Family Adventures 6.6.4 — hard fix for travel links, meals, memories, scrapbook controls, and mobile scrolling */
(function(){
  'use strict';
  window.OFA_VERSION='6.6.4';
  const $=id=>document.getElementById(id);
  const $$=sel=>Array.from(document.querySelectorAll(sel));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const now=()=>new Date().toISOString();
  const me=()=>{try{return data?.profile?.name||firebase?.auth?.().currentUser?.displayName||firebase?.auth?.().currentUser?.email||localStorage.getItem('ofa_family_user')||'Me'}catch{return 'Me'}};
  const toastMsg=m=>{try{typeof toast==='function'?toast(m):console.log(m)}catch{console.log(m)}};
  function ensure(){ if(!window.data)return false; ['people','trips','memories','pages','links','meals','groceries','packing','pins','chat','activity'].forEach(k=>{if(!Array.isArray(data[k]))data[k]=[]}); data.trips.forEach(t=>{if(!Array.isArray(t.tripLinks))t.tripLinks=[]; if(!Array.isArray(t.voteOptions))t.voteOptions=[]}); return true; }
  function saveNow(){ try{ if(typeof normalizeData==='function')normalizeData(); }catch{} try{localStorage.setItem('ofaDataFinalV4',JSON.stringify(data));localStorage.setItem('ofaData',JSON.stringify(data));}catch{} try{ if(typeof queueFirebaseSave==='function')queueFirebaseSave(); else if(typeof pushFirebaseData==='function')pushFirebaseData(); else if(typeof save==='function')save(); }catch(e){console.warn(e)} }
  function normUrl(u){u=String(u||'').trim(); if(!u)return ''; if(!/^https?:\/\//i.test(u))u='https://'+u; return u;}
  function cleanKey(s){return String(s||'').trim().toLowerCase().replace(/\/$/,'')}
  function linkKey(l){return [cleanKey(l.url),cleanKey(l.title),cleanKey(l.tripId||l.trip)].join('|')}
  function allLinks(){ensure(); const map=new Map(); (data.links||[]).forEach(l=>{if(l&&l.url)map.set(linkKey(l),l)}); (data.trips||[]).forEach(t=>(t.tripLinks||[]).forEach(l=>{if(l&&l.url){const x={...l,tripId:l.tripId||t.id,trip:l.trip||t.name};map.set(linkKey(x),x)}})); return [...map.values()];}
  function dedupeLinks(){ensure(); const arr=allLinks(); const map=new Map(); arr.forEach(l=>map.set(linkKey(l),l)); data.links=[...map.values()]; data.trips.forEach(t=>{const tm=new Map(); data.links.filter(l=>l.tripId===t.id||l.trip===t.name).forEach(l=>tm.set(linkKey(l),l)); t.tripLinks=[...tm.values()];});}
  function addLinkToTrip(tripId,title,url){ensure(); const t=data.trips.find(x=>x.id===tripId||x.name===tripId); const link={id:uid(),title:(title||'Travel link').trim(),url:normUrl(url),trip:t?.name||'General',tripId:t?.id||'',createdAt:now(),addedBy:me()}; if(!link.url){toastMsg('Add the travel link first.'); return;} data.links.push(link); if(t){t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link);} dedupeLinks(); saveNow(); renderTravel(); try{renderTrips()}catch{} toastMsg('Travel link saved');}
  window.addTripLink=function(tripId){addLinkToTrip(tripId,$(`tripLinkTitle-${tripId}`)?.value,$(`tripLinkUrl-${tripId}`)?.value); if($(`tripLinkTitle-${tripId}`))$(`tripLinkTitle-${tripId}`).value=''; if($(`tripLinkUrl-${tripId}`))$(`tripLinkUrl-${tripId}`).value='';};
  window.removeTravelLink664=function(id){ensure(); data.links=data.links.filter(l=>l.id!==id); data.trips.forEach(t=>t.tripLinks=(t.tripLinks||[]).filter(l=>l.id!==id)); saveNow(); renderTravel(); try{renderTrips()}catch{}};
  window.tripLinkRows=function(t){dedupeLinks(); const arr=allLinks().filter(l=>l.tripId===t.id||l.trip===t.name); return arr.length?`<div class="tripLinks">${arr.map(l=>`<div class="linkRow"><a href="${esc(normUrl(l.url))}" target="_blank" rel="noopener">${esc(l.title||'Travel link')}</a><button type="button" onclick="removeTravelLink664('${l.id}')" class="secondary smallBtn">Remove</button></div>`).join('')}</div>`:'<p class="helperText">No travel links saved yet.</p>';};
  window.renderTravel=function(){const box=$('travelList'); if(!box)return; dedupeLinks(); const arr=allLinks(); box.innerHTML=`<div class="card formCard travelForm664"><h3>Add Travel Link</h3><label>Title<input id="linkTitle664" placeholder="Lost trails, hotel, restaurant, reservation..." value="${esc($('linkTitle664')?.value||'')}"></label><label>Adventure<select id="linkTrip664">${(data.trips||[]).map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}<option value="General">General</option></select></label><label>Link<input id="linkUrl664" placeholder="website.com or https://..." value="${esc($('linkUrl664')?.value||'')}"></label><button type="button" id="saveLink664" class="primary">Save Travel Link</button></div>`+(arr.length?arr.map(l=>`<div class="item"><h3>${esc(l.title||'Travel link')}</h3><p>${esc(l.trip||'General')}</p><a href="${esc(normUrl(l.url))}" target="_blank" rel="noopener">Open link</a><br><button type="button" onclick="removeTravelLink664('${l.id}')" class="secondary">Delete</button></div>`).join(''):'<div class="card"><p>No travel links yet.</p></div>'); const b=$('saveLink664'); if(b)b.onclick=()=>{addLinkToTrip($('linkTrip664')?.value,$('linkTitle664')?.value,$('linkUrl664')?.value);};};
  function tripCard(t){const place=t.address||t.tripAddress||t.destination||''; return `<div class="item tripCard"><h3>${esc(t.name)}</h3><p>${esc(place)} ${t.start?`• ${esc(t.start)} to ${esc(t.end||'')}`:''}</p><div class="itemActions"><button type="button" onclick="editTrip&&editTrip('${t.id}')" class="primary">Edit Trip</button><button type="button" onclick="openTripMap&&openTripMap('${t.id}')" class="secondary">Open Directions</button><button type="button" onclick="refreshTripWeather&&refreshTripWeather('${t.id}')" class="secondary">Refresh Live Weather</button><button type="button" onclick="del&&del('trips','${t.id}')" class="secondary">Delete</button></div><p class="weatherBox">${esc(t.weather||'No live weather loaded yet.')}</p><div class="linkBox"><h4>Travel Links</h4>${tripLinkRows(t)}<input id="tripLinkTitle-${t.id}" placeholder="Link title"><input id="tripLinkUrl-${t.id}" placeholder="website.com or https://..."><button type="button" onclick="addTripLink('${t.id}')" class="secondary">Add Travel Link</button></div><div class="voteBox"><h4>Family Voting</h4>${(t.voteOptions||[]).map((v,i)=>`<div class="voteRow"><span>${esc(v.text||'Option')}</span><strong>${Object.keys(v.votes||{}).length} vote(s)</strong><button type="button" onclick="voteTrip&&voteTrip('${t.id}',${i})" class="secondary">Vote</button></div>`).join('')||'<p>No voting options yet.</p>'}<textarea id="voteInput-${t.id}" placeholder="Add choices, one per line"></textarea><textarea id="voteLinks-${t.id}" placeholder="Optional links, one per line"></textarea><button type="button" onclick="addVoteOptionsBulk&&addVoteOptionsBulk('${t.id}')" class="secondary">Add Voting Option(s)</button></div></div>`}
  window.renderTrips=function(){const box=$('tripList'); if(!box)return; ensure(); dedupeLinks(); box.innerHTML=(data.trips||[]).map(tripCard).join('')||'<div class="card"><p>No trips added yet.</p></div>';};
  document.addEventListener('click',function(e){const b=e.target.closest('button'); if(!b)return; const txt=(b.textContent||'').trim().toLowerCase(); if(txt==='add travel link'){const wrap=b.closest('.linkBox'); if(wrap){e.preventDefault(); e.stopImmediatePropagation(); const id=(wrap.querySelector('input[id^="tripLinkUrl-"]')?.id||'').replace('tripLinkUrl-',''); if(id)window.addTripLink(id);}} if(txt==='save link'||txt==='save travel link'){e.preventDefault(); e.stopImmediatePropagation(); addLinkToTrip($('linkTrip664')?.value||$('linkTrip')?.value,$('linkTitle664')?.value||$('linkTitle')?.value,$('linkUrl664')?.value||$('linkUrl')?.value);}},true);
  function prettyDate(d){if(!d)return ''; const x=new Date(String(d).slice(0,10)+'T12:00:00'); return isNaN(x)?String(d):x.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});}
  function dateRange(start,end){const out=[]; if(!start)return out; const s=new Date(start+'T12:00:00'), e=new Date((end||start)+'T12:00:00'); if(isNaN(s)||isNaN(e))return out; for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1)){out.push(d.toISOString().slice(0,10)); if(out.length>31)break} return out;}
  function mealTypes(i,total){return total>1&&i===0?['Lunch','Dinner','Snack']:total>1&&i===total-1?['Breakfast','Lunch']:['Breakfast','Lunch','Dinner','Snack'];}
  function fillMealDropdowns(){const t=data.trips.find(x=>x.id===$('mealTrip')?.value||x.name===$('mealTrip')?.value)||data.trips[0]; const dates=t?dateRange(t.start,t.end):[]; const ds=$('mealDate664'), ms=$('mealType664'); if(ds)ds.innerHTML=dates.map(d=>`<option value="${d}">${esc(prettyDate(d))}</option>`).join('')||'<option value="">Add trip dates first</option>'; if(ms){const d=ds?.value; const idx=Math.max(0,dates.indexOf(d)); ms.innerHTML=(dates.length?mealTypes(idx,dates.length):['Breakfast','Lunch','Dinner','Snack']).map(m=>`<option>${m}</option>`).join('');}}
  function ensureMealForm(){const form=$('meals')?.querySelector('.formCard'); if(!form||$('mealDate664'))return; const title=$('mealTitle')?.closest('label'); if(title)title.style.display='none'; title?.insertAdjacentHTML('afterend',`<div class="twoCols"><label>Date<select id="mealDate664"></select></label><label>Meal<select id="mealType664"></select></label></div><label>Meal list<select id="mealScope664"><option value="group">Group meal list</option><option value="private">My private meal list</option></select></label>`); $('mealTrip')?.addEventListener('change',fillMealDropdowns); $('mealDate664')?.addEventListener('change',fillMealDropdowns); const b=$('saveMeal'); if(b)b.onclick=function(ev){ev&&ev.preventDefault(); const tripVal=$('mealTrip')?.value||'General'; const t=data.trips.find(x=>x.id===tripVal||x.name===tripVal); const m={id:uid(),trip:t?.name||tripVal,tripId:t?.id||'',date:$('mealDate664')?.value||'',mealDate:$('mealDate664')?.value||'',mealType:$('mealType664')?.value||'Meal',title:$('mealType664')?.value||'Meal',scope:$('mealScope664')?.value||'group',private:($('mealScope664')?.value==='private'),item:($('mealItem')?.value||'').trim()||$('mealType664')?.value||'Meal',person:($('mealPerson')?.value||'').trim()||'Volunteer needed',owner:me(),createdAt:now()}; data.meals.push(m); if($('mealItem'))$('mealItem').value=''; if($('mealPerson'))$('mealPerson').value=''; saveNow(); renderMeals(); toastMsg('Meal saved');}; fillMealDropdowns();}
  function rowMeal(m){return `<div class="item"><b>${esc(prettyDate(m.date||m.mealDate))} ${esc(m.mealType||m.title||'Meal')}</b><br>${esc(m.item||'Meal item')}<br><small>${esc(m.person||'Volunteer needed')} • ${esc(m.trip||'General')}</small><button type="button" onclick="deleteMeal664('${m.id}')" class="secondary smallBtn">Delete</button></div>`}
  window.deleteMeal664=id=>{data.meals=data.meals.filter(m=>m.id!==id); saveNow(); renderMeals();};
  window.renderMeals=function(){const box=$('mealList'); if(!box)return; ensure(); ensureMealForm(); const mine=me(); const group=data.meals.filter(m=>m.scope!=='private'&&!m.private); const priv=data.meals.filter(m=>m.scope==='private'||m.private||m.owner===mine); const t=data.trips.find(x=>x.id===$('mealTrip')?.value||x.name===$('mealTrip')?.value)||data.trips[0]; const dates=t?dateRange(t.start,t.end):[]; const calendar=dates.length?`<div class="card mealDateCards664"><h3>Meals by Trip Date</h3>${dates.map((d,i)=>`<div class="mealDayCard"><h3>${esc(prettyDate(d))}</h3>${mealTypes(i,dates.length).map(mt=>`<div class="mealSlot664"><b>${mt}</b><button type="button" onclick="document.getElementById('mealDate664').value='${d}';fillMealDropdowns664&&fillMealDropdowns664();document.getElementById('mealType664').value='${mt}';document.getElementById('mealItem').focus();" class="secondary smallBtn">Add</button></div>`).join('')}</div>`).join('')}</div>`:''; box.innerHTML=calendar+`<div class="card"><h3>Group Meal List</h3>${group.map(rowMeal).join('')||'<p>No group meals yet.</p>'}</div><div class="card"><h3>My Private Meal List</h3>${priv.map(rowMeal).join('')||'<p>No private meals yet.</p>'}</div>`;}; window.fillMealDropdowns664=fillMealDropdowns;
  function mediaList(){const out=[]; (data.memories||[]).forEach(m=>(m.media||[]).forEach((mm,i)=>{const src=mm.src||mm.url||mm.dataUrl||mm; if(src)out.push({id:mm.id||`${m.id}-${i}`,src,title:m.title||'Memory',memoryId:m.id})})); return out;}
  window.renderMemories=function(){const box=$('memoryGrid'); if(!box)return; const sorted=[...(data.memories||[])].sort((a,b)=>String(b.date||b.createdAt||'').localeCompare(String(a.date||a.createdAt||''))); box.innerHTML=sorted.map(m=>`<div class="memory journal"><div class="journalMeta">${esc(m.uploader||'')} • ${esc(m.trip||'')} • ${esc(m.date||'')}</div><h3>${esc(m.title||'Memory')}</h3><div class="mediaGrid">${(m.media||[]).map(mm=>{const src=mm.src||mm.url||mm.dataUrl||mm; return String(src).startsWith('data:video')?`<video controls src="${src}"></video>`:`<img src="${src}" alt="memory">`}).join('')}</div><p>${esc(m.caption||'')}</p><div class="memoryActions"><button type="button" onclick="addMemoryToBook&&addMemoryToBook('${m.id}')" class="secondary">Add photos to scrapbook</button><button type="button" onclick="editMemory664('${m.id}')" class="secondary">Edit</button><button type="button" onclick="downloadMemory664('${m.id}')" class="secondary">Download / Print</button><button type="button" onclick="del&&del('memories','${m.id}')" class="secondary">Delete</button></div></div>`).join('')||'<div class="card"><p>No memories yet.</p></div>'; try{renderScrapbookChoices()}catch{}};
  window.editMemory664=id=>{const m=data.memories.find(x=>x.id===id); if(!m)return; const title=prompt('Memory title',m.title||''); if(title===null)return; const caption=prompt('Journal entry',m.caption||''); m.title=title; if(caption!==null)m.caption=caption; saveNow(); renderMemories();}; window.downloadMemory664=id=>{const m=data.memories.find(x=>x.id===id); if(!m)return; window.print();};
  function enhanceScrapControls(){const sec=$('scrapbook'); if(!sec||$('scrapControls664'))return; const form=sec.querySelector('.formCard'); if(form){form.insertAdjacentHTML('beforeend',`<div id="scrapControls664" class="card"><h3>Frames / Cutouts</h3><div id="frameChips664" class="chipScroller"></div><h3>Stickers & Extras</h3><div id="stickerChips664" class="chipScroller"></div></div>`);} const frames=['soft','polaroid','circle','heart','scallop','postcard','ticket','torn','gold','none']; const stickers=['📷','💕','❤️','💛','💙','⭐','✨','☀️','🌊','🐚','🏖️','🧭','✈️','📍','🎣','🍔','🔥','🎆']; $('frameChips664').innerHTML=frames.map(f=>`<button type="button" class="scrapChip" onclick="selectFrame664('${f}')">${f}</button>`).join(''); $('stickerChips664').innerHTML=stickers.map(s=>`<button type="button" class="scrapChip" onclick="addDraftSticker664('${s}')">${s}</button>`).join('');}
  window.selectFrame664=f=>{if($('pageFrame'))$('pageFrame').value=f; $$('.scrapChip').forEach(c=>c.classList.toggle('selected',c.textContent.trim()===f)); renderDraft664();};
  let draftStickers=[];
  function selectedIds(){try{return window.selectedScrapPhotos||selectedScrapPhotos||[]}catch{return []}}
  function selectedPhotos(){const ids=selectedIds(); return mediaList().filter(x=>ids.includes(x.id));}
  window.addDraftSticker664=s=>{draftStickers.push({id:uid(),text:s,x:40+draftStickers.length*30,y:360,size:52}); renderDraft664();};
  function frameClass(){return 'frame-'+($('pageFrame')?.value||'soft')}
  window.renderDraft664=function(){enhanceScrapControls(); let box=$('draftPage664'); const host=$('scrapbookPhotoPicker')||$('scrapbookPages')?.parentElement; if(!host)return; if(!box){host.insertAdjacentHTML('afterend',`<div id="draftPage664" class="card"><h3>Draft Scrapbook Page</h3><div id="draftCanvas664" class="draftCanvas664"></div><div class="scrapTools noPrint"><button type="button" id="saveDraft664" class="primary">Save Scrapbook Page</button><button type="button" id="clearDraft664" class="secondary">Clear Draft</button></div></div>`); box=$('draftPage664'); $('clearDraft664').onclick=()=>{draftStickers=[]; try{window.selectedScrapPhotos=[]; selectedScrapPhotos=[]}catch{} renderDraft664();}; $('saveDraft664').onclick=()=>{const photos=selectedPhotos().map(p=>p.src); const page={id:uid(),title:$('pageTitle')?.value||'Scrapbook Page',note:$('pageNote')?.value||'',frame:$('pageFrame')?.value||'soft',theme:$('pageBg')?.value||$('pageTheme')?.value||'Rose Gold',photos,stickers:draftStickers,createdAt:now()}; data.pages.push(page); draftStickers=[]; try{window.selectedScrapPhotos=[]; selectedScrapPhotos=[]}catch{} saveNow(); renderPages(); toastMsg('Scrapbook page saved');};}
    const photos=selectedPhotos(); $('draftCanvas664').innerHTML=(photos.length?photos.map((p,i)=>`<img class="draftPhoto664 ${frameClass()}" src="${p.src}" style="left:${8+(i%2)*44}%;top:${20+Math.floor(i/2)*34}%;width:40%">`).join(''):'<p>Select memory photos above, then choose frames and stickers before saving.</p>')+draftStickers.map(s=>`<div class="sticker664" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${esc(s.text)}<span class="resize664">↘</span></div>`).join(''); bindDrag664(); };
  window.renderPages=function(){const box=$('scrapbookPages'); if(!box)return; ensure(); box.innerHTML=(data.pages||[]).map(p=>`<div class="scrapPage664 card" id="page-${p.id}"><h3>${esc(p.title||'Scrapbook Page')}</h3><div class="scrapCanvas664">${(p.photos||[]).map((src,i)=>`<img class="scrapPhoto664 frame-${esc(p.frame||'soft')}" src="${src}" style="left:${6+(i%2)*46}%;top:${18+Math.floor(i/2)*32}%;width:42%">`).join('')}${(p.stickers||[]).map(s=>`<div class="sticker664" data-page="${p.id}" data-id="${s.id}" style="left:${s.x||50}px;top:${s.y||360}px;font-size:${s.size||52}px">${esc(s.text||'❤️')}<span class="resize664">↘</span></div>`).join('')}</div><p>${esc(p.note||'')}</p><div class="scrapTools noPrint"><button type="button" onclick="editPage664('${p.id}')" class="secondary">Edit</button><button type="button" onclick="addPageSticker664('${p.id}')" class="secondary">Add Sticker</button><button type="button" onclick="window.print()" class="secondary">Download / Print</button><button type="button" onclick="del&&del('pages','${p.id}')" class="secondary">Delete</button></div></div>`).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>'; bindDrag664(); renderDraft664();};
  window.editPage664=id=>{const p=data.pages.find(x=>x.id===id); if(!p)return; const title=prompt('Page title',p.title||''); if(title!==null)p.title=title; const note=prompt('Page note',p.note||''); if(note!==null)p.note=note; saveNow(); renderPages();}; window.addPageSticker664=id=>{const p=data.pages.find(x=>x.id===id); if(!p)return; p.stickers=p.stickers||[]; p.stickers.push({id:uid(),text:prompt('Sticker','❤️')||'❤️',x:70,y:360,size:52}); saveNow(); renderPages();};
  function bindDrag664(){ $$('.sticker664').forEach(el=>{if(el.dataset.bound664)return; el.dataset.bound664='1'; let drag=false,resize=false,sx=0,sy=0,sl=0,st=0,ss=0; const move=e=>{if(!drag&&!resize)return; e.preventDefault(); const t=e.touches?e.touches[0]:e; if(resize){el.style.fontSize=Math.max(20,ss+(t.clientX-sx)/2)+'px';}else{el.style.left=sl+(t.clientX-sx)+'px'; el.style.top=st+(t.clientY-sy)+'px';}}; const up=()=>{drag=false;resize=false; window.removeEventListener('mousemove',move); window.removeEventListener('touchmove',move);}; el.addEventListener('mousedown',down); el.addEventListener('touchstart',down,{passive:false}); function down(e){e.preventDefault(); const t=e.touches?e.touches[0]:e; resize=e.target.classList.contains('resize664'); drag=!resize; sx=t.clientX; sy=t.clientY; sl=parseFloat(el.style.left)||0; st=parseFloat(el.style.top)||0; ss=parseFloat(el.style.fontSize)||52; window.addEventListener('mousemove',move); window.addEventListener('touchmove',move,{passive:false}); window.addEventListener('mouseup',up,{once:true}); window.addEventListener('touchend',up,{once:true});}}); }
  const oldRender=window.render;
  window.render=function(){ensure(); try{oldRender&&oldRender()}catch(e){console.warn(e)} try{renderTrips()}catch{} try{renderTravel()}catch{} try{renderMeals()}catch{} try{renderMemories()}catch{} try{renderPages()}catch{} };
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{try{render()}catch(e){console.warn(e)}},600)); setTimeout(()=>{try{render()}catch(e){console.warn(e)}},1500);
})();
