/* Our Family Adventures 7.1.1 — corrective save/sync/mobile editor patch */
(function(){
  'use strict';
  const VERSION='7.1.1';
  const FAMILY_ID='our-family-adventures';
  const DATA_PATH=`families/${FAMILY_ID}/data`;
  const $=id=>document.getElementById(id);
  const $$=s=>Array.from(document.querySelectorAll(s));
  const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const now=()=>new Date().toISOString();
  const msg=m=>{try{window.toast?window.toast(m):console.log(m)}catch{console.log(m)}};
  const me=()=>{try{return data.profile?.name||localStorage.getItem('ofa_family_user')||firebase?.auth?.().currentUser?.displayName||firebase?.auth?.().currentUser?.email||'Family member'}catch{return 'Family member'}};
  const norm=s=>String(s||'').trim().toLowerCase();
  const url=u=>{u=String(u||'').trim(); if(!u)return ''; return /^https?:\/\//i.test(u)?u:'https://'+u};
  let remoteStarted=false, applying=false, cropState={photos:[],stickers:[],texts:[],frame:'soft',bg:'seaGlass'};
  function ensure(){window.data=window.data||{}; ['people','trips','memories','pages','links','meals','groceries','packing','pins','chat','activity','notifications','invites'].forEach(k=>{if(!Array.isArray(data[k]))data[k]=[]}); data.profile=data.profile||{}; data.settings=data.settings||{}; data.settings.familyId=FAMILY_ID; return data;}
  function db(){try{return firebase?.apps?.length&&firebase.database?firebase.database():null}catch{return null}}
  function localSave(){ensure(); try{localStorage.setItem('ofaDataFinalV4',JSON.stringify(data)); localStorage.setItem('ofaData',JSON.stringify(data));}catch(e){console.warn(e)}}
  function dedupeAll(){ensure(); const linkMap=new Map(); const key=l=>[norm(l.title),url(l.url).replace(/\/$/,''),norm(l.tripId||l.trip)].join('|'); [...(data.links||[]),...(data.trips||[]).flatMap(t=>(t.tripLinks||[]).map(l=>({...l,tripId:l.tripId||t.id,trip:l.trip||t.name})))].forEach(l=>{if(l&&l.url)linkMap.set(key(l),l)}); data.links=[...linkMap.values()]; data.trips.forEach(t=>{t.tripLinks=data.links.filter(l=>l.tripId===t.id||l.trip===t.name); const voteMap=new Map(); (t.voteOptions||[]).forEach(v=>{const k=[norm(v.text),url(v.link||v.url).replace(/\/$/,'')].join('|'); if(k!=='|')voteMap.set(k,{...v,votes:v.votes||{}})}); t.voteOptions=[...voteMap.values()];});}
  function save(reason){ensure(); dedupeAll(); data.__meta={version:VERSION,updatedAt:now(),updatedBy:me(),reason:reason||'save'}; localSave(); if(!applying){const r=db(); if(r)r.ref(DATA_PATH).set(JSON.parse(JSON.stringify(data))).then(()=>setSync('Live sync on')).catch(e=>{console.warn(e); setSync('Could not load shared family data - check Realtime Database rules')});} setTimeout(renderAll,50);}
  window.OFA711Save=save;
  function setSync(t){let el=$('syncPill71'); if(!el){document.body.insertAdjacentHTML('beforeend','<div id="syncPill71" class="syncPill ok"></div>'); el=$('syncPill71')} el.textContent=t;}
  function startRemote(){if(remoteStarted)return; remoteStarted=true; const r=db(); if(!r){setSync('Firebase Realtime Database not connected'); return;} r.ref(DATA_PATH).on('value',snap=>{const val=snap.val(); if(!val){save('seed shared family data'); return;} applying=true; Object.keys(data).forEach(k=>delete data[k]); Object.assign(data,val); ensure(); localSave(); applying=false; setSync('Live sync on'); renderAll();},e=>{console.warn(e); setSync('Could not load shared family data - check Realtime Database rules')});}
  function isAdmin(){ensure(); const u=firebase?.auth?.().currentUser; const email=norm(u?.email||data.profile.email||''); const name=norm(data.profile.name||''); if(data.profile.admin===true||norm(data.profile.role)==='admin')return true; return (data.people||[]).some(p=>norm(p.role)==='admin'&&(norm(p.email)===email||norm(p.name)===name));}
  window.OFA711IsAdmin=isAdmin;
  function members(){ensure(); const names=[...new Set(['Volunteer needed','Me / I will bring it',me(),...data.people.map(p=>p.name).filter(Boolean)])]; return names;}
  function tripOptions(sel){ensure(); return (data.trips||[]).map(t=>`<option value="${E(t.id)}" ${sel===t.id||sel===t.name?'selected':''}>${E(t.name||'Trip')}</option>`).join('')+'<option value="General">General</option>';}
  function memberOptions(sel){return members().map(n=>`<option ${n===sel?'selected':''}>${E(n)}</option>`).join('')}
  function tripBy(v){return (data.trips||[]).find(t=>t.id===v||t.name===v)||data.trips[0]||null}
  function placeOf(t){return t?.address||t?.tripAddress||t?.destination||t?.location||t?.name||''}
  function mapSearch(q){return `https://www.google.com/maps/search/${encodeURIComponent(q)}`}
  function gmapEmbed(q){return `https://www.google.com/maps?q=${encodeURIComponent(q||'United States')}&output=embed`}
  function weatherLink(q){return `https://weather.com/weather/today/l/${encodeURIComponent(q||'')}`}
  function cardSearch(t){const place=placeOf(t); return `<div class="card tripSearch711"><h3>Search Near This Trip</h3><p>${E(place||'Add a destination/address first.')}</p><div class="quickSearchGrid"><a class="secondary" target="_blank" href="${mapSearch('restaurants near '+place)}">Restaurants</a><a class="secondary" target="_blank" href="${mapSearch('grocery stores near '+place)}">Grocery Stores</a><a class="secondary" target="_blank" href="${mapSearch('gas stations near '+place)}">Gas Stations</a><a class="secondary" target="_blank" href="${mapSearch('hospitals near '+place)}">Hospitals</a><a class="secondary" target="_blank" href="${mapSearch('hotels near '+place)}">Hotels</a></div></div>`;}
  function cleanOldSearch(){const heads=$$('h3').filter(h=>/Search Near This Trip/i.test(h.textContent||'')); heads.forEach(h=>{const c=h.closest('.card'); if(c&&!c.classList.contains('tripSearch711'))c.style.display='none';});}
  function renderTrips(){const box=$('tripList'); if(!box)return; ensure(); dedupeAll(); box.innerHTML=(data.trips||[]).map(t=>{const links=(data.links||[]).filter(l=>l.tripId===t.id||l.trip===t.name); return `<div class="item tripCard"><h3>${E(t.name||'Trip')}</h3><p>${E(placeOf(t))} ${t.start?`• ${E(t.start)} to ${E(t.end||'')}`:''}</p><div class="mapBox"><iframe loading="lazy" src="${gmapEmbed(placeOf(t))}"></iframe></div><div class="weatherLiveCard"><b>Live Weather</b><p>Weather Channel may open outside the app on phones if it blocks embedding.</p><a class="secondary" target="_blank" href="${weatherLink(placeOf(t))}">Open Weather Channel forecast</a></div>${cardSearch(t)}<div class="linkBox"><h4>Travel Links</h4>${links.map(l=>`<div class="linkRow"><a target="_blank" href="${E(url(l.url))}">${E(l.title||l.url)}</a><button type="button" class="secondary smallBtn" data-del-link="${l.id}">Remove</button></div>`).join('')||'<p>No travel links saved yet.</p>'}<input id="tripLinkTitle-${t.id}" placeholder="Link title"><input id="tripLinkUrl-${t.id}" placeholder="website.com or https://..."><button type="button" class="secondary" data-add-link="${t.id}">Add travel link</button></div><div class="voteBox"><h4>Family Voting</h4>${(t.voteOptions||[]).map((v,i)=>`<div class="voteRow"><div><b>${E(v.text||'Option')}</b>${v.link?`<br><a target="_blank" href="${E(url(v.link))}">Open link</a>`:''}</div><strong>${Object.keys(v.votes||{}).length} vote(s)</strong><button type="button" class="secondary smallBtn" data-vote="${t.id}|${i}">Vote</button>${isAdmin()?`<button type="button" class="secondary smallBtn" data-del-vote="${t.id}|${i}">Remove</button>`:''}</div>`).join('')||'<p>No voting options yet. Add options below.</p>'}<textarea id="voteInput-${t.id}" placeholder="Add choices, one per line"></textarea><textarea id="voteLink-${t.id}" placeholder="Optional links, one per line"></textarea><button type="button" class="secondary" data-add-vote="${t.id}">Add voting option(s)</button></div><div class="itemActions"><button class="primary" type="button" data-open-trip="${t.id}">Open Trip Page</button><button class="secondary" type="button" onclick="editTrip&&editTrip('${t.id}')">Edit</button><button class="secondary" type="button" onclick="del&&del('trips','${t.id}')">Delete</button></div></div>`}).join('')||'<div class="card"><p>No trips added yet.</p></div>';}
  function addTravelLink(tripId,title,urlVal){const t=tripBy(tripId); const u=url(urlVal); if(!u)return msg('Add the travel link first.'); const link={id:id(),tripId:t?.id||'',trip:t?.name||'General',title:(title||'Travel link').trim(),url:u,createdAt:now(),addedBy:me()}; data.links.push(link); if(t){t.tripLinks=t.tripLinks||[]; t.tripLinks.push(link)} save('travel link saved'); ['linkTitle','linkUrl','linkTitle664','linkUrl664',`tripLinkTitle-${tripId}`,`tripLinkUrl-${tripId}`].forEach(x=>{if($(x))$(x).value=''}); msg('Travel link saved');}
  function addVote(tripId){const t=tripBy(tripId); if(!t)return; const opts=($(`voteInput-${tripId}`)?.value||'').split(/[\n,]+/).map(s=>s.trim()).filter(Boolean); const links=($(`voteLink-${tripId}`)?.value||$(`voteLinks-${tripId}`)?.value||'').split(/[\n,]+/).map(s=>s.trim()).filter(Boolean); const n=Math.max(opts.length,links.length); if(!n)return msg('Add a voting title or link first.'); t.voteOptions=t.voteOptions||[]; for(let i=0;i<n;i++)t.voteOptions.push({id:id(),text:opts[i]||links[i]||`Option ${i+1}`,link:links[i]||(/^https?:/i.test(opts[i]||'')?opts[i]:''),votes:{},createdAt:now()}); if($(`voteInput-${tripId}`))$(`voteInput-${tripId}`).value=''; if($(`voteLink-${tripId}`))$(`voteLink-${tripId}`).value=''; if($(`voteLinks-${tripId}`))$(`voteLinks-${tripId}`).value=''; save('vote option added');}
  function renderTravel(){const box=$('travelList'); if(!box)return; dedupeAll(); box.innerHTML=`<div class="card formCard"><h3>Add Travel Link</h3><label>Title<input id="linkTitle711" placeholder="Lost Trails, hotel, restaurant, reservation..."></label><label>Adventure<select id="linkTrip711">${tripOptions()}</select></label><label>Link<input id="linkUrl711" placeholder="website.com or https://..."></label><button type="button" id="saveLink711" class="primary">Save Travel Link</button></div>`+(data.links.map(l=>`<div class="item"><h3><a target="_blank" href="${E(url(l.url))}">${E(l.title||'Travel link')}</a></h3><p>${E(l.trip||'General')}</p><button type="button" class="secondary" data-del-link="${l.id}">Remove</button></div>`).join('')||'<div class="card"><p>No travel links yet.</p></div>'); const b=$('saveLink711'); if(b)b.onclick=()=>addTravelLink($('linkTrip711').value,$('linkTitle711').value,$('linkUrl711').value);}
  function row(list,x,title,sub){return `<div class="item checklistItem"><label class="checkLine"><input type="checkbox" ${x.done?'checked':''} data-toggle="${list}|${x.id}"><span><b>${E(title)}</b><small>${E(sub||'')}</small></span></label><p class="helperText">${x.private?'Private':'Group'} • Assigned: ${E(x.assignedTo||x.person||'Volunteer needed')}</p><button type="button" class="secondary smallBtn" data-del-item="${list}|${x.id}">Delete</button></div>`}
  function dateRange(s,e){const out=[]; if(!s)return out; let a=new Date(s+'T12:00:00'), b=new Date((e||s)+'T12:00:00'); if(isNaN(a)||isNaN(b))return out; for(let d=new Date(a);d<=b&&out.length<31;d.setDate(d.getDate()+1))out.push(d.toISOString().slice(0,10)); return out}
  function pretty(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}
  function mealSlots(i,total){return total>1&&i===0?['Lunch','Dinner','Snack']:total>1&&i===total-1?['Breakfast','Lunch']:['Breakfast','Lunch','Dinner','Snack','Happy hour','Dining out']}
  function setupListForms(){ensure(); const meal=$('saveMeal'); if(meal){const card=meal.closest('.formCard')||meal.parentElement; if(card&&!$('mealType711')){card.querySelector('label:has(#mealTitle)')?.remove(); $('mealPerson')?.closest('label')?.remove(); card.insertAdjacentHTML('afterbegin',`<label>Meal<select id="mealType711"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option><option>Happy hour</option><option>Dining out</option></select></label><label>Assigned to<select id="mealAssigned711">${memberOptions('Volunteer needed')}</select></label>`)} meal.onclick=e=>{e.preventDefault(); addList('meals')};}
    const g=$('saveGrocery'); if(g){const card=g.closest('.formCard')||g.parentElement; card?.querySelectorAll('label').forEach(l=>{if(/List privacy/i.test(l.textContent||''))l.remove()}); if(!$('groceryAssigned711'))g.insertAdjacentHTML('beforebegin',`<label>Assigned to<select id="groceryAssigned711">${memberOptions('Volunteer needed')}</select></label>`); g.onclick=e=>{e.preventDefault(); addList('groceries')};}
    const p=$('savePacking'); if(p){if(!$('packingAssigned711'))p.insertAdjacentHTML('beforebegin',`<label>Assigned to<select id="packingAssigned711">${memberOptions('Volunteer needed')}</select></label>`); p.onclick=e=>{e.preventDefault(); addList('packing')};}}
  function addList(kind){ensure(); const base=kind==='meals'?'meal':kind==='groceries'?'grocery':'packing'; const item=($(base+'Item')?.value||'').trim(); if(!item)return msg('Add an item first.'); const trip=($(base+'Trip')?.value)||'General'; const scope=($(base+'ScopeSelect652')?.value||$(base+'Privacy')?.value||'group'); const assigned=($(`${base}Assigned711`)?.value||$(base+'Person')?.value||'Volunteer needed'); const obj={id:id(),trip,item,scope,private:scope==='private',owner:scope==='private'?me():assigned,person:assigned,assignedTo:assigned,done:false,createdAt:now(),addedBy:me()}; if(kind==='meals'){obj.mealType=$('mealType711')?.value||$('mealType664')?.value||'Meal'; obj.date=$('mealDate664')?.value||''; data.meals.push(obj)} else data[kind].push(obj); if($(base+'Item'))$(base+'Item').value=''; save(kind+' item saved'); msg('Saved');}
  function renderMeals(){const box=$('mealList'); if(!box)return; setupListForms(); const t=tripBy($('mealTrip')?.value); const days=t?dateRange(t.start,t.end):[]; const calendar=days.length?`<div class="card mealDateCards711"><h3>Meals by Trip Date</h3><p>Pick a trip, then add meals under each travel day.</p>${days.map((d,i)=>`<div class="mealDayCard"><h3>${E(pretty(d))}</h3>${mealSlots(i,days.length).map(slot=>`<div class="mealSlot664"><b>${E(slot)}</b><button type="button" class="secondary smallBtn" data-meal-preset="${d}|${slot}">Add</button>${data.meals.filter(m=>(m.date===d||!m.date)&&(m.mealType===slot||m.title===slot)).map(m=>row('meals',m,m.item,m.assignedTo)).join('')}</div>`).join('')}</div>`).join('')}</div>`:''; box.innerHTML=calendar+`<div class="card"><h3>Group Meals</h3>${data.meals.filter(m=>!m.private).map(m=>row('meals',m,`${m.mealType||'Meal'}: ${m.item}`,m.trip)).join('')||'<p>No group meals yet.</p>'}</div><div class="card"><h3>My Private Meals</h3>${data.meals.filter(m=>m.private&&(m.owner===me()||m.addedBy===me())).map(m=>row('meals',m,`${m.mealType||'Meal'}: ${m.item}`,m.trip)).join('')||'<p>No private meals yet.</p>'}</div><div class="card"><h3>Grocery List</h3>${data.groceries.map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No grocery items yet.</p>'}</div>`;}
  function renderPacking(){const box=$('packingList'); if(!box)return; box.innerHTML=`<div class="card"><h3>Group Packing</h3>${data.packing.filter(p=>!p.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No group packing items yet.</p>'}</div><div class="card"><h3>My Private Packing</h3>${data.packing.filter(p=>p.private&&(p.owner===me()||p.addedBy===me())).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No private packing items yet.</p>'}</div>`;}
  function fileData(f){return new Promise((res,rej)=>{const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(f)})}
  async function saveMemory(){const files=Array.from($('memoryFiles')?.files||[]); const title=($('memoryTitle')?.value||'Family Memory').trim(); if(!files.length&&!title)return msg('Choose photos/videos or add a title.'); const mem={id:id(),title,caption:$('memoryCaption')?.value||'',date:$('memoryDate')?.value||'',trip:$('memoryTrip')?.value||'',uploader:$('memoryUploader')?.value||me(),media:[],createdAt:now()}; for(const f of files){mem.media.push({id:id(),name:f.name,type:f.type||'image',src:await fileData(f)})} data.memories.push(mem); ['memoryFiles','memoryTitle','memoryCaption','memoryDate','memoryTrip','memoryUploader'].forEach(x=>{if($(x))$(x).value=''}); save('memory saved'); msg('Memory saved');}
  function allMedia(){const out=[]; data.memories.forEach(m=>(m.media||[]).forEach((mm,i)=>{const src=typeof mm==='string'?mm:mm.src||mm.url||mm.data; if(src)out.push({id:mm.id||`${m.id}-${i}`,memoryId:m.id,src,type:mm.type||'',name:mm.name||m.title||'Photo',trip:m.trip,date:m.date})})); return out;}
  function renderMemories(){const box=$('memoryGrid'); if(!box)return; box.innerHTML=(data.memories||[]).map(m=>`<div class="memory journal"><h3>${E(m.title||'Memory')}</h3><p>${E(m.trip||'')} • ${E(m.date||'')} • ${E(m.uploader||'')}</p><div class="mediaGrid">${(m.media||[]).map((mm,i)=>{const src=typeof mm==='string'?mm:mm.src||mm.url||mm.data; const vid=String(mm.type||src).includes('video'); return `<div class="mediaAdminWrap">${vid?`<video controls src="${src}"></video>`:`<img src="${src}" alt="memory">`}${isAdmin()?`<button type="button" class="mediaDelete711" data-del-media="memories|${m.id}|${i}">×</button>`:''}</div>`}).join('')}</div><p>${E(m.caption||'')}</p><button type="button" class="secondary" data-add-book="${m.id}">Add photos to scrapbook</button><button type="button" class="secondary" onclick="del&&del('memories','${m.id}')">Delete Memory</button></div>`).join('')||'<div class="card"><p>No memories yet.</p></div>';}
  function installScrapbook(){const host=$('scrapbookPhotoPicker'); if(!host||host.dataset.v711)return; host.dataset.v711='1'; host.innerHTML=`<h3>Draft Scrapbook Page</h3><p>Tap photos, crop/zoom with controls, drag frames and stickers, then save.</p><div class="scrapTools711"><label>Frame<select id="frame711"><option value="soft">Soft</option><option value="polaroid">Pol</option><option value="heart">Heart</option><option value="circle">Circle</option><option value="star">Star</option><option value="none">None</option></select></label><label>Background<select id="bg711"><option value="seaGlass">Sea Glass</option><option value="sunset">Sunset</option><option value="sand">Sand</option><option value="roseGold">Rose Gold</option></select></label><button type="button" id="addText711" class="secondary">Text</button><button type="button" id="clearScrap711" class="secondary">Clear</button></div><h4>Photos</h4><div id="photoChoices711" class="scrapPhotoPickerGrid"></div><h4>Frames / Cutouts</h4><div class="framePalette711"><button data-frame711="soft">Soft</button><button data-frame711="polaroid">Pol</button><button data-frame711="heart">♡</button><button data-frame711="circle">○</button><button data-frame711="star">★</button><button data-frame711="none">None</button></div><h4>Stickers & Emojis</h4><div class="stickerPalette711">${'📷 💕 ❤️ 💛 💙 ⭐ ✨ ☀️ 🌊 🐚 🏖️ 🧭 ✈️ 📍 🍔 🌭 🎆'.split(' ').map(s=>`<button type="button" data-sticker711="${s}">${s}</button>`).join('')}</div><div id="canvas711" class="scrapCanvas711"></div><button type="button" id="savePage711" class="primary">Save Scrapbook Page</button>`; $('frame711').onchange=()=>{cropState.frame=$('frame711').value; drawCanvas()}; $('bg711').onchange=()=>{cropState.bg=$('bg711').value; drawCanvas()}; $('addText711').onclick=()=>{cropState.texts.push({id:id(),text:prompt('Text','Family memory')||'Family memory',x:50,y:80,size:24}); drawCanvas()}; $('clearScrap711').onclick=()=>{cropState={photos:[],stickers:[],texts:[],frame:'soft',bg:'seaGlass'}; drawChoices(); drawCanvas()}; $('savePage711').onclick=saveScrap; $$('#scrapbook [data-frame711]').forEach(b=>b.onclick=()=>{cropState.frame=b.dataset.frame711; $('frame711').value=cropState.frame; drawCanvas()}); $$('#scrapbook [data-sticker711]').forEach(b=>b.onclick=()=>{cropState.stickers.push({id:id(),text:b.dataset.sticker711,x:100,y:220,size:48}); drawCanvas()}); drawChoices(); drawCanvas();}
  function drawChoices(){const box=$('photoChoices711'); if(!box)return; const selected=new Set(cropState.photos.map(p=>p.mediaId)); box.innerHTML=allMedia().filter(m=>!String(m.type).includes('video')).map(m=>`<button type="button" class="scrapPick ${selected.has(m.id)?'selected':''}" data-pick711="${m.id}"><img src="${m.src}"><small>${E(m.name)}</small></button>`).join('')||'<p>No photos found. Save memories first.</p>'; box.querySelectorAll('[data-pick711]').forEach(b=>b.onclick=()=>{const m=allMedia().find(x=>x.id===b.dataset.pick711); if(!m)return; if(selected.has(m.id))cropState.photos=cropState.photos.filter(p=>p.mediaId!==m.id); else cropState.photos.push({id:id(),mediaId:m.id,src:m.src,x:30+cropState.photos.length*20,y:90+cropState.photos.length*20,w:180,h:150,zoom:1,ox:50,oy:50}); drawChoices(); drawCanvas();});}
  function drawCanvas(){const c=$('canvas711'); if(!c)return; c.className=`scrapCanvas711 bg-${cropState.bg}`; c.innerHTML=`<h3>${E($('pageTitle')?.value||'Draft Scrapbook Page')}</h3>`+cropState.photos.map(p=>`<div class="cropPhoto711 frame-${cropState.frame}" data-pid="${p.id}" style="left:${p.x}px;top:${p.y}px;width:${p.w}px;height:${p.h}px"><img src="${p.src}" style="transform:scale(${p.zoom});object-position:${p.ox}% ${p.oy}%"><div class="cropBtns"><button data-crop="${p.id}|zin">+</button><button data-crop="${p.id}|zout">-</button><button data-crop="${p.id}|up">↑</button><button data-crop="${p.id}|down">↓</button><button data-crop="${p.id}|left">←</button><button data-crop="${p.id}|right">→</button><button data-crop="${p.id}|del">×</button></div><span class="resize711">↘</span></div>`).join('')+cropState.stickers.map(s=>`<div class="sticker711" data-sid="${s.id}" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${E(s.text)}<span class="resize711">↘</span></div>`).join('')+cropState.texts.map(t=>`<div class="text711" data-sid="${t.id}" style="left:${t.x}px;top:${t.y}px;font-size:${t.size}px">${E(t.text)}<span class="resize711">↘</span></div>`).join(''); bindMove();}
  function bindMove(){function bind(el,obj){let start=null; el.onpointerdown=e=>{if(e.target.closest('button'))return; e.preventDefault(); const rect=el.getBoundingClientRect(); start={x:e.clientX,y:e.clientY,l:obj.x,t:obj.y,w:obj.w,h:obj.h,size:obj.size,resize:e.target.classList.contains('resize711')}; el.setPointerCapture(e.pointerId)}; el.onpointermove=e=>{if(!start)return; if(start.resize){if(obj.w){obj.w=Math.max(80,start.w+e.clientX-start.x); obj.h=Math.max(80,start.h+e.clientY-start.y)} else obj.size=Math.max(18,start.size+(e.clientX-start.x)/2)} else {obj.x=Math.max(0,start.l+e.clientX-start.x); obj.y=Math.max(0,start.t+e.clientY-start.y)} drawCanvas()}; el.onpointerup=()=>start=null;}
    $$('#canvas711 .cropPhoto711').forEach(el=>bind(el,cropState.photos.find(p=>p.id===el.dataset.pid))); $$('#canvas711 .sticker711,#canvas711 .text711').forEach(el=>bind(el,[...cropState.stickers,...cropState.texts].find(s=>s.id===el.dataset.sid))); $$('[data-crop]').forEach(b=>b.onclick=e=>{e.stopPropagation(); const [pid,act]=b.dataset.crop.split('|'); const p=cropState.photos.find(x=>x.id===pid); if(!p)return; if(act==='zin')p.zoom=Math.min(3,p.zoom+.1); if(act==='zout')p.zoom=Math.max(.7,p.zoom-.1); if(act==='up')p.oy=Math.max(0,p.oy-5); if(act==='down')p.oy=Math.min(100,p.oy+5); if(act==='left')p.ox=Math.max(0,p.ox-5); if(act==='right')p.ox=Math.min(100,p.ox+5); if(act==='del')cropState.photos=cropState.photos.filter(x=>x.id!==pid); drawChoices(); drawCanvas();});}
  function saveScrap(){const page={id:id(),title:($('pageTitle')?.value||'Scrapbook Page').trim(),note:($('pageNote')?.value||'').trim(),bg:cropState.bg,frame:cropState.frame,photos:cropState.photos.map(p=>p.src),photoLayout:cropState.photos,stickers:cropState.stickers,texts:cropState.texts,createdAt:now(),version:VERSION}; if(!page.photos.length&&!page.note&&!page.title)return msg('Add photos or a title first.'); data.pages.push(page); cropState={photos:[],stickers:[],texts:[],frame:'soft',bg:'seaGlass'}; ['pageTitle','pageNote'].forEach(x=>{if($(x))$(x).value=''}); save('scrapbook page saved'); drawChoices(); drawCanvas(); msg('Scrapbook page saved');}
  function renderPages(){const box=$('scrapbookPages'); if(!box)return; box.innerHTML=(data.pages||[]).map(p=>`<div class="scrapPage711 card"><h3>${E(p.title||'Scrapbook Page')}</h3><div class="scrapCanvas711 bg-${E(p.bg||'seaGlass')}">${(p.photoLayout||[]).map(ph=>`<div class="cropPhoto711 frame-${E(p.frame||'soft')}" style="left:${ph.x}px;top:${ph.y}px;width:${ph.w}px;height:${ph.h}px"><img src="${ph.src}" style="transform:scale(${ph.zoom||1});object-position:${ph.ox||50}% ${ph.oy||50}%"></div>`).join('')||((p.photos||[]).map((src,i)=>`<div class="cropPhoto711 frame-${E(p.frame||'soft')}" style="left:${30+i*25}px;top:${90+i*25}px;width:180px;height:150px"><img src="${src}"></div>`).join(''))}${(p.stickers||[]).map(s=>`<div class="sticker711" style="left:${s.x}px;top:${s.y}px;font-size:${s.size}px">${E(s.text||s.emoji||'❤️')}</div>`).join('')}${(p.texts||[]).map(t=>`<div class="text711" style="left:${t.x}px;top:${t.y}px;font-size:${t.size}px">${E(t.text)}</div>`).join('')}</div><p>${E(p.note||'')}</p><button type="button" class="secondary" onclick="window.print()">Download / Print</button>${isAdmin()?`<button type="button" class="secondary" data-del-page="${p.id}">Delete Page</button>`:''}</div>`).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>';}
  function adminGate(){const admin=isAdmin(); document.body.classList.toggle('isAdmin711',admin); $$('[data-go="admin71"], #drawer [data-go="admin71"], .adminOnlyCard, #settings .card:has(#adminUnlockBtn), #settings .card:has(#createInviteBtn)').forEach(el=>{el.style.display=admin?'':'none'}); const role=$('personRole'); if(role&&!admin){role.innerHTML='<option>Family</option><option>Child</option><option>Guest</option>'} const inviteRole=$('inviteRole'); if(inviteRole&&admin){inviteRole.innerHTML='<option>Family</option><option>Child</option><option>Guest</option><option>Admin</option>'}}
  function profileClearHook(){const b=$('saveProfile652')||$('profileSave651'); if(b&&!b.dataset.v711){b.dataset.v711='1'; b.addEventListener('click',()=>setTimeout(()=>['profileName652','profileEmail652','profilePhone652','profilePhoto652','profileName651','profileEmail651','profilePhone651','profilePhoto651'].forEach(x=>{if($(x))$(x).value=''}),500),true)}}
  function renderHomeTop(){if((location.hash||'').includes('home')||$('.dock [data-go="home"]')?.classList.contains('active')){window.scrollTo(0,0)}}
  function renderAll(){ensure(); cleanOldSearch(); setupListForms(); installScrapbook(); adminGate(); profileClearHook(); try{renderTrips()}catch(e){console.warn(e)} try{renderTravel()}catch(e){console.warn(e)} try{renderMeals()}catch(e){console.warn(e)} try{renderPacking()}catch(e){console.warn(e)} try{renderMemories()}catch(e){console.warn(e)} try{renderPages()}catch(e){console.warn(e)} try{drawChoices(); drawCanvas()}catch{} }
  document.addEventListener('click',function(e){const a=e.target.closest('a.secondary[href*="weather.com"], .weatherLiveCard a'); if(a){return;} const b=e.target.closest('button'); if(!b)return; const t=(b.textContent||'').trim().toLowerCase(); if(b.dataset.addLink){e.preventDefault(); e.stopImmediatePropagation(); addTravelLink(b.dataset.addLink,$(`tripLinkTitle-${b.dataset.addLink}`)?.value,$(`tripLinkUrl-${b.dataset.addLink}`)?.value)} if(b.dataset.delLink){e.preventDefault(); e.stopImmediatePropagation(); data.links=data.links.filter(l=>l.id!==b.dataset.delLink); data.trips.forEach(t=>t.tripLinks=(t.tripLinks||[]).filter(l=>l.id!==b.dataset.delLink)); save('travel link removed')} if(b.dataset.addVote){e.preventDefault(); e.stopImmediatePropagation(); addVote(b.dataset.addVote)} if(b.dataset.vote){e.preventDefault(); const [tid,i]=b.dataset.vote.split('|'); const tr=tripBy(tid), v=tr?.voteOptions?.[+i]; if(v){v.votes=v.votes||{}; v.votes[me()]=now(); save('vote')}} if(b.dataset.delVote&&isAdmin()){e.preventDefault(); const [tid,i]=b.dataset.delVote.split('|'); const tr=tripBy(tid); if(tr){tr.voteOptions.splice(+i,1); save('vote option removed')}} if(b.dataset.toggle){const [list,i]=b.dataset.toggle.split('|'); const x=data[list]?.find(z=>z.id===i); if(x){x.done=b.checked; save(list+' toggled')}} if(b.dataset.delItem){e.preventDefault(); const [list,i]=b.dataset.delItem.split('|'); data[list]=data[list].filter(x=>x.id!==i); save(list+' deleted')} if(b.dataset.mealPreset){const [d,slot]=b.dataset.mealPreset.split('|'); if($('mealDate664'))$('mealDate664').value=d; if($('mealType711'))$('mealType711').value=slot; $('mealItem')?.focus();} if(b.dataset.delMedia&&isAdmin()){const [,mid,idx]=b.dataset.delMedia.split('|'); const m=data.memories.find(x=>x.id===mid); if(m){m.media.splice(+idx,1); save('media deleted')}} if(b.dataset.delPage&&isAdmin()){data.pages=data.pages.filter(p=>p.id!==b.dataset.delPage); save('scrapbook page deleted')} if(b.id==='saveMemories'){e.preventDefault(); e.stopImmediatePropagation(); saveMemory()} if(t.includes('remove duplicates')){e.preventDefault(); dedupeAll(); save('duplicates removed'); msg('Duplicates removed')} if(b.dataset.go==='home'){setTimeout(()=>window.scrollTo(0,0),50)}},true);
  const oldRender=window.render; window.render=function(){try{oldRender&&oldRender()}catch(e){console.warn(e)} renderAll();};
  document.addEventListener('DOMContentLoaded',()=>{ensure(); startRemote(); renderAll(); setTimeout(renderAll,800);});
  setTimeout(()=>{ensure(); startRemote(); renderAll();},1800);
})();
