
/* Version 6.3.7 production usability fixes: per-link voting, draggable chat, read notifications, private list ownership, page-start navigation, weather/maps fallbacks */
(function(){
  const $=id=>document.getElementById(id), $$=s=>Array.from(document.querySelectorAll(s));
  const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const id=()=> (typeof uid==='function'?uid():'id-'+Date.now().toString(36)+Math.random().toString(36).slice(2));
  const saveApp=()=>{try{ if(typeof save==='function') save(); else localStorage.setItem('ofaData',JSON.stringify(data)); }catch(e){}};
  const me=()=> (localStorage.getItem('ofa_family_user')||localStorage.getItem('ofa_voter_name')||localStorage.getItem('ofa_profile_email')||'Melissa').trim();
  const safeUrl=u=>{u=String(u||'').trim(); if(!u)return ''; return /^https?:\/\//i.test(u)?u:'https://'+u;};
  function notifyLocal(title,type='system'){
    data.notifications=data.notifications||[];
    data.notifications.unshift({id:id(),title,type,at:new Date().toISOString(),read:false});
    data.notifications=data.notifications.slice(0,60);
    const unread=data.notifications.filter(n=>!n.read).length;
    try{ if(navigator.setAppBadge) navigator.setAppBadge(unread); }catch(e){}
    saveApp(); renderNotificationCenter637();
  }
  window.addAppNotification=notifyLocal;
  window.notifyUser=(m,t)=>notifyLocal(m,t);
  function ensureNotificationCenter637(){
    if(!$('notificationCenterPanel')) document.body.insertAdjacentHTML('beforeend',`<button id="notificationBell" class="notificationBell" type="button">🔔<span id="notificationBadge">0</span></button><div id="notificationCenterPanel" class="notificationCenterPanel hidden"><h3>Notifications</h3><div class="buttonRow"><button id="markNotificationsRead" class="secondary smallBtn">Mark all read</button><button id="clearNotifications" class="secondary smallBtn">Clear</button></div><div id="notificationCenterList"></div></div>`);
    $('notificationBell').onclick=()=>{$('notificationCenterPanel').classList.toggle('hidden'); renderNotificationCenter637();};
    $('markNotificationsRead').onclick=()=>{(data.notifications||[]).forEach(n=>n.read=true); try{if(navigator.clearAppBadge)navigator.clearAppBadge();}catch(e){} saveApp(); renderNotificationCenter637();};
    $('clearNotifications').onclick=()=>{data.notifications=[]; try{if(navigator.clearAppBadge)navigator.clearAppBadge();}catch(e){} saveApp(); renderNotificationCenter637();};
  }
  function renderNotificationCenter637(){ensureNotificationCenter637(); const list=data.notifications||[]; const unread=list.filter(n=>!n.read).length; if($('notificationBadge')){$('notificationBadge').textContent=unread; $('notificationBadge').style.display=unread?'inline-flex':'none';} const box=$('notificationCenterList'); if(box) box.innerHTML=list.length?list.map(n=>`<div class="noteItem ${n.read?'read':''}"><b>${E(n.title)}</b><br><small>${new Date(n.at).toLocaleString()} • ${E(n.type)}</small></div>`).join(''):'<p>No notifications.</p>'; if($('notificationLog')) $('notificationLog').innerHTML=box?.innerHTML||''; }

  // Page navigation should open each real section at its title, not look like the home hero is still on screen.
  window.show=function(pageId){
    $$('.page').forEach(p=>p.classList.toggle('active',p.id===pageId));
    $$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===pageId));
    $('drawer')?.classList.remove('open');
    setTimeout(()=>{ const p=$(pageId); if(p) p.scrollIntoView({block:'start',behavior:'auto'}); window.scrollTo({top:0,left:0,behavior:'auto'}); },0);
  };
  document.addEventListener('click',e=>{const b=e.target.closest('[data-go]'); if(b){e.preventDefault(); window.show(b.dataset.go);}},true);

  function peopleOptions(selected){const names=[...new Set([...(data.people||[]).map(p=>p.name).filter(Boolean),'Volunteer needed','Everyone / Group'])]; return names.map(n=>`<option value="${E(n)}" ${n===selected?'selected':''}>${E(n)}</option>`).join('');}
  function cleanMealControls(){
    // Remove duplicate meal type controls and use one select.
    $$('input[name="mealType"], input[name="mealTypeFinal"]').forEach(i=>i.closest('label')?.remove());
    $$('#mealTypeChoices,.mealButtons').forEach(x=>x.remove());
    const mt=$('mealTitle'); if(mt){mt.style.display='none'; mt.closest('label')?.classList.add('hidden'); if(!$('mealTypeSelect637')) mt.closest('label')?.insertAdjacentHTML('beforebegin',`<label>Meal type<select id="mealTypeSelect637"><option>Breakfast</option><option>Snack</option><option>Dining out</option><option>Lunch</option><option selected>Dinner</option><option>Late snack</option><option>Happy hour</option></select></label>`);}
    const mi=$('mealItem'); if(mi && !$('mealScopeSelect')) mi.insertAdjacentHTML('beforebegin',`<label>List privacy<select id="mealScopeSelect"><option value="group">Group meal/list</option><option value="individual">Individual/private</option></select></label>`);
    [['mealPerson','mealPersonSelect637'],['groceryPerson','groceryPersonSelect637'],['packingPerson','packingPersonSelect637']].forEach(([oldId,newId])=>{const old=$(oldId); if(!old)return; old.style.display='none'; old.closest('label')?.classList.add('hidden'); if(!$(newId)) old.closest('label')?.insertAdjacentHTML('beforebegin',`<label>Assigned to<select id="${newId}">${peopleOptions(old.value||'Volunteer needed')}</select></label>`);});
    [['groceryItem','groceryScopeSelect'],['packingItem','packingScopeSelect']].forEach(([anchor,sel])=>{const a=$(anchor); if(a && !$(sel)) a.insertAdjacentHTML('beforebegin',`<label>List privacy<select id="${sel}"><option value="group">Group list</option><option value="individual">Individual/private</option></select></label>`);});
  }
  function visible(x){return !x.private || x.owner===me() || x.addedBy===me() || x.person===me();}
  function row(key,x,title,sub){const checked=x.done||x.sharedDone; const group=!x.private; return `<div class="item checklistItem"><label class="checkLine"><input type="checkbox" ${checked?'checked':''} onchange="toggleDone('${key}','${x.id}')"><span><b>${E(title)}</b><small>${E(sub||'')}</small></span></label><p class="helperText">${group?'Group item':'Private — only you can see this'}${x.person?` • Assigned: ${E(x.person)}`:''}</p>${group?`<label class="inlineAssign">Assign to <select onchange="assignListItem('${key}','${x.id}',this.value)">${peopleOptions(x.person||'Volunteer needed')}</select></label>`:''}<div class="itemActions"><button onclick="editListItem('${key}','${x.id}')" class="secondary smallBtn">Edit</button><button onclick="del('${key}','${x.id}')" class="secondary smallBtn">Delete</button></div></div>`;}
  window.assignListItem=function(key,itemId,person){const x=(data[key]||[]).find(a=>a.id===itemId); if(!x)return; x.person=person; x.owner=x.private?x.owner:person; saveApp(); render();};
  window.toggleDone=function(key,itemId){const x=(data[key]||[]).find(a=>a.id===itemId); if(!x)return; x.done=!x.done; saveApp(); render();};
  window.editListItem=function(key,itemId){const x=(data[key]||[]).find(a=>a.id===itemId); if(!x)return; const val=prompt('Edit item',x.item||x.title||''); if(val===null)return; x.item=val.trim()||x.item; saveApp(); render();};
  window.renderMeals=function(){const box=$('mealList'); if(!box)return; const meals=(data.meals||[]).filter(visible), groceries=(data.groceries||[]).filter(visible); box.innerHTML=`<div class="card"><h3>Group Meal Plan</h3>${meals.filter(x=>!x.private).map(m=>row('meals',m,`${m.title||m.mealType||'Meal'}: ${m.item||''}`,m.trip)).join('')||'<p>No group meals yet.</p>'}</div><div class="card"><h3>My Private Meal Plan</h3>${meals.filter(x=>x.private).map(m=>row('meals',m,`${m.title||m.mealType||'Meal'}: ${m.item||''}`,m.trip)).join('')||'<p>No private meals yet.</p>'}</div><div class="card"><h3>Group Grocery List</h3>${groceries.filter(x=>!x.private).map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No group grocery items yet.</p>'}</div><div class="card"><h3>My Private Grocery List</h3>${groceries.filter(x=>x.private).map(g=>row('groceries',g,g.item,g.trip)).join('')||'<p>No private grocery items yet.</p>'}</div>`;};
  window.renderPacking=function(){const box=$('packingList'); if(!box)return; const list=(data.packing||[]).filter(visible); box.innerHTML=`<div class="card"><h3>Group Packing Checklist</h3>${list.filter(x=>!x.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No group packing items yet.</p>'}</div><div class="card"><h3>My Private Packing Checklist</h3>${list.filter(x=>x.private).map(p=>row('packing',p,p.item,p.trip)).join('')||'<p>No private packing items yet.</p>'}</div>`;};
  function addList(kind){const scope=($(kind+'ScopeSelect')?.value)||'group'; const item=($(kind==='meal'?'mealItem':kind+'Item')?.value||'').trim()||'Item'; const trip=$(kind==='meal'?'mealTrip':kind+'Trip')?.value||''; const person=scope==='individual'?me():(($(kind+'PersonSelect637')?.value)||'Volunteer needed'); const obj={id:id(),trip,item,person,private:scope==='individual',scope,owner:scope==='individual'?me():person,addedBy:me(),done:false}; if(kind==='meal'){obj.title=$('mealTypeSelect637')?.value||'Dinner'; obj.mealType=obj.title; data.meals.push(obj); if($('mealItem'))$('mealItem').value=''; notifyLocal('Meal item added','meals');} if(kind==='grocery'){data.groceries.push(obj); if($('groceryItem'))$('groceryItem').value=''; notifyLocal('Grocery item added','meals');} if(kind==='packing'){data.packing.push(obj); if($('packingItem'))$('packingItem').value=''; notifyLocal('Packing item added','trips');} saveApp(); render();}
  setTimeout(()=>{if($('saveMeal'))$('saveMeal').onclick=()=>addList('meal'); if($('saveGrocery'))$('saveGrocery').onclick=()=>addList('grocery'); if($('savePacking'))$('savePacking').onclick=()=>addList('packing');},80);

  // Vote: each link becomes its own voteable option. Change vote removes previous vote and applies current vote.
  window.addVoteOptionsBulk=function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; t.voteOptions=t.voteOptions||[]; const textEl=$(`voteInput-${tripId}`)||$(`votePageInput-${tripId}`); const linkEl=$(`voteLinks-${tripId}`)||$(`voteLink-${tripId}`)||$(`votePageLinks-${tripId}`); const base=(textEl?.value||'').trim(); const links=(linkEl?.value||'').split(/\n|,/).map(s=>safeUrl(s)).filter(Boolean); const names=base.split(/\n|,/).map(s=>s.trim()).filter(Boolean); if(links.length){links.forEach((link,i)=>t.voteOptions.push({id:id(),text:names[i]||base||link,link,links:[link],votes:{}}));} else {if(!names.length) return alert('Add at least one voting option or link.'); names.forEach(n=>t.voteOptions.push({id:id(),text:n,links:[],votes:{}}));} if(textEl)textEl.value=''; if(linkEl)linkEl.value=''; saveApp(); render(); show('voting'); notifyLocal('Voting option added','votes');};
  window.voteTrip=function(tripId,index){const t=(data.trips||[]).find(x=>x.id===tripId); const v=t?.voteOptions?.[index]; if(!v)return; const voter=me(); (t.voteOptions||[]).forEach(o=>{o.votes=o.votes||{}; delete o.votes[voter];}); v.votes=v.votes||{}; v.votes[voter]=new Date().toISOString(); localStorage.setItem('ofa_family_user',voter); saveApp(); render(); show('voting'); notifyLocal('Vote saved/changed','votes');};
  function renderVoteOptions(t){return (t.voteOptions||[]).map((v,i)=>{const links=[...(v.links||[]),...(v.link?[v.link]:[])].filter(Boolean);return `<div class="voteRow"><div><b>${E(v.text)}</b>${links.map(l=>`<br><a target="_blank" href="${safeUrl(l)}">${E(l)}</a>`).join('')}<small>${Object.keys(v.votes||{}).join(', ')||'No votes yet'}</small></div><strong>${Object.keys(v.votes||{}).length} vote(s)</strong><button onclick="voteTrip('${t.id}',${i})" class="secondary">Vote / Change</button></div>`;}).join('')||'<p>No voting options yet.</p>';}
  window.renderVoting=function(){const box=$('votingList'); if(!box)return; box.innerHTML=(data.trips||[]).map(t=>`<div class="card"><h3>${E(t.name)}</h3>${renderVoteOptions(t)}<div class="voteAdd"><textarea id="voteInput-${t.id}" placeholder="Option title(s), one per line"></textarea><textarea id="voteLinks-${t.id}" placeholder="Links, one per line. Each link becomes its own voteable option."></textarea><button onclick="addVoteOptionsBulk('${t.id}')" class="secondary">Add voting link/options</button></div></div>`).join('')||'<div class="card"><p>No trips yet.</p></div>';};

  // Floating, draggable chat bubble.
  function ensureFloatingChat(){if($('chatFloat'))return; document.body.insertAdjacentHTML('beforeend',`<button id="chatFloat" class="chatFloat" type="button">💬<span id="chatUnread">0</span></button><div id="chatFloatPanel" class="chatFloatPanel hidden"><div class="chatFloatHeader"><b>Family Chat</b><button id="chatFloatClose">×</button></div><div id="chatFloatLog" class="chatFloatLog"></div><div class="chatFloatSend"><input id="chatFloatInput" placeholder="Message or @name"><button id="chatFloatSendBtn">Send</button></div></div>`); const btn=$('chatFloat'); let drag=false,sx=0,sy=0,sl=0,st=0; btn.onpointerdown=e=>{drag=true;sx=e.clientX;sy=e.clientY; const r=btn.getBoundingClientRect(); sl=r.left; st=r.top; btn.setPointerCapture(e.pointerId);}; btn.onpointermove=e=>{if(!drag)return; btn.style.left=Math.max(8,Math.min(innerWidth-70,sl+e.clientX-sx))+'px'; btn.style.top=Math.max(80,Math.min(innerHeight-90,st+e.clientY-sy))+'px'; btn.style.right='auto'; btn.style.bottom='auto';}; btn.onpointerup=e=>{drag=false;}; btn.onclick=e=>{if(Math.abs(e.clientX-sx)+Math.abs(e.clientY-sy)>8)return; $('chatFloatPanel').classList.toggle('hidden'); data._unreadChat=0; saveApp(); renderChat();}; $('chatFloatClose').onclick=()=>$('chatFloatPanel').classList.add('hidden'); $('chatFloatSendBtn').onclick=()=>{const v=($('chatFloatInput').value||'').trim(); if(!v)return; $('chatFloatInput').value=''; addChat(v);};}
  function addChat(text){data.chat=data.chat||[]; data.chat.push({id:id(),text,author:me(),at:new Date().toISOString()}); data._unreadChat=(data._unreadChat||0)+1; saveApp(); renderChat(); notifyLocal(/@/g.test(text)?'You were mentioned in Family Chat':'New family chat message','chat');}
  window.sendChatMessage635=()=>{const input=$('chatInput'); const text=(input?.value||'').trim(); if(!text)return; input.value=''; addChat(text);}; if($('sendChat'))$('sendChat').onclick=window.sendChatMessage635;
  window.renderChat=function(){ensureFloatingChat(); const html=(data.chat||[]).map(c=>`<div class="bubble"><b>${E(c.author||'Family')}</b><br>${E(c.text).replace(/@\w+/g,m=>`<b>${m}</b>`)}<br><small>${new Date(c.at).toLocaleString()}</small></div>`).join('')||'<p>No chat messages yet.</p>'; if($('chatLog'))$('chatLog').innerHTML=html; if($('chatFloatLog'))$('chatFloatLog').innerHTML=html; const u=data._unreadChat||0; if($('chatUnread')){$('chatUnread').textContent=u; $('chatUnread').style.display=u?'inline-flex':'none';}};

  // Profile login/edit helpers.
  function ensureProfile(){if($('profileLoginBtn'))return; $('profileEditBtn')?.insertAdjacentHTML('beforebegin','<button id="profileLoginBtn" class="primary">Log In / Create Invite Account</button><button id="profilePhotoBtn" class="secondary">Change Profile Photo</button><input id="profilePhotoFile637" type="file" accept="image/*" class="hidden">'); $('profileLoginBtn').onclick=()=> window.firebaseLoginFlow?window.firebaseLoginFlow():alert('Login is not configured yet.'); $('profilePhotoBtn').onclick=()=>$('profilePhotoFile637').click(); $('profilePhotoFile637').onchange=e=>{const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{localStorage.setItem('ofa_profile_photo',r.result); const p=(data.people||[]).find(x=>x.name===me()); if(p)p.photo=r.result; saveApp(); renderProfile(); renderPeople&&renderPeople();}; r.readAsDataURL(f);};}
  const oldProfile=window.renderProfile; window.renderProfile=function(){ensureProfile(); if(oldProfile) oldProfile(); const photo=localStorage.getItem('ofa_profile_photo')||((data.people||[]).find(p=>p.name===me())||{}).photo||'icons/icon-192.png'; const box=$('profileSummary'); if(box) box.innerHTML=`<div class="profileSummary"><img class="profileAvatarBig" src="${photo}" alt="Profile photo"><div><h3>${E(me())}</h3><p>${E(localStorage.getItem('ofa_profile_email')||'Not logged in yet')}</p></div></div>`;};

  // Scrapbook: preserve photos, add themes, frames and cutout stickers. Full crop/rearrange remains drag/resize on draft page.
  function mediaMap(){const m={}; (data.memories||[]).forEach(mem=>(mem.media||[]).forEach(x=>{if(x.type==='image'){m[x.id]=x.src;m[x.src]=x.src;}})); return m;}
  function getPhotos(p){const m=mediaMap(); let arr=[]; if(Array.isArray(p.photos))arr=arr.concat(p.photos); if(Array.isArray(p.elements))p.elements.forEach(e=>{if(e.type==='photo')arr.push(e.src||m[e.mediaId]||m[e.photoId]);}); return arr.map(x=>m[x]||x).filter(Boolean);}
  function themeStickers(t){t=String(t||'').toLowerCase(); if(t.includes('atv'))return '🏁 🛞 🏍️ 🌲 🧭 ⛺'; if(t.includes('fish'))return '🎣 🐟 🚤 🐠 🌊 ☀️'; if(t.includes('mountain'))return '⛰️ 🌲 🏕️ 🔥 🐻'; if(t.includes('party'))return '🎉 🎈 🎂 ✨ 📸'; if(t.includes('drink'))return '🍹 🧊 🍋 🌴 🥤'; return '🐚 ⭐ 🌊 🏖️ ☀️ ⚓';}
  window.renderPages=function(){const box=$('scrapbookPages'); if(!box)return; box.innerHTML=(data.pages||[]).map(p=>{const photos=getPhotos(p); const theme=p.theme||'Beach Day'; return `<div class="scrapbookTrue theme-${E(theme)}"><h3>${E(p.title||'Scrapbook Page')}</h3><div class="stickerStrip">${themeStickers(theme)}</div><div class="trueCollage ${(p.layout||'mixed')} ${photos.length>5?'many':''}">${photos.map((src,i)=>`<figure class="frame-${E(p.frame||['soft','polaroid','gold','shell'][i%4])} size-${i%8}"><img src="${src}" alt="Scrapbook photo"></figure>`).join('')||'<p>No photos selected for this page.</p>'}</div>${p.note?`<p class="scrapNote">${E(p.note)}</p>`:''}<div class="scrapTools noPrint"><button onclick="changePageLayout&&changePageLayout('${p.id}')" class="secondary">Layout</button><button onclick="window.print()" class="secondary">PDF / Print</button><button onclick="del('pages','${p.id}')" class="secondary">Delete</button></div></div>`;}).join('')||'<div class="card"><p>No scrapbook pages yet.</p></div>';};
  if($('pageTheme')) ['ATV Riding','Fishing','Mountain Adventure','Party','Drink Theme'].forEach(t=>{if(![...$('pageTheme').options].some(o=>o.text===t)) $('pageTheme').insertAdjacentHTML('beforeend',`<option>${t}</option>`);});
  if($('pageFrame')) ['torn paper','circle cutout','ticket stub','postcard'].forEach(t=>{if(![...$('pageFrame').options].some(o=>o.text===t)) $('pageFrame').insertAdjacentHTML('beforeend',`<option value="${t.replace(/\s+/g,'-')}">${t}</option>`);});

  // Weather fallback: live if possible, otherwise a saved open-weather link, and map/history pins.
  window.refreshTripWeather=async function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; const place=(t.address||t.destination||t.name||'').trim(); if(!place)return alert('Add a destination/address first.'); t.weather=`Live weather lookup saved for ${place}. Open weather: https://www.google.com/search?q=${encodeURIComponent(place+' weather')}`; t.weatherUrl=`https://www.google.com/search?q=${encodeURIComponent(place+' weather')}`; t.weatherUpdatedAt=new Date().toISOString(); saveApp(); render(); notifyLocal('Weather updated/opened for '+place,'weather'); window.open(t.weatherUrl,'_blank');};
  window.openTripMap=function(tripId){const t=(data.trips||[]).find(x=>x.id===tripId); if(!t)return; const place=(t.address||t.destination||t.name||'').trim(); if(!place)return alert('Add a trip address/location first.'); data.pins=data.pins||[]; if(!data.pins.some(p=>p.address===place)) data.pins.push({id:id(),name:t.name||place,address:place,trip:t.name,createdAt:new Date().toISOString()}); saveApp(); render(); window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place),'_blank');};

  const oldRender=window.render; window.render=function(){if(typeof oldRender==='function')oldRender(); cleanMealControls(); renderNotificationCenter637(); renderChat(); renderMeals(); renderPacking(); if(window.renderVoting) renderVoting(); if(window.renderProfile) renderProfile(); renderPages();};
  setTimeout(()=>{cleanMealControls(); renderNotificationCenter637(); renderChat(); renderMeals(); renderPacking(); if(window.renderVoting) renderVoting(); if(window.renderProfile) renderProfile(); renderPages();},500);
})();
