(()=>{'use strict';
const RELEASE='10.3.17',DATA_KEY='ofa-9-data',JOURNAL_KEY='ofa-media-journal-v1';
let correcting=false,mediaDeleteBusy=false,mediaDeleteObserver=null;
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}}
function writeJson(key,value){localStorage.setItem(key,JSON.stringify(value))}
function setTitle(){if(correcting)return;const expected=`Our Family Adventures ${RELEASE}`;if(document.title!==expected){correcting=true;document.title=expected;correcting=false}}
function setStoredVersion(){try{const data=readJson(DATA_KEY,null);if(data){data.version=RELEASE;writeJson(DATA_KEY,data)}}catch(error){console.warn('Version storage update',error)}}
function familyId(data){return String(data?.settings?.template?.familyId||'default-family').toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||'default-family'}
function trip(data,tripId){return (Array.isArray(data?.trips)?data.trips:[]).find(row=>String(row?.id)===String(tripId))}
function recordPath(data,collection,item){const base=`families/${familyId(data)}`;if(!item?.tripId)return `${base}/publicData/shared/${collection}/${item.id}`;const bucket=trip(data,item.tripId)?.visibility==='private'?'privateTrips':'familyTrips';return `${base}/${bucket}/${item.tripId}/collections/${collection}/${item.id}`}
function currentUser(){try{return window.firebase?.auth?.().currentUser||null}catch{return null}}
function isAdmin(){return localStorage.getItem('ofa-role')==='Admin'}
function canDelete(item){const user=currentUser();return !!user&&(isAdmin()||String(item?.owner||item?.createdBy||'')===String(user.uid))}
function sameUrl(a,b){try{return new URL(String(a||''),location.href).href===new URL(String(b||''),location.href).href}catch{return String(a||'')===String(b||'')}}
function notify(text){const toast=document.querySelector('#toast');if(!toast)return;toast.textContent=text;toast.style.display='block';clearTimeout(toast.__mediaDeleteTimer);toast.__mediaDeleteTimer=setTimeout(()=>toast.style.display='none',4200)}
function verifyAdminForOtherOwner(data,item){const user=currentUser();if(!user||!isAdmin()||String(item?.owner||item?.createdBy||'')===String(user.uid))return true;const code=String(data?.settings?.adminCode||'');if(!code)return true;const entered=prompt('Enter the Admin PIN to permanently delete this photo.');if(entered===code)return true;notify('Incorrect Admin PIN. Photo was not deleted.');return false}
async function deleteStorage(item){if(!window.firebase?.storage)return;try{if(item?.storagePath){await firebase.storage().ref(item.storagePath).delete();return}if(item?.url&&/^https?:/i.test(item.url))await firebase.storage().refFromURL(item.url).delete()}catch(error){if(error?.code==='storage/object-not-found')return;throw error}}
function cleanedMemory(memory,item){const ids=Array.isArray(memory?.mediaIds)?memory.mediaIds:[],photos=Array.isArray(memory?.photos)?memory.photos:[];let touched=false,newIds=[],newPhotos=[];const length=Math.max(ids.length,photos.length);for(let i=0;i<length;i++){const idMatch=String(ids[i]||'')===String(item.id),urlMatch=photos[i]&&sameUrl(photos[i],item.url);if(idMatch||urlMatch){touched=true;continue}if(ids[i])newIds.push(ids[i]);if(photos[i])newPhotos.push(photos[i])}if(!touched&&photos.some(url=>sameUrl(url,item.url))){touched=true;newIds=ids.filter(id=>String(id)!==String(item.id));newPhotos=photos.filter(url=>!sameUrl(url,item.url))}return touched?{mediaIds:newIds,photos:newPhotos}:null}
async function cleanupMemories(data,item){const jobs=[];(Array.isArray(data?.memories)?data.memories:[]).forEach(memory=>{const cleaned=cleanedMemory(memory,item);if(!cleaned)return;memory.mediaIds=cleaned.mediaIds;memory.photos=cleaned.photos;jobs.push(firebase.database().ref(recordPath(data,'memories',memory)).update(cleaned))});if(jobs.length)await Promise.all(jobs)}
function cleanupLocal(data,item){data.media=(Array.isArray(data.media)?data.media:[]).filter(row=>String(row?.id)!==String(item.id));(Array.isArray(data.memories)?data.memories:[]).forEach(memory=>{const cleaned=cleanedMemory(memory,item);if(cleaned){memory.mediaIds=cleaned.mediaIds;memory.photos=cleaned.photos}});writeJson(DATA_KEY,data);const journal=readJson(JOURNAL_KEY,{});if(journal&&journal[item.id]){delete journal[item.id];writeJson(JOURNAL_KEY,journal)}}
async function deleteMediaPhoto(itemId){if(mediaDeleteBusy)return;const data=readJson(DATA_KEY,{}),item=(Array.isArray(data.media)?data.media:[]).find(row=>String(row?.id)===String(itemId));if(!item){notify('This photo is no longer in the Media Library.');return}if(!canDelete(item)){notify('Only the photo owner or an Admin can delete this photo.');return}if(!verifyAdminForOtherOwner(data,item))return;if(!confirm(`Permanently delete “${item.name||'this photo'}”? This removes it from Media and any Memory that uses it.`))return;if(!window.firebase?.database||!currentUser()){notify('Sign in and connect to Firebase before deleting photos.');return}mediaDeleteBusy=true;try{notify('Deleting photo…');await deleteStorage(item);await firebase.database().ref(recordPath(data,'media',item)).remove();await cleanupMemories(data,item);cleanupLocal(data,item);notify('Photo deleted.');setTimeout(()=>location.reload(),250)}catch(error){console.error('Photo delete failed',error);const code=error?.code?` (${error.code})`:'';notify(`Photo could not be deleted${code}: ${error?.message||'Please try again.'}`)}finally{mediaDeleteBusy=false}}
function enhanceMediaDeletes(){if(!window.app||!document.body)return;window.app.deleteMediaPhoto=deleteMediaPhoto;const card=[...document.querySelectorAll('#view .card')].find(node=>node.querySelector(':scope > h2')?.textContent.trim()==='Media Library');if(!card)return;const data=readJson(DATA_KEY,{}),rows=Array.isArray(data.media)?data.media:[];card.querySelectorAll('.mediaGrid .mediaTile').forEach(tile=>{if(tile.querySelector('[data-ofa-photo-delete]'))return;const image=tile.querySelector('.photoThumb img'),src=image?.src||image?.getAttribute('src')||'',item=rows.find(row=>row?.id&&row?.url&&sameUrl(row.url,src));if(!item||!canDelete(item))return;const actions=tile.querySelector('.mediaActions')||tile;const button=document.createElement('button');button.type='button';button.className='danger';button.dataset.ofaPhotoDelete=item.id;button.textContent='Delete Photo';button.setAttribute('aria-label',`Delete ${item.name||'photo'}`);button.onclick=()=>deleteMediaPhoto(item.id);actions.appendChild(button)})}
function start(){setTitle();setStoredVersion();const title=document.querySelector('title');if(title){const observer=new MutationObserver(setTitle);observer.observe(title,{childList:true,characterData:true,subtree:true});window.OFAVersionTitleGuard=observer}window.OFAVersion=RELEASE;enhanceMediaDeletes();if(document.body){mediaDeleteObserver=new MutationObserver(()=>queueMicrotask(enhanceMediaDeletes));mediaDeleteObserver.observe(document.body,{childList:true,subtree:true});window.OFAMediaDeleteObserver=mediaDeleteObserver}window.addEventListener('hashchange',()=>setTimeout(enhanceMediaDeletes,0))}
if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(rows=>rows.forEach(registration=>{registration.update().catch(()=>{});registration.waiting?.postMessage({type:'SKIP_WAITING'});registration.active?.postMessage({type:'CLEAR_OLD_CACHES'})})).catch(()=>{});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();